# Generated by Django 5.2.12 on 2026-04-15 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0013_prescriptionbatch_batch_no_non_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'medical'), (1, 'exercise'), (2, 'diet')], db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('due_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat_type', models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'daily'), (2, 'weekly')], default=0)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'high'), (1, 'medium'), (2, 'low')], db_index=True, default=1)),
                ('business_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('business_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'manual'), (1, 'ai'), (2, 'report')], db_index=True, default=0)),
                ('notification_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='medical.member')),
            ],
            options={
                'db_table': 'task',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'medical'), (1, 'exercise'), (2, 'diet')], db_index=True)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('due_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat_type', models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'daily'), (2, 'weekly')], default=0)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'high'), (1, 'medium'), (2, 'low')], default=1)),
                ('business_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('business_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'manual'), (1, 'ai'), (2, 'report')], db_index=True, default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'ignored'), (3, 'expired')], db_index=True, default=0)),
                ('extract_payload', models.JSONField(blank=True, default=dict)),
                ('task_payload', models.JSONField(blank=True, default=dict)),
                ('similarity_payload', models.JSONField(blank=True, default=dict)),
                ('ignored_reason', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_cards', to='task_system.task')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cards', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cards', to='medical.member')),
            ],
            options={
                'db_table': 'task_card',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0)),
                ('meal_type', models.CharField(db_index=True, default='breakfast', max_length=32)),
                ('calorie_target', models.PositiveIntegerField(default=0)),
                ('food_recommend', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='manual', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_tasks_operated', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_diet', to='task_system.task')),
            ],
            options={
                'db_table': 'task_diet',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('business_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('related_sub_type', models.CharField(blank=True, choices=[('task_medical', 'task_medical'), ('task_exercise', 'task_exercise'), ('task_diet', 'task_diet')], default='', max_length=32)),
                ('related_sub_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'done'), (2, 'skipped'), (3, 'failed')], db_index=True)),
                ('executed_at', models.DateTimeField(db_index=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='medical.member')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='task_system.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_execution',
                'ordering': ['-executed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0)),
                ('exercise_type', models.CharField(db_index=True, max_length=64)),
                ('duration_min', models.PositiveIntegerField(default=0)),
                ('intensity', models.CharField(default='medium', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='manual', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_tasks_operated', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_exercise', to='task_system.task')),
            ],
            options={
                'db_table': 'task_exercise',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0)),
                ('reminder_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('medical_task_type', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='manual', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_tasks_operated', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_medical', to='task_system.task')),
            ],
            options={
                'db_table': 'task_medical',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('channel', models.CharField(choices=[('local', 'local'), ('apns', 'apns'), ('sms', 'sms')], default='local', max_length=16)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'sent'), (2, 'failed')], db_index=True, default=0)),
                ('template_code', models.CharField(default='health_task_default', max_length=64)),
                ('template_params', models.JSONField(blank=True, default=dict)),
                ('reminder_time', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, default='', max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to='medical.member')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task_system.task')),
            ],
            options={
                'db_table': 'task_notification',
                'ordering': ['-reminder_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to='medical.member')),
            ],
            options={
                'db_table': 'task_plan',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'status'], name='task_member__68deaa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'updated_at'], name='task_member__410eec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'type', 'status'], name='task_member__3ee565_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'business_type', 'business_id'], name='task_member__6d62cc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcard',
            index=models.Index(fields=['member', 'status'], name='task_card_member__c004eb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcard',
            index=models.Index(fields=['member', 'updated_at'], name='task_card_member__1c2f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcard',
            index=models.Index(fields=['member', 'type', 'status'], name='task_card_member__15d5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task', 'executed_at'], name='task_execut_task_id_2156f9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['member', 'status', 'executed_at'], name='task_execut_member__6fd851_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['task', 'status'], name='task_notifi_task_id_7946c0_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['member', 'status', 'reminder_time'], name='task_notifi_member__b1e07d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskplan',
            index=models.Index(fields=['member', 'status'], name='task_plan_member__64d3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskplan',
            index=models.Index(fields=['member', 'updated_at'], name='task_plan_member__cefaf2_idx'),
        ),
    ]
