# Generated by Django 5.2.12 on 2026-06-03 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'medical'), (1, 'exercise'), (2, 'diet')], db_index=True, verbose_name='任务类型')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态')),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间')),
                ('due_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='截止时间')),
                ('repeat_type', models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'daily'), (2, 'weekly')], default=0, verbose_name='重复类型')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'high'), (1, 'medium'), (2, 'low')], db_index=True, default=1, verbose_name='优先级')),
                ('business_type', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务类型')),
                ('business_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务 ID')),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'manual'), (1, 'ai'), (2, 'report')], db_index=True, default=0, verbose_name='任务来源')),
                ('notification_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='通知标识')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='medical.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态')),
                ('meal_type', models.CharField(db_index=True, default='breakfast', max_length=32, verbose_name='餐次类型')),
                ('calorie_target', models.PositiveIntegerField(default=0, verbose_name='目标热量')),
                ('food_recommend', models.JSONField(blank=True, default=list, verbose_name='食物建议')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('source', models.CharField(default='manual', max_length=16, verbose_name='来源')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_tasks_operated', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_diet', to='task_system.task', verbose_name='主任务')),
            ],
            options={
                'verbose_name': '饮食任务',
                'verbose_name_plural': '饮食任务',
                'db_table': 'task_diet',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务类型')),
                ('business_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务 ID')),
                ('related_sub_type', models.CharField(blank=True, choices=[('task_medical', 'task_medical'), ('task_exercise', 'task_exercise'), ('task_diet', 'task_diet')], default='', max_length=32, verbose_name='关联子类型')),
                ('related_sub_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='关联子 ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'done'), (2, 'skipped'), (3, 'failed')], db_index=True, verbose_name='执行状态')),
                ('executed_at', models.DateTimeField(db_index=True, verbose_name='执行时间')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='执行数据')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='medical.member', verbose_name='成员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='task_system.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行用户')),
            ],
            options={
                'verbose_name': '任务执行记录',
                'verbose_name_plural': '任务执行记录',
                'db_table': 'task_execution',
                'ordering': ['-executed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态')),
                ('exercise_type', models.CharField(db_index=True, max_length=64, verbose_name='运动类型')),
                ('duration_min', models.PositiveIntegerField(default=0, verbose_name='时长（分钟）')),
                ('intensity', models.CharField(default='medium', max_length=16, verbose_name='强度')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('source', models.CharField(default='manual', max_length=16, verbose_name='来源')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_tasks_operated', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_exercise', to='task_system.task', verbose_name='主任务')),
            ],
            options={
                'verbose_name': '运动任务',
                'verbose_name_plural': '运动任务',
                'db_table': 'task_exercise',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态')),
                ('reminder_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='提醒时间')),
                ('medical_task_type', models.CharField(db_index=True, max_length=64, verbose_name='医疗任务类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('source', models.CharField(default='manual', max_length=16, verbose_name='来源')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_tasks_operated', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_medical', to='task_system.task', verbose_name='主任务')),
            ],
            options={
                'verbose_name': '医疗任务',
                'verbose_name_plural': '医疗任务',
                'db_table': 'task_medical',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('channel', models.CharField(choices=[('local', 'local'), ('apns', 'apns'), ('sms', 'sms')], default='local', max_length=16, verbose_name='通知渠道')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'sent'), (2, 'failed')], db_index=True, default=0, verbose_name='通知状态')),
                ('template_code', models.CharField(default='health_task_default', max_length=64, verbose_name='模板编码')),
                ('template_params', models.JSONField(blank=True, default=dict, verbose_name='模板参数')),
                ('reminder_time', models.DateTimeField(db_index=True, verbose_name='提醒时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('failed_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='失败原因')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to='medical.member', verbose_name='成员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task_system.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务提醒',
                'verbose_name_plural': '任务提醒',
                'db_table': 'task_notification',
                'ordering': ['-reminder_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='计划状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to='medical.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '任务计划',
                'verbose_name_plural': '任务计划',
                'db_table': 'task_plan',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'status'], name='task_member__68deaa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'updated_at'], name='task_member__410eec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'type', 'status'], name='task_member__3ee565_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'business_type', 'business_id'], name='task_member__6d62cc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task', 'executed_at'], name='task_execut_task_id_2156f9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['member', 'status', 'executed_at'], name='task_execut_member__6fd851_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['task', 'status'], name='task_notifi_task_id_7946c0_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['member', 'status', 'reminder_time'], name='task_notifi_member__b1e07d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskplan',
            index=models.Index(fields=['member', 'status'], name='task_plan_member__64d3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskplan',
            index=models.Index(fields=['member', 'updated_at'], name='task_plan_member__cefaf2_idx'),
        ),
    ]
