# Generated by Django 5.2.12 on 2026-04-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_prescriptionbatch_batch_no_non_unique'),
        ('task_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelOptions(
            name='taskdiet',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '饮食任务', 'verbose_name_plural': '饮食任务'},
        ),
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'ordering': ['-executed_at', '-id'], 'verbose_name': '任务执行记录', 'verbose_name_plural': '任务执行记录'},
        ),
        migrations.AlterModelOptions(
            name='taskexercise',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '运动任务', 'verbose_name_plural': '运动任务'},
        ),
        migrations.AlterModelOptions(
            name='taskmedical',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '医疗任务', 'verbose_name_plural': '医疗任务'},
        ),
        migrations.AlterModelOptions(
            name='tasknotification',
            options={'ordering': ['-reminder_time', '-id'], 'verbose_name': '任务提醒', 'verbose_name_plural': '任务提醒'},
        ),
        migrations.AlterModelOptions(
            name='taskplan',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '任务计划', 'verbose_name_plural': '任务计划'},
        ),
        migrations.AlterField(
            model_name='task',
            name='business_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务 ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='business_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='medical.member', verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='通知标识'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'high'), (1, 'medium'), (2, 'low')], db_index=True, default=1, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'daily'), (2, 'weekly')], default=0, verbose_name='重复类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(0, 'manual'), (1, 'ai'), (2, 'report')], db_index=True, default=0, verbose_name='任务来源'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'medical'), (1, 'exercise'), (2, 'diet')], db_index=True, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='calorie_target',
            field=models.PositiveIntegerField(default=0, verbose_name='目标热量'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='food_recommend',
            field=models.JSONField(blank=True, default=list, verbose_name='食物建议'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='meal_type',
            field=models.CharField(db_index=True, default='breakfast', max_length=32, verbose_name='餐次类型'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_tasks_operated', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='source',
            field=models.CharField(default='manual', max_length=16, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_diet', to='task_system.task', verbose_name='主任务'),
        ),
        migrations.AlterField(
            model_name='taskdiet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='business_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务 ID'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='business_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='executed_at',
            field=models.DateTimeField(db_index=True, verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='medical.member', verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='related_sub_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='关联子 ID'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='related_sub_type',
            field=models.CharField(blank=True, choices=[('task_medical', 'task_medical'), ('task_exercise', 'task_exercise'), ('task_diet', 'task_diet')], default='', max_length=32, verbose_name='关联子类型'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'done'), (2, 'skipped'), (3, 'failed')], db_index=True, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='task_system.task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行用户'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='value',
            field=models.JSONField(blank=True, default=dict, verbose_name='执行数据'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='duration_min',
            field=models.PositiveIntegerField(default=0, verbose_name='时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='exercise_type',
            field=models.CharField(db_index=True, max_length=64, verbose_name='运动类型'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='intensity',
            field=models.CharField(default='medium', max_length=16, verbose_name='强度'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_tasks_operated', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='source',
            field=models.CharField(default='manual', max_length=16, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_exercise', to='task_system.task', verbose_name='主任务'),
        ),
        migrations.AlterField(
            model_name='taskexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='medical_task_type',
            field=models.CharField(db_index=True, max_length=64, verbose_name='医疗任务类型'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_tasks_operated', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='reminder_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='提醒时间'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='source',
            field=models.CharField(default='manual', max_length=16, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'canceled')], db_index=True, default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_medical', to='task_system.task', verbose_name='主任务'),
        ),
        migrations.AlterField(
            model_name='taskmedical',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='channel',
            field=models.CharField(choices=[('local', 'local'), ('apns', 'apns'), ('sms', 'sms')], default='local', max_length=16, verbose_name='通知渠道'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='failed_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to='medical.member', verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='reminder_time',
            field=models.DateTimeField(db_index=True, verbose_name='提醒时间'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'sent'), (2, 'failed')], db_index=True, default=0, verbose_name='通知状态'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task_system.task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='template_code',
            field=models.CharField(default='health_task_default', max_length=64, verbose_name='模板编码'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='template_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='模板参数'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to='medical.member', verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='status',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='计划状态'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='taskplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.DeleteModel(
            name='TaskCard',
        ),
    ]
