from django.urls import path

from hospital_care.api.backoffice.views import (
    AgentDetailView,
    AgentReviewView,
    DepartmentDetailView,
    HospitalActivateView,
    HospitalAgentFormOptionsView,
    HospitalAgentListCreateView,
    HospitalAuditLogView,
    HospitalDepartmentListCreateView,
    HospitalDetailView,
    HospitalDoctorDetailView,
    HospitalDoctorListView,
    HospitalKnowledgeBaseListCreateView,
    HospitalListCreateView,
    HospitalStaffDetailView,
    HospitalStaffListCreateView,
    HospitalSuspendView,
    KnowledgeBaseDetailView,
    KnowledgeDocumentDetailView,
    KnowledgeDocumentListCreateView,
    KnowledgeVectorBuildView,
)

urlpatterns = [
    path("hospitals/", HospitalListCreateView.as_view(), name="hospital-care-admin-hospitals"),
    path("hospitals/<uuid:hospital_id>/", HospitalDetailView.as_view(), name="hospital-care-admin-hospital-detail"),
    path("hospitals/<uuid:hospital_id>/activate/", HospitalActivateView.as_view(), name="hospital-care-admin-activate"),
    path("hospitals/<uuid:hospital_id>/suspend/", HospitalSuspendView.as_view(), name="hospital-care-admin-suspend"),
    path("hospitals/<uuid:hospital_id>/departments/", HospitalDepartmentListCreateView.as_view(), name="hospital-care-admin-departments"),
    path("departments/<uuid:department_id>/", DepartmentDetailView.as_view(), name="hospital-care-admin-department-detail"),
    path("hospitals/<uuid:hospital_id>/staff/", HospitalStaffListCreateView.as_view(), name="hospital-care-admin-staff"),
    path("staff/<uuid:staff_id>/", HospitalStaffDetailView.as_view(), name="hospital-care-admin-staff-detail"),
    path("hospitals/<uuid:hospital_id>/doctors/", HospitalDoctorListView.as_view(), name="hospital-care-admin-doctors"),
    path("doctors/<uuid:doctor_id>/", HospitalDoctorDetailView.as_view(), name="hospital-care-admin-doctor-detail"),
    path("hospitals/<uuid:hospital_id>/agent-form-options/", HospitalAgentFormOptionsView.as_view(), name="hospital-care-admin-agent-form-options"),
    path("hospitals/<uuid:hospital_id>/agents/", HospitalAgentListCreateView.as_view(), name="hospital-care-admin-agents"),
    path("agents/<uuid:agent_id>/", AgentDetailView.as_view(), name="hospital-care-admin-agent-detail"),
    path("agents/<uuid:agent_id>/review/", AgentReviewView.as_view(), name="hospital-care-admin-agent-review"),
    path("hospitals/<uuid:hospital_id>/knowledge-bases/", HospitalKnowledgeBaseListCreateView.as_view(), name="hospital-care-admin-knowledge-bases"),
    path("knowledge-bases/<uuid:profile_id>/", KnowledgeBaseDetailView.as_view(), name="hospital-care-admin-knowledge-detail"),
    path("knowledge-bases/<uuid:profile_id>/documents/", KnowledgeDocumentListCreateView.as_view(), name="hospital-care-admin-knowledge-documents"),
    path(
        "knowledge-bases/<uuid:profile_id>/documents/<uuid:document_id>/",
        KnowledgeDocumentDetailView.as_view(),
        name="hospital-care-admin-knowledge-document-detail",
    ),
    path("knowledge-bases/<uuid:profile_id>/vector-build/", KnowledgeVectorBuildView.as_view(), name="hospital-care-admin-knowledge-vector-build"),
    path("hospitals/<uuid:hospital_id>/audit-logs/", HospitalAuditLogView.as_view(), name="hospital-care-admin-audit"),
]
