import type { RouteRecordRaw } from 'vue-router';

export const constantRoutes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('../views/LoginView.vue'),
    meta: { public: true },
  },
  {
    path: '/',
    component: () => import('../layouts/AdminLayout.vue'),
    children: [
      { path: '', redirect: '/dashboard' },
      { path: '/dashboard', name: 'Dashboard', component: () => import('../views/DashboardView.vue'), meta: { title: '仪表盘', keepAlive: true } },
      { path: '/tasks', name: 'Tasks', component: () => import('../views/TasksDashboardView.vue'), meta: { title: '异步任务看板' } },
      { path: '/tasks/manager', name: 'TasksManager', component: () => import('../views/TasksManagerView.vue'), meta: { title: '异步任务管理' } },
      { path: '/users', name: 'Users', component: () => import('../views/UsersView.vue'), meta: { title: '用户管理' } },
      { path: '/users/devices', name: 'Devices', component: () => import('../views/DevicesView.vue'), meta: { title: '设备管理' } },
      { path: '/users/deactivations', name: 'Deactivations', component: () => import('../views/DeactivationsView.vue'), meta: { title: '注销管理' } },
      { path: '/users/blacklist', name: 'Blacklist', component: () => import('../views/BlacklistView.vue'), meta: { title: '黑名单管理' } },
      { path: '/conversations/users', name: 'ConversationUsers', component: () => import('../views/ConversationUsersView.vue'), meta: { title: '用户对话', superAdminOnly: true, keepAlive: true } },
      { path: '/conversations/users/:userId', name: 'ConversationUserThreads', component: () => import('../views/ConversationUserThreadsView.vue'), meta: { title: '用户会话详情', superAdminOnly: true, keepAlive: true } },
      { path: '/conversations/quick-questions', name: 'ConversationQuickQuestions', component: () => import('../views/ConversationQuickQuestionsView.vue'), meta: { title: '快捷问题配置', superAdminOnly: true, keepAlive: true } },
      { path: '/medical-data/users', name: 'MedicalDataUsers', component: () => import('../views/MedicalDataUsersView.vue'), meta: { title: '用户医疗数据' } },
      { path: '/medical-data/users/:userId', name: 'MedicalDataUserMembers', component: () => import('../views/MedicalDataUserMembersView.vue'), meta: { title: '用户成员医疗数据' } },
      {
        path: '/medical-data/users/:userId/members/:memberId',
        name: 'MedicalDataMember',
        component: () => import('../views/MedicalDataMemberView.vue'),
        meta: { title: '成员医疗数据' },
      },
      { path: '/medical-data/quality', name: 'MedicalDataQuality', component: () => import('../views/MedicalDataQualityView.vue'), meta: { title: '数据质检' } },
      { path: '/medical-data/attachments', name: 'MedicalDataAttachments', component: () => import('../views/MedicalDataAttachmentsView.vue'), meta: { title: '附件与识别' } },
      { path: '/medical-data/analytics', name: 'MedicalDataAnalytics', component: () => import('../views/MedicalDataAnalyticsView.vue'), meta: { title: '医疗数据统计' } },
      { path: '/articles/overview', name: 'ArticleOverview', component: () => import('../views/articles/ArticleOverviewView.vue'), meta: { title: '文章总览', keepAlive: true } },
      { path: '/articles/list', name: 'ArticleList', component: () => import('../views/articles/ArticleListView.vue'), meta: { title: '文章管理', keepAlive: true } },
      { path: '/articles/new', name: 'ArticleCreate', component: () => import('../views/articles/ArticleEditorView.vue'), meta: { title: '新建文章' } },
      { path: '/articles/:id/edit', name: 'ArticleEdit', component: () => import('../views/articles/ArticleEditorView.vue'), meta: { title: '编辑文章' } },
      { path: '/articles/categories', name: 'ArticleCategories', component: () => import('../views/articles/ArticleCategoriesView.vue'), meta: { title: '分类管理', keepAlive: true } },
      { path: '/articles/tags', name: 'ArticleTags', component: () => import('../views/articles/ArticleTagsView.vue'), meta: { title: '标签管理', keepAlive: true } },
      { path: '/articles/locales', name: 'ArticleLocales', component: () => import('../views/articles/ArticleLocalesView.vue'), meta: { title: '多语言管理' } },
      { path: '/articles/:id/versions', name: 'ArticleVersions', component: () => import('../views/articles/ArticleVersionsView.vue'), meta: { title: '版本记录' } },
      { path: '/articles/analytics', name: 'ArticleAnalytics', component: () => import('../views/articles/ArticleAnalyticsView.vue'), meta: { title: '阅读数据', keepAlive: true } },
      { path: '/articles/compliance', name: 'ArticleCompliance', component: () => import('../views/articles/ArticleComplianceView.vue'), meta: { title: '来源合规', keepAlive: true } },
      { path: '/articles/recycle-bin', name: 'ArticleRecycleBin', component: () => import('../views/articles/ArticleRecycleBinView.vue'), meta: { title: '回收站' } },
      { path: '/notifications/overview', name: 'NotificationOverview', component: () => import('../views/NotificationOverviewView.vue'), meta: { title: '通知中心总览' } },
      { path: '/notifications/users', name: 'NotificationUsers', component: () => import('../views/NotificationUsersView.vue'), meta: { title: '通知用户列表' } },
      { path: '/notifications/templates', name: 'NotificationTemplates', component: () => import('../views/NotificationTemplatesView.vue'), meta: { title: '通知模板' } },
      { path: '/notifications/campaigns', name: 'NotificationCampaigns', component: () => import('../views/NotificationCampaignsView.vue'), meta: { title: '发送活动' } },
      { path: '/notifications/records/all', name: 'NotificationAllRecords', component: () => import('../views/NotificationAllRecordsView.vue'), meta: { title: '全渠道记录', channel: 'all' } },
      { path: '/notifications/apns', name: 'NotificationAPNs', component: () => import('../views/NotificationAPNsView.vue'), meta: { title: 'APNs发送记录', channel: 'apns' } },
      { path: '/notifications/sms', name: 'NotificationSMS', component: () => import('../views/NotificationSMSView.vue'), meta: { title: '短信发送记录', channel: 'sms' } },
      { path: '/notifications/email', name: 'NotificationEmail', component: () => import('../views/NotificationEmailView.vue'), meta: { title: '邮箱发送记录', channel: 'email' } },
      { path: '/notifications/suppressions', name: 'NotificationSuppressions', component: () => import('../views/NotificationSuppressionsView.vue'), meta: { title: '异常与抑制' } },
      { path: '/notifications/analytics', name: 'NotificationAnalytics', component: () => import('../views/NotificationAnalyticsView.vue'), meta: { title: '统计分析' } },
      { path: '/notifications/channel-settings', name: 'NotificationChannelSettings', component: () => import('../views/NotificationChannelSettingsView.vue'), meta: { title: '渠道设置' } },
      { path: '/version/configs', name: 'VersionConfigs', component: () => import('../views/VersionConfigsView.vue'), meta: { title: '版本配置' } },
      { path: '/version/logs', name: 'VersionLogs', component: () => import('../views/VersionLogsView.vue'), meta: { title: '检查日志' } },
      {
        path: '/ai-config/scenarios/:scenarioKey',
        name: 'AIScenarioModels',
        component: () => import('../views/AIScenarioModelsView.vue'),
        meta: { title: '场景模型' },
      },
      { path: '/ai-config/scenarios', name: 'AIScenarios', component: () => import('../views/AIScenariosView.vue'), meta: { title: 'AI场景配置' } },
      { path: '/ai-config/models', name: 'AIModels', component: () => import('../views/AIModelsView.vue'), meta: { title: '模型目录' } },
      { path: '/ai-config/small-tasks', name: 'AISmallTasks', component: () => import('../views/AISmallTasksView.vue'), meta: { title: 'AI小任务' } },
      { path: '/ai-config/providers', name: 'AIProviders', component: () => import('../views/AIProvidersView.vue'), meta: { title: 'Provider配置' } },
      { path: '/ai-config/trials', name: 'AITrials', component: () => import('../views/AITrialsView.vue'), meta: { title: '试用期' } },
      { path: '/rbac', name: 'RBAC', component: () => import('../views/RBACView.vue'), meta: { title: '权限管理' } },
      {
        path: '/audit',
        component: () => import('../views/AuditView.vue'),
        children: [
          { path: '', redirect: '/audit/admin' },
          { path: 'admin', name: 'OperatorAudit', component: () => import('../views/audit/OperatorAuditView.vue'), meta: { title: '操作员日志', keepAlive: true } },
          { path: 'system', name: 'SystemLog', component: () => import('../views/audit/SystemLogView.vue'), meta: { title: '系统日志', keepAlive: true } },
        ],
      },
    ],
  },
];
