"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CircleHelp, RotateCw, ShieldCheck } from "lucide-react";
import { SparkAuthApi } from "@/lib/api/auth-api";
import { SparkApiError, SparkHttpClient } from "@/lib/api/http-client";
import { getOrCreateWebDeviceId, normalizeMainlandPhone, phoneOtpErrorMessage } from "@/lib/auth/phone";
import { authDiagnosticLog, createAuthRequestId, deviceLogSuffix, maskPhone } from "@/lib/auth/diagnostics";
import { useAuth } from "@/context/AuthContext";

export default function PhoneLoginPage() {
  const router = useRouter(); const auth = useAuth();
  const [phone, setPhone] = useState(""); const [code, setCode] = useState(""); const [otpId, setOtpId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [expires, setExpires] = useState<number | null>(null); const codeRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!otpId || !expires) return; const timer = window.setInterval(() => setExpires((value) => value && value > 0 ? value - 1 : 0), 1000); return () => window.clearInterval(timer); }, [otpId, expires]);
  const requestOtp = async () => { const requestId = createAuthRequestId("request"); const startedAt = Date.now(); const normalizedPhone = normalizeMainlandPhone(phone); if (!normalizedPhone) { authDiagnosticLog("warn", "browser", "phone_otp.request.validation_failed", { request_id: requestId, phone: maskPhone(phone) }); setError("请输入正确的中国大陆手机号"); return; } const deviceId = getOrCreateWebDeviceId(); authDiagnosticLog("info", "browser", "phone_otp.request.started", { request_id: requestId, phone: maskPhone(normalizedPhone), device: deviceLogSuffix(deviceId) }); setBusy(true); setError(null); try { const api = new SparkAuthApi(new SparkHttpClient({ baseUrl: "" })); const data = await api.requestPhoneOtp({ phone_number: normalizedPhone, bundle_id: "cn.Zhaodk.Health.web", device_id: deviceId, scene: "login" }, requestId); authDiagnosticLog("info", "browser", "phone_otp.request.succeeded", { request_id: requestId, duration_ms: Date.now() - startedAt, expires_in: data.expires_in }); setPhone(normalizedPhone); setOtpId(data.otp_id); setExpires(data.expires_in); } catch (cause) { const failure = cause instanceof SparkApiError ? cause.failure : null; authDiagnosticLog("error", "browser", "phone_otp.request.failed", { request_id: failure?.requestId || requestId, duration_ms: Date.now() - startedAt, http_status: failure?.httpStatus, business_code: failure?.code, retryable: failure?.retryable, network_error: failure?.message, error_type: cause instanceof Error ? cause.name : typeof cause }); setError(phoneOtpErrorMessage(cause, "request")); } finally { setBusy(false); } };
  const verify = async () => { if (!otpId) return; const requestId = createAuthRequestId("verify"); const startedAt = Date.now(); const normalizedPhone = normalizeMainlandPhone(phone); if (!normalizedPhone) { authDiagnosticLog("warn", "browser", "phone_otp.verify.validation_failed", { request_id: requestId, phone: maskPhone(phone) }); setError("手机号格式错误，请重新获取验证码"); return; } const deviceId = getOrCreateWebDeviceId(); authDiagnosticLog("info", "browser", "phone_otp.verify.started", { request_id: requestId, phone: maskPhone(normalizedPhone), device: deviceLogSuffix(deviceId) }); setBusy(true); setError(null); try { const api = new SparkAuthApi(new SparkHttpClient({ baseUrl: "" })); const token = await api.verifyPhoneOtp({ otp_id: otpId, phone_number: normalizedPhone, code, bundle_id: "cn.Zhaodk.Health.web", device_id: deviceId }, requestId); authDiagnosticLog("info", "browser", "phone_otp.verify.succeeded", { request_id: requestId, duration_ms: Date.now() - startedAt }); await auth.login(token); router.replace("/chat" as never); } catch (cause) { const failure = cause instanceof SparkApiError ? cause.failure : null; authDiagnosticLog("error", "browser", "phone_otp.verify.failed", { request_id: failure?.requestId || requestId, duration_ms: Date.now() - startedAt, http_status: failure?.httpStatus, business_code: failure?.code, retryable: failure?.retryable, error_type: cause instanceof Error ? cause.name : typeof cause }); setError(phoneOtpErrorMessage(cause, "verify")); } finally { setBusy(false); } };
  const updateCode = (value: string) => { const next = value.replace(/\D/g, "").slice(0, 6); setCode(next); };
  return <main className="login-page"><section className="login-card login-card--otp" role="dialog" aria-modal="true" aria-labelledby="phone-title"><div className="login-modal-header"><button className="login-icon-button" aria-label="返回登录方式" onClick={() => router.push("/login" as never)}><ArrowLeft size={18} /></button><h1 id="phone-title">{otpId ? "输入 6 位验证码" : "手机号登录"}</h1><button className="login-icon-button" aria-label="登录帮助"><CircleHelp size={18} /></button></div>{otpId ? <div className="otp-content"><p className="login-subtitle">验证码已发送至 <strong>{phone}</strong></p><div className="otp-boxes" aria-label="6 位验证码"><input ref={codeRef} className="otp-hidden-input" value={code} onChange={(event) => updateCode(event.target.value)} inputMode="numeric" autoComplete="one-time-code" aria-label="输入验证码" autoFocus />{Array.from({ length: 6 }, (_, index) => <span className={`otp-box ${code[index] ? "otp-box--filled" : ""} ${error ? "otp-box--error" : ""}`} key={index}>{code[index] || ""}</span>)}</div><button className="otp-resend" disabled={busy || Boolean(expires)} onClick={() => { setOtpId(null); setCode(""); void requestOtp(); }}>{expires ? `重新发送 ${expires}s` : <><RotateCw size={13} />重新发送</>}</button><button className="login-option" onClick={() => void verify()} disabled={busy || code.length !== 6}>{busy ? "正在验证…" : "确认登录"}</button></div> : <div className="phone-content"><p className="login-subtitle">使用手机号接收一次性验证码</p><label className="login-field"><span>手机号</span><div className="phone-input"><span>+86</span><input value={phone} onChange={(event) => { setPhone(event.target.value.replace(/[^\d\s()-]/g, "")); setError(null); }} inputMode="tel" autoComplete="tel-national" placeholder="请输入 11 位手机号" maxLength={20} autoFocus /></div></label><button className="login-option" onClick={() => void requestOtp()} disabled={busy || !normalizeMainlandPhone(phone)}>{busy ? "正在发送…" : "下一步"}</button></div>}{error && <p role="alert" className="login-error">{error}</p>}<p className="login-security"><ShieldCheck size={14} />验证码仅用于本次登录，不会保存</p></section></main>;
}
