# Generated by Django 5.2.12 on 2026-05-26 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('original_name', models.CharField(max_length=255)),
                ('file_ext', models.CharField(blank=True, default='', max_length=32)),
                ('mime_type', models.CharField(blank=True, default='application/octet-stream', max_length=128)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_md5', models.CharField(blank=True, default='', max_length=64)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('object_key', models.CharField(blank=True, default='', max_length=1024)),
                ('storage_type', models.CharField(blank=True, default='oss', max_length=32)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManagedFileBusinessRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(db_index=True, max_length=64)),
                ('business_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_relations', to='file_manager.managedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_file_business_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['user', 'is_deleted', 'updated_at'], name='file_manage_user_id_d219e6_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfilebusinessrelation',
            index=models.Index(fields=['user', 'business_type', 'business_id'], name='file_manage_user_id_1ba16e_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfilebusinessrelation',
            index=models.Index(fields=['business_type', 'business_id'], name='file_manage_busines_15553a_idx'),
        ),
        migrations.AddConstraint(
            model_name='managedfilebusinessrelation',
            constraint=models.UniqueConstraint(fields=('file', 'business_type', 'business_id'), name='uniq_managed_file_business_relation'),
        ),
    ]
