# Generated by Django 6.0.3 on 2026-04-03 13:30

import django.db.models.deletion
import file_manager.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_uuid", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("file", models.FileField(max_length=512, upload_to=file_manager.models.upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("file_ext", models.CharField(blank=True, default="", max_length=32)),
                ("mime_type", models.CharField(blank=True, default="application/octet-stream", max_length=128)),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_md5", models.CharField(blank=True, default="", max_length=64)),
                ("is_public", models.BooleanField(db_index=True, default=False)),
                ("business_type", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("business_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "is_deleted", "updated_at"], name="file_manage_user_id_70bdce_idx"),
                    models.Index(
                        fields=["user", "business_type", "business_id", "is_deleted"],
                        name="file_manage_user_id_4ff21a_idx",
                    ),
                ],
            },
        ),
    ]
