# Generated by Django 6.0.3 on 2026-04-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='managedfile',
            new_name='file_manage_user_id_d219e6_idx',
            old_name='file_manage_user_id_70bdce_idx',
        ),
        migrations.RenameIndex(
            model_name='managedfile',
            new_name='file_manage_user_id_1f7ea3_idx',
            old_name='file_manage_user_id_4ff21a_idx',
        ),
    ]
