# Generated by Django 5.2.12 on 2026-04-09 02:49

from django.db import migrations, models


def _managed_file_upload_to(instance, filename):
    return f"managed_files/{instance.user_id}/{instance.file_uuid}/{filename}"


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_managedfile_oss_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfile',
            name='file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=_managed_file_upload_to),
        ),
    ]
