from __future__ import annotations

from typing import Any

from common.exceptions import APIError


ERROR_HTTP: dict[str, int] = {
    "HOSPITAL_NOT_FOUND": 404,
    "HOSPITAL_INACTIVE": 409,
    "HOSPITAL_CODE_CONFLICT": 409,
    "HOSPITAL_VERSION_CONFLICT": 409,
    "HOSPITAL_ACTIVATE_INVALID": 409,
    "DEPARTMENT_NOT_FOUND": 404,
    "DEPARTMENT_PARENT_INVALID": 400,
    "STAFF_NOT_FOUND": 404,
    "STAFF_ALREADY_EXISTS": 409,
    "STAFF_LAST_ADMIN": 409,
    "STAFF_ROLE_LOCKED": 409,
    "DOCTOR_PROFILE_NOT_ACTIVE": 403,
    "DOCTOR_ROLE_REQUIRED": 400,
    "MEMBER_ACCESS_DENIED": 403,
    "HOSPITAL_MEMBERSHIP_REQUIRED": 403,
    "AGENT_NOT_FOUND": 404,
    "AGENT_NOT_PUBLISHED": 409,
    "AGENT_VERSION_CONFLICT": 409,
    "AGENT_REVIEW_INVALID": 409,
    "KNOWLEDGE_BASE_FORBIDDEN": 403,
    "AGENT_DOCTOR_INVALID": 400,
    "AGENT_DEPARTMENT_INVALID": 400,
    "AGENT_BASE_MODEL_UNAVAILABLE": 409,
    "HOSPITAL_KNOWLEDGE_NOT_FOUND": 404,
    "HOSPITAL_KNOWLEDGE_VERSION_CONFLICT": 409,
    "HOSPITAL_KNOWLEDGE_EMBEDDING_UNAVAILABLE": 409,
    "HOSPITAL_KNOWLEDGE_DOCUMENT_NOT_FOUND": 404,
    "HOSPITAL_KNOWLEDGE_CURSOR_INVALID": 409,
    "HOSPITAL_KNOWLEDGE_SYNC_UNAVAILABLE": 503,
    "CONVERSATION_NOT_FOUND": 404,
    "CONVERSATION_NOT_ASSIGNED": 403,
    "CONVERSATION_ENDED": 409,
    "CONVERSATION_VERSION_CONFLICT": 409,
    "CONVERSATION_REBIND_FORBIDDEN": 409,
    "PATIENT_CONSENT_REQUIRED": 403,
    "IDEMPOTENCY_CONFLICT": 409,
    "IDEMPOTENCY_KEY_REQUIRED": 400,
    "REGISTRATION_INTEGRATION_UNAVAILABLE": 503,
    "REGISTRATION_REDIRECT_INVALID": 400,
    "PAYLOAD_INVALID": 400,
}

ERROR_INT: dict[str, int] = {
    "HOSPITAL_NOT_FOUND": 40481,
    "HOSPITAL_INACTIVE": 40981,
    "HOSPITAL_CODE_CONFLICT": 40982,
    "HOSPITAL_VERSION_CONFLICT": 40983,
    "HOSPITAL_ACTIVATE_INVALID": 40984,
    "DEPARTMENT_NOT_FOUND": 40482,
    "DEPARTMENT_PARENT_INVALID": 40081,
    "STAFF_NOT_FOUND": 40483,
    "STAFF_ALREADY_EXISTS": 40985,
    "STAFF_LAST_ADMIN": 40993,
    "STAFF_ROLE_LOCKED": 40994,
    "DOCTOR_PROFILE_NOT_ACTIVE": 40381,
    "DOCTOR_ROLE_REQUIRED": 40082,
    "MEMBER_ACCESS_DENIED": 40382,
    "HOSPITAL_MEMBERSHIP_REQUIRED": 40383,
    "AGENT_NOT_FOUND": 40484,
    "AGENT_NOT_PUBLISHED": 40986,
    "AGENT_VERSION_CONFLICT": 40987,
    "AGENT_REVIEW_INVALID": 40988,
    "KNOWLEDGE_BASE_FORBIDDEN": 40384,
    "AGENT_DOCTOR_INVALID": 40086,
    "AGENT_DEPARTMENT_INVALID": 40087,
    "AGENT_BASE_MODEL_UNAVAILABLE": 40995,
    "HOSPITAL_KNOWLEDGE_NOT_FOUND": 40486,
    "HOSPITAL_KNOWLEDGE_VERSION_CONFLICT": 40996,
    "HOSPITAL_KNOWLEDGE_EMBEDDING_UNAVAILABLE": 40997,
    "HOSPITAL_KNOWLEDGE_DOCUMENT_NOT_FOUND": 40487,
    "HOSPITAL_KNOWLEDGE_CURSOR_INVALID": 40998,
    "HOSPITAL_KNOWLEDGE_SYNC_UNAVAILABLE": 50382,
    "CONVERSATION_NOT_FOUND": 40485,
    "CONVERSATION_NOT_ASSIGNED": 40385,
    "CONVERSATION_ENDED": 40989,
    "CONVERSATION_VERSION_CONFLICT": 40990,
    "CONVERSATION_REBIND_FORBIDDEN": 40991,
    "PATIENT_CONSENT_REQUIRED": 40386,
    "IDEMPOTENCY_CONFLICT": 40992,
    "IDEMPOTENCY_KEY_REQUIRED": 40083,
    "REGISTRATION_INTEGRATION_UNAVAILABLE": 50381,
    "REGISTRATION_REDIRECT_INVALID": 40084,
    "PAYLOAD_INVALID": 40085,
}


class HospitalCareError(APIError):
    def __init__(self, error_code: str, *, details: dict[str, Any] | None = None, status_code: int | None = None):
        payload = {"error_code": error_code, **(details or {})}
        super().__init__(
            error_code,
            code=ERROR_INT.get(error_code, -1),
            status_code=status_code or ERROR_HTTP.get(error_code, 400),
            details=payload,
        )
        self.error_code = error_code
