_DEFAULT_CHAT = {
    "endpoint": "https://api.sparkclient.local/v1/chat/completions",
    "model": "spark-chat-default",
    "temperature": 0.2,
    "max_tokens": 4096,
}
_DEFAULT_EMBED = {
    "endpoint": "https://api.sparkclient.local/v1/embeddings",
    "model": "spark-embedding-default",
    "temperature": 0.0,
    "max_tokens": 2048,
}

DEFAULT_SCENARIOS = {
    "chat": dict(_DEFAULT_CHAT),
    "optimization_text": {
        "endpoint": "https://api.sparkclient.local/v1/chat/completions",
        "model": "spark-chat-default",
        "temperature": 0.0,
        "max_tokens": 4096,
    },
    "optimization_visual": dict(_DEFAULT_CHAT),
    "context_folding": dict(_DEFAULT_CHAT),
    "router": dict(_DEFAULT_CHAT),
    "model_config": dict(_DEFAULT_EMBED),
    "report_interpretation": dict(_DEFAULT_CHAT),
}

DEFAULT_API_KEYS = [
    {
        "name": "Spark Default",
        "company": "SPARK",
        "key": "",
        "request_url": "https://api.sparkclient.local/v1/chat/completions",
        "is_hidden": False,
        "help": "Spark first-party endpoint",
        "source": "system",
    },
    {
        "name": "Spark Embedding",
        "company": "SPARK",
        "key": "",
        "request_url": "https://api.sparkclient.local/v1/embeddings",
        "is_hidden": False,
        "help": "Spark first-party embedding endpoint",
        "source": "system",
    },
    {
        "name": "OpenAI",
        "company": "OPENAI",
        "key": "",
        "request_url": "https://api.openai.com/v1/chat/completions",
        "is_hidden": True,
        "help": "OpenAI compatible endpoint",
        "source": "system",
    },
]

DEFAULT_SEARCH_KEYS = [
    {
        "name": "Spark Search",
        "company": "SPARK",
        "key": "",
        "request_url": "https://api.sparkclient.local/v1/search",
        "is_using": True,
        "search_class": "web",
        "help": "Default web search connector",
        "source": "system",
    },
    {
        "name": "Tavily Search",
        "company": "TAVILY",
        "key": "",
        "request_url": "https://api.tavily.com/search",
        "is_using": False,
        "search_class": "web",
        "help": "RAG retrieval provider",
        "source": "system",
    },
]

DEFAULT_TOOL_KEYS = [
    {
        "name": "Spark Tools",
        "company": "SPARK",
        "key": "",
        "request_url": "https://api.sparkclient.local/v1/tools",
        "is_using": True,
        "tool_class": "native",
        "help": "Spark default tools",
        "source": "system",
    },
    {
        "name": "Mapbox",
        "company": "MAPBOX",
        "key": "",
        "request_url": "https://api.mapbox.com",
        "is_using": False,
        "tool_class": "map",
        "help": "Map geocoding / route tool",
        "source": "system",
    },
]

DEFAULT_MODELS = [
    {
        "name": "spark-chat-default",
        "display_name": "Spark Chat Default",
        "position": 0,
        "company": "SPARK",
        "is_hidden": False,
        "supports_search": True,
        "supports_multimodal": True,
        "supports_reasoning": True,
        "supports_tool_use": True,
        "supports_voice_gen": False,
        "supports_image_gen": False,
        "price_tier": 0,
        "supports_text": True,
        "reasoning_controllable": False,
        "source": "system",
    },
    {
        "name": "spark-embedding-default",
        "display_name": "Spark Embedding Default",
        "position": 10,
        "company": "SPARK",
        "is_hidden": False,
        "supports_search": False,
        "supports_multimodal": False,
        "supports_reasoning": False,
        "supports_tool_use": False,
        "supports_voice_gen": False,
        "supports_image_gen": False,
        "price_tier": 0,
        "supports_text": True,
        "reasoning_controllable": False,
        "source": "system",
    },
    {
        "name": "spark-tts-default",
        "display_name": "Spark TTS Default",
        "position": 20,
        "company": "SPARK",
        "is_hidden": False,
        "supports_search": False,
        "supports_multimodal": False,
        "supports_reasoning": False,
        "supports_tool_use": False,
        "supports_voice_gen": True,
        "supports_image_gen": False,
        "price_tier": 0,
        "supports_text": True,
        "reasoning_controllable": False,
        "source": "system",
    },
]

DEFAULT_USER_INFO = {
    "choose_embedding_model": "spark-embedding-default",
    "optimization_text_model": "spark-chat-default",
    "optimization_visual_model": "spark-chat-default",
    "text_to_speech_model": "spark-tts-default",
    "use_knowledge": True,
    "knowledge_count": 5,
    "knowledge_similarity": 0.75,
    "use_search": True,
    "bilingual_search": False,
    "search_count": 3,
    "use_map": False,
    "use_calendar": False,
    "use_weather": False,
    "use_canvas": False,
    "use_code": False,
}
