"""
Django settings for SparkService project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

from dotenv import load_dotenv

# Use PyMySQL as the MySQLdb driver for Django's mysql backend.
# This avoids requiring the mysqlclient C extension in local/dev.
try:
    import pymysql  # type: ignore

    pymysql.install_as_MySQLdb()
    # Django 6.0 在 mysql 后端里会检查 MySQLdb 版本号（mysqlclient 版本校验）。
    # PyMySQL 的兼容层里 __version__ 可能不足以通过校验，因此我们做一个最小化注入。
    import MySQLdb  # type: ignore

    MySQLdb.__version__ = "2.2.99"
    MySQLdb.version_info = (2, 2, 99)
except Exception:
    # If mysqlclient is installed instead, Django will work as usual.
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from `.env` if present.
# Secrets like `DB_PASSWORD` must never be committed.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-sln8o!z!x*=w&6boe+@cdfv_@))sx(02^=+qp6q^-#88l6_w9*",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() in ("1", "true", "yes", "y")

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",") if h.strip()]

# Apple Sign-In security hardening:
# optionally restrict accepted Apple audience(bundle_id) to this allowlist.
APPLE_ALLOWED_BUNDLE_IDS = [
    item.strip()
    for item in os.getenv("APPLE_ALLOWED_BUNDLE_IDS", "").split(",")
    if item.strip()
]

# Aliyun OSS / STS（`file_manager` 签发客户端临时凭证）
# 来源：项目根目录 `.env`（由上方 `load_dotenv` 注入 `os.environ`），部署环境也可用容器/系统环境变量覆盖。
ALIYUN_ACCESS_KEY_ID = (os.getenv("ALIYUN_ACCESS_KEY_ID") or "").strip()
ALIYUN_ACCESS_KEY_SECRET = (os.getenv("ALIYUN_ACCESS_KEY_SECRET") or "").strip()
ALIYUN_STS_ROLE_ARN = (os.getenv("ALIYUN_STS_ROLE_ARN") or "").strip()
ALIYUN_OSS_BUCKET = (os.getenv("ALIYUN_OSS_BUCKET") or "").strip() or "spark-oss"
ALIYUN_OSS_REGION = (os.getenv("ALIYUN_OSS_REGION") or "").strip() or "cn-hangzhou"
ALIYUN_OSS_ENDPOINT = (os.getenv("ALIYUN_OSS_ENDPOINT") or "").strip()
ALIYUN_STS_DURATION_SECONDS = int(os.getenv("ALIYUN_STS_DURATION_SECONDS", "3600"))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # Must come before staticfiles so `runserver` uses ASGI (HTTP + WebSocket).
    'daphne',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'django_celery_beat',
    'django_celery_results',
    'accounts',
    'ai_config',
    'chat_sync',
    'medical',
    'file_manager',
    'backoffice',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.request_id_middleware.RequestIdMiddleware',
    'common.middleware.request_logging_middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'SparkService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SparkService.wsgi.application'
ASGI_APPLICATION = 'SparkService.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.mysql")
db_options = {}
if "mysql" in DB_ENGINE:
    db_options = {"charset": "utf8mb4"}

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': os.getenv("DB_NAME", "sparkservice"),
        'USER': os.getenv("DB_USER", "root"),
        'PASSWORD': os.getenv("DB_PASSWORD", ""),
        'HOST': os.getenv("DB_HOST", "127.0.0.1"),
        'PORT': os.getenv("DB_PORT", "3306"),
        'OPTIONS': db_options,
        'CONN_MAX_AGE': int(os.getenv("DB_CONN_MAX_AGE", "60")),
    }
}

# Default PK type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# -------------------------
# DRF + JWT (SimpleJWT)
# -------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
    "EXCEPTION_HANDLER": "common.exception_handlers.api_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "30"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Keep signing key consistent across workers.
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY", SECRET_KEY),
}

# -------------------------
# AI Trial
# -------------------------
AI_TRIAL_DURATION_DAYS = int(os.getenv("AI_TRIAL_DURATION_DAYS", "15"))
AI_TRIAL_AUTO_APPROVE_APPLICATIONS = os.getenv("AI_TRIAL_AUTO_APPROVE_APPLICATIONS", "true").lower() in ("1", "true", "yes", "y")

# -------------------------
# CORS
# -------------------------
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "false").lower() in ("1", "true", "yes", "y")
CORS_ALLOWED_ORIGINS = [
    item.strip()
    for item in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173,"
        "http://localhost:5174,http://127.0.0.1:5174,"
        "http://localhost:5175,http://127.0.0.1:5175,"
        "http://localhost:6018,http://127.0.0.1:6018",
    ).split(",")
    if item.strip()
]

# -------------------------
# Celery
# -------------------------
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "300"))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "240"))

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
DJANGO_CELERY_BEAT_TZ_AWARE = True

# -------------------------
# Channels / WebSocket
# -------------------------
_channel_backend = os.getenv("CHANNEL_LAYER_BACKEND", "channels_redis.core.RedisChannelLayer")
if _channel_backend == "channels.layers.InMemoryChannelLayer":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": _channel_backend,
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": _channel_backend,
            "CONFIG": {
                "hosts": [os.getenv("CHANNEL_REDIS_URL", CELERY_BROKER_URL)],
            },
        }
    }

# -------------------------
# Security headers (only enforce in prod)
# -------------------------
if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "true").lower() in ("1", "true", "yes", "y")

# -------------------------
# Logging
# -------------------------
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
LOG_FORMAT = os.getenv("LOG_FORMAT", "console")
if LOG_FORMAT not in {"console", "json"}:
    LOG_FORMAT = "console"
LOG_BACKUP_COUNT = int(os.getenv("LOG_BACKUP_COUNT", "14"))
LOG_API_IO_TO_ACCESS = os.getenv("LOG_API_IO_TO_ACCESS", "false").lower() in ("1", "true", "yes", "y")
LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)
API_IO_HANDLERS = ["console", "app_file"]
if LOG_API_IO_TO_ACCESS:
    API_IO_HANDLERS.append("access_file")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "common.logging.RequestIdFilter",
        }
    },
    "formatters": {
        "console": {
            "format": "%(levelname)s %(asctime)s %(name)s [request_id=%(request_id)s] %(message)s",
        },
        "json": {
            "()": "common.logging.JsonFormatter",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": LOG_FORMAT,
            "level": LOG_LEVEL,
            "filters": ["request_id"],
        },
        "app_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "app.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": LOG_FORMAT,
            "level": LOG_LEVEL,
            "filters": ["request_id"],
        },
        "access_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "access.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": LOG_FORMAT,
            "level": LOG_LEVEL,
            "filters": ["request_id"],
        },
        "celery_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "celery.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": LOG_FORMAT,
            "level": LOG_LEVEL,
            "filters": ["request_id"],
        },
        "chat_sync_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "chat_sync.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": LOG_FORMAT,
            "level": LOG_LEVEL,
            "filters": ["request_id"],
        },
        "medical_flow_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "medical_flow.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": LOG_FORMAT,
            "level": LOG_LEVEL,
            "filters": ["request_id"],
        },
        "medical_api_io_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "medical_api_io.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": LOG_FORMAT,
            "level": LOG_LEVEL,
            "filters": ["request_id"],
        },
    },
    "loggers": {
        "django": {"handlers": ["console", "app_file"], "level": LOG_LEVEL, "propagate": True},
        "accounts": {"handlers": ["console", "app_file"], "level": LOG_LEVEL, "propagate": True},
        "accounts.request": {"handlers": ["console", "access_file"], "level": LOG_LEVEL, "propagate": False},
        "accounts.api_io": {"handlers": API_IO_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "accounts.flow": {"handlers": ["console", "access_file", "app_file"], "level": LOG_LEVEL, "propagate": False},
        "celery": {"handlers": ["console", "celery_file"], "level": LOG_LEVEL, "propagate": True},
        "chat_sync": {"handlers": ["console", "chat_sync_file", "app_file"], "level": LOG_LEVEL, "propagate": False},
        "medical.flow": {"handlers": ["console", "medical_flow_file", "app_file"], "level": LOG_LEVEL, "propagate": False},
        "medical.api_io": {
            "handlers": ["console", "medical_api_io_file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
