# Generated by Django 6.0.3 on 2026-04-03 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('chief_complaint', models.CharField(blank=True, default='', max_length=255)),
                ('diagnosis', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('visit_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('relationship', models.CharField(default='self', max_length=64)),
                ('avatar', models.URLField(blank=True, default='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('report_type', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('hospital', models.CharField(blank=True, default='', max_length=255)),
                ('doctor', models.CharField(blank=True, default='', max_length=128)),
                ('content', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('medical_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='medical.medicalcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='medical.member')),
            ],
            options={
                'ordering': ['-date', '-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_cases', to='medical.member'),
        ),
        migrations.CreateModel(
            name='ExaminationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('subcategory', models.CharField(blank=True, default='', max_length=64)),
                ('report_name', models.CharField(max_length=255)),
                ('check_type', models.CharField(blank=True, default='', max_length=128)),
                ('conclusion', models.TextField(blank=True, default='')),
                ('doctor_advice', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('medical_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_reports', to='medical.medicalcase')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_reports', to='medical.member')),
            ],
            options={
                'ordering': ['-date', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('drug_name', models.CharField(max_length=128)),
                ('dosage', models.CharField(blank=True, default='', max_length=128)),
                ('frequency', models.CharField(blank=True, default='', max_length=128)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='active', max_length=16)),
                ('medical_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='medical.medicalcase')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'client_uid'), name='uniq_member_user_client_uid'),
        ),
        migrations.AddConstraint(
            model_name='medicalreport',
            constraint=models.UniqueConstraint(fields=('user', 'client_uid'), name='uniq_medical_report_user_client_uid'),
        ),
        migrations.AddConstraint(
            model_name='medicalcase',
            constraint=models.UniqueConstraint(fields=('user', 'client_uid'), name='uniq_case_user_client_uid'),
        ),
        migrations.AddConstraint(
            model_name='examinationreport',
            constraint=models.UniqueConstraint(fields=('user', 'client_uid'), name='uniq_exam_user_client_uid'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('user', 'client_uid'), name='uniq_prescription_user_client_uid'),
        ),
    ]
