# Generated by Django 5.2.12 on 2026-06-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medicationreminderlocalauthorization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicationreminderlocalauthorization',
            new_name='medical_med_user_id_9b40c2_idx',
            old_name='medical_medi_user_id_8d2989_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationreminderlocalauthorization',
            new_name='medical_med_member__53be9b_idx',
            old_name='medical_medi_member__42f678_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationreminderlocalauthorization',
            new_name='medical_med_medicat_1b7ef2_idx',
            old_name='medical_medi_medicat_ec3767_idx',
        ),
    ]
