# Generated by Django 6.0.3 on 2026-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_healthmetricrecord_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examinationreport',
            name='uniq_exam_user_client_uid',
        ),
        migrations.RemoveConstraint(
            model_name='healthmetricrecord',
            name='uniq_health_metric_user_client_uid',
        ),
        migrations.RemoveConstraint(
            model_name='medicalcase',
            name='uniq_case_user_client_uid',
        ),
        migrations.RemoveConstraint(
            model_name='medicalreport',
            name='uniq_medical_report_user_client_uid',
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='uniq_member_user_client_uid',
        ),
        migrations.RemoveConstraint(
            model_name='prescription',
            name='uniq_prescription_user_client_uid',
        ),
        migrations.AddField(
            model_name='member',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='member',
            name='chronic_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.RemoveField(
            model_name='examinationreport',
            name='client_uid',
        ),
        migrations.RemoveField(
            model_name='healthmetricrecord',
            name='client_uid',
        ),
        migrations.RemoveField(
            model_name='medicalcase',
            name='client_uid',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='client_uid',
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='member',
            name='client_uid',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='client_uid',
        ),
    ]
