# Generated by Django 6.0.3 on 2026-04-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_remove_examinationreport_uniq_exam_user_client_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthExamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('report_no', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('exam_date', models.DateField(blank=True, db_index=True, null=True)),
                ('exam_type', models.PositiveSmallIntegerField(choices=[(1, 'routine'), (2, 'onboarding'), (3, 'special'), (4, 'senior')], default=1)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'manual'), (2, 'ocr'), (3, 'imported')], default=1)),
                ('raw_ocr', models.JSONField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'completed'), (3, 'verified')], db_index=True, default=1)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'health_exam_report',
                'ordering': ['-exam_date', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedExamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('health_exam_report', 'Health Exam Report'), ('examination_report', 'Examination Report')], db_index=True, max_length=32)),
                ('business_id', models.PositiveBigIntegerField(db_index=True)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('sub_category', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(blank=True, default='', max_length=64)),
                ('result_value', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('reference_range', models.CharField(blank=True, default='', max_length=255)),
                ('flag', models.CharField(blank=True, default='', max_length=16)),
                ('result_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('modality', models.CharField(blank=True, default='', max_length=32)),
                ('body_part', models.CharField(blank=True, default='', max_length=128)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'med_exam_detail',
                'ordering': ['sort_order', '-updated_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='examinationreport',
            options={'ordering': ['-reported_at', '-updated_at', '-id']},
        ),
        migrations.RenameField(
            model_name='examinationreport',
            old_name='check_type',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='examinationreport',
            old_name='report_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='examinationreport',
            old_name='medical_case',
            new_name='medical_record',
        ),
        migrations.RemoveField(
            model_name='examinationreport',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='examinationreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examinationreport',
            name='doctor_advice',
        ),
        migrations.RemoveField(
            model_name='examinationreport',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='doctor_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='impression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='organization_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='performed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='raw_ocr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='reported_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'manual'), (2, 'ocr')], default=1),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'completed'), (3, 'revised'), (4, 'discarded')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='examinationreport',
            name='category',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='examinationreport',
            index=models.Index(fields=['member', 'status', 'is_deleted'], name='examination_member__3b1428_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationreport',
            index=models.Index(fields=['member', 'performed_at', 'is_deleted'], name='examination_member__d11bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationreport',
            index=models.Index(fields=['member', 'reported_at', 'is_deleted'], name='examination_member__2ff8f6_idx'),
        ),
        migrations.AlterModelTable(
            name='examinationreport',
            table='examination_report',
        ),
        migrations.AddField(
            model_name='healthexamreport',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_exam_reports', to='medical.member'),
        ),
        migrations.AddField(
            model_name='healthexamreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medexamdetail',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_exam_details', to='medical.member'),
        ),
        migrations.AddIndex(
            model_name='healthexamreport',
            index=models.Index(fields=['member', 'exam_date', 'is_deleted'], name='health_exam_member__9aeda2_idx'),
        ),
        migrations.AddIndex(
            model_name='healthexamreport',
            index=models.Index(fields=['member', 'status', 'is_deleted'], name='health_exam_member__aa6cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='medexamdetail',
            index=models.Index(fields=['business_type', 'business_id', 'is_deleted'], name='med_exam_de_busines_f213f3_idx'),
        ),
        migrations.AddIndex(
            model_name='medexamdetail',
            index=models.Index(fields=['member', 'is_deleted'], name='med_exam_de_member__d9e802_idx'),
        ),
        migrations.AddIndex(
            model_name='medexamdetail',
            index=models.Index(fields=['category', 'sub_category', 'is_deleted'], name='med_exam_de_categor_740399_idx'),
        ),
        migrations.AddIndex(
            model_name='medexamdetail',
            index=models.Index(fields=['business_type', 'business_id', 'sort_order'], name='med_exam_de_busines_721c40_idx'),
        ),
    ]
