# Generated by Django 5.2.12 on 2026-06-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_membermedicalprofile_membermodulesetting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membermedicalprofile',
            new_name='medical_mem_user_id_2d574a_idx',
            old_name='medical_me_user_memb_1f2e34_idx',
        ),
        migrations.RenameIndex(
            model_name='membermodulesetting',
            new_name='medical_mem_user_id_22640b_idx',
            old_name='medical_mem_user_memb_7a3c1b_idx',
        ),
        migrations.RenameIndex(
            model_name='membermodulesetting',
            new_name='medical_mem_member__5e220e_idx',
            old_name='medical_mem_member_0bf3dd_idx',
        ),
    ]
