# Generated by Django 6.0.3 on 2026-04-06 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_healthexamreport_medexamdetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='initial', max_length=20)),
                ('method', models.CharField(blank=True, default='', max_length=32)),
                ('outcome', models.TextField(blank=True, default='')),
                ('next_action', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-completed_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('generic_name', models.CharField(blank=True, db_comment='通用名', default='', max_length=255)),
                ('brand_name', models.CharField(blank=True, db_comment='品牌名', default='', max_length=255)),
                ('drug_name', models.CharField(db_comment='药品显示名', max_length=255)),
                ('dosage_form', models.CharField(blank=True, db_comment='剂型', default='', max_length=64)),
                ('strength', models.CharField(blank=True, db_comment='规格', default='', max_length=128)),
                ('route', models.CharField(blank=True, db_comment='给药途径', default='', max_length=64)),
                ('dose_per_time', models.CharField(blank=True, db_comment='单次剂量文本', default='', max_length=64)),
                ('dose_value', models.DecimalField(blank=True, db_comment='单次剂量数值', decimal_places=3, max_digits=10, null=True)),
                ('dose_unit', models.CharField(blank=True, db_comment='单次剂量单位', default='', max_length=32)),
                ('frequency_code', models.CharField(blank=True, db_comment='频次编码', default='', max_length=64)),
                ('period', models.CharField(blank=True, db_comment='频次周期', default='', max_length=16)),
                ('times_per_period', models.PositiveSmallIntegerField(blank=True, db_comment='每周期次数', null=True)),
                ('frequency_text', models.CharField(blank=True, db_comment='频次展示文案', default='', max_length=255)),
                ('duration_days', models.PositiveIntegerField(blank=True, db_comment='疗程天数', null=True)),
                ('instructions', models.TextField(blank=True, db_comment='用药说明', default='')),
                ('reminder_enabled', models.BooleanField(db_comment='是否启用提醒', default=True)),
                ('reminder_times', models.JSONField(blank=True, db_comment='提醒时间点列表', default=list)),
                ('sort_order', models.PositiveIntegerField(db_comment='批次内排序', default=0)),
                ('extra', models.JSONField(blank=True, db_comment='扩展字段', default=dict)),
            ],
            options={
                'verbose_name': '用药记录',
                'verbose_name_plural': '用药记录',
                'db_table': 'medication',
                'db_table_comment': '用药记录：处方批次下的药品行与提醒规则。',
                'ordering': ['sort_order', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicationTakenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('scheduled_at', models.DateTimeField(db_comment='计划服药时间', db_index=True)),
                ('taken_at', models.DateTimeField(blank=True, db_comment='实际服药时间', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('taken', 'Taken'), ('skipped', 'Skipped'), ('snoozed', 'Snoozed')], db_index=True, default='scheduled', max_length=20)),
                ('dose_sequence', models.PositiveSmallIntegerField(db_comment='当日第几次', default=1)),
                ('actual_dose', models.CharField(blank=True, db_comment='实际服用剂量文本', default='', max_length=64)),
                ('timezone', models.CharField(blank=True, db_comment='打卡时区', db_index=True, default='UTC', max_length=64)),
                ('notes', models.TextField(blank=True, db_comment='备注', default='')),
                ('extra', models.JSONField(blank=True, db_comment='扩展字段', default=dict)),
            ],
            options={
                'verbose_name': '服药打卡',
                'verbose_name_plural': '服药打卡',
                'db_table': 'medication_taken_record',
                'db_table_comment': '服药打卡记录：单次应服/已服/漏服事实。',
                'ordering': ['-scheduled_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModelChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('operator', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '模型变更日志',
                'verbose_name_plural': '模型变更日志',
                'db_table': 'model_change_log',
                'db_table_comment': '通用模型审计日志：追踪医疗域关键状态与字段变更。',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('prescriber_name', models.CharField(blank=True, db_comment='开方医生姓名', default='', help_text='开方医生', max_length=128)),
                ('institution_name', models.CharField(blank=True, db_comment='机构名称', default='', help_text='开方机构名称', max_length=255)),
                ('prescribed_at', models.DateTimeField(blank=True, db_comment='开方或方案开始时间', db_index=True, help_text='开方/方案起始时间', null=True)),
                ('diagnosis', models.TextField(blank=True, db_comment='诊断摘要', default='', help_text='诊断或适应症摘要')),
                ('batch_no', models.CharField(blank=True, db_comment='业务唯一批次号', default='', help_text='业务批次号/处方号', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('audited', 'Audited'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('auditor_name', models.CharField(blank=True, db_comment='审核人姓名', default='', help_text='审核人姓名', max_length=128)),
                ('audited_at', models.DateTimeField(blank=True, db_comment='审核时间', help_text='审核时间', null=True)),
                ('extra', models.JSONField(blank=True, db_comment='扩展字段', default=dict)),
            ],
            options={
                'verbose_name': '处方批次',
                'verbose_name_plural': '处方批次',
                'db_table': 'prescription_batch',
                'db_table_comment': '处方批次：一次处方或用药方案的批次头信息。',
                'ordering': ['-prescribed_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('procedure_name', models.CharField(max_length=255)),
                ('procedure_code', models.CharField(blank=True, default='', max_length=64)),
                ('site', models.CharField(blank=True, default='', max_length=128)),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('surgeon', models.CharField(blank=True, default='', max_length=128)),
                ('anesthesia_type', models.CharField(blank=True, default='', max_length=128)),
                ('incision_level', models.CharField(blank=True, default='', max_length=8)),
                ('asa_class', models.CharField(blank=True, default='', max_length=8)),
                ('source_system_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-performed_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, default='', max_length=16)),
                ('body_part', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('visit_type', models.CharField(default='custom', max_length=32)),
                ('visited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=128)),
                ('doctor_name', models.CharField(blank=True, default='', max_length=128)),
                ('visit_no', models.CharField(blank=True, default='', max_length=64)),
                ('source_system_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-visited_at', '-updated_at', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medical_case',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='member',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='medicalcase',
            options={'ordering': ['-created_at', '-updated_at', '-id']},
        ),
        migrations.RenameField(
            model_name='medicalcase',
            old_name='notes',
            new_name='diagnosis_summary',
        ),
        migrations.RemoveField(
            model_name='medicalcase',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='medicalcase',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalcase',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='medicalcase',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='age_at_visit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='hospital_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='record_type',
            field=models.CharField(db_index=True, default='custom', max_length=32),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'submitted'), (3, 'archived')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='medicalcase',
            index=models.Index(fields=['member', 'is_deleted', 'created_at'], name='medical_med_member__6c6d17_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcase',
            index=models.Index(fields=['member', 'record_type', 'is_deleted', 'created_at'], name='medical_med_member__d91f47_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcase',
            index=models.Index(fields=['member', 'status', 'is_deleted', 'created_at'], name='medical_med_member__c9ebd5_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcase',
            index=models.Index(fields=['hospital_name'], name='medical_med_hospita_e18bb3_idx'),
        ),
        migrations.AddField(
            model_name='followup',
            name='medical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='medical.medicalcase'),
        ),
        migrations.AddField(
            model_name='followup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='medical.member'),
        ),
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='member',
            field=models.ForeignKey(db_comment='所属就诊人 ID', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medical.member'),
        ),
        migrations.AddField(
            model_name='medication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationtakenrecord',
            name='medication',
            field=models.ForeignKey(db_comment='对应药品行 ID', on_delete=django.db.models.deletion.CASCADE, related_name='taken_records', to='medical.medication'),
        ),
        migrations.AddField(
            model_name='medicationtakenrecord',
            name='member',
            field=models.ForeignKey(db_comment='所属就诊人 ID', on_delete=django.db.models.deletion.CASCADE, related_name='medication_taken_records', to='medical.member'),
        ),
        migrations.AddField(
            model_name='medicationtakenrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelchangelog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='medical.member'),
        ),
        migrations.AddField(
            model_name='modelchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionbatch',
            name='medical_case',
            field=models.ForeignKey(blank=True, db_comment='可选来源病例 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_batches', to='medical.medicalcase'),
        ),
        migrations.AddField(
            model_name='prescriptionbatch',
            name='member',
            field=models.ForeignKey(db_comment='所属就诊人 ID', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_batches', to='medical.member'),
        ),
        migrations.AddField(
            model_name='prescriptionbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='batch',
            field=models.ForeignKey(db_comment='所属处方批次 ID', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medical.prescriptionbatch'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='medical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='medical.medicalcase'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='medical.member'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='symptom',
            name='medical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='medical.medicalcase'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='medical.member'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='medical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='medical.medicalcase'),
        ),
        migrations.AddField(
            model_name='visit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='medical.member'),
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['medical_case', 'status', 'completed_at'], name='medical_fol_medical_f68578_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['member', 'medical_case', 'is_deleted', 'completed_at'], name='medical_fol_member__ccb125_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationtakenrecord',
            index=models.Index(fields=['medication', 'scheduled_at', 'status'], name='medication__medicat_a8b583_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationtakenrecord',
            index=models.Index(fields=['user', 'member', 'scheduled_at', 'status'], name='medication__user_id_6a62db_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationtakenrecord',
            constraint=models.UniqueConstraint(fields=('medication', 'scheduled_at', 'dose_sequence'), name='uniq_medication_schedule_sequence'),
        ),
        migrations.AddIndex(
            model_name='prescriptionbatch',
            index=models.Index(fields=['user', 'member', 'is_deleted', 'prescribed_at'], name='prescriptio_user_id_705747_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionbatch',
            index=models.Index(fields=['medical_case'], name='prescriptio_medical_9b6fba_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionbatch',
            index=models.Index(fields=['batch_no'], name='prescriptio_batch_n_9c475b_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['batch', 'sort_order'], name='medication_batch_i_f0703b_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['user', 'member', 'is_deleted', 'created_at'], name='medication_user_id_0a66ae_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['medical_case', 'performed_at'], name='medical_sur_medical_5a2c59_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['member', 'medical_case', 'is_deleted', 'performed_at'], name='medical_sur_member__e27c59_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['source_system_id'], name='medical_sur_source__36c244_idx'),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['medical_case', 'created_at'], name='medical_sym_medical_9e232c_idx'),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['member', 'medical_case', 'is_deleted', 'created_at'], name='medical_sym_member__235d50_idx'),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['body_part'], name='medical_sym_body_pa_9e35cf_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['medical_case', 'visited_at'], name='medical_vis_medical_c2ea25_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['member', 'medical_case', 'is_deleted', 'visited_at'], name='medical_vis_member__d1922f_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['source_system_id'], name='medical_vis_source__86a775_idx'),
        ),
    ]
