# Generated by Django 5.2.12 on 2026-05-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_medicationplan_frequency_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationplan',
            name='frequency_text',
            field=models.CharField(db_comment='频次说明文本（展示用，可自动生成或手改）', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationplan',
            name='frequency_type',
            field=models.CharField(choices=[('daily', '每天'), ('every_n_days', '每几天'), ('weekly', '每周指定星期')], db_comment='频次类型：每天/每几天/每周', default='daily', max_length=20),
        ),
    ]
