# Generated by Django 5.2.12 on 2026-06-20 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_rename_medical_me_user_memb_1f2e34_idx_medical_mem_user_id_2d574a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='medexamdetail',
            table_comment='体检与临床检查共用的行级医技结果明细（指标行）。',
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='body_part',
            field=models.CharField(blank=True, db_comment='检查部位，例如甲状腺、肝脏', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='business_id',
            field=models.PositiveBigIntegerField(db_comment='关联报告主表 ID', db_index=True),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='business_type',
            field=models.CharField(choices=[('health_exam_report', 'Health Exam Report'), ('examination_report', 'Examination Report')], db_comment='业务类型：health_exam_report（体检报告）或 examination_report（检查/检验报告）', db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='category',
            field=models.CharField(blank=True, db_comment='指标大类，例如血常规、肝功能、血脂', db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='diagnosis',
            field=models.TextField(blank=True, db_comment='诊断或结论描述（影像/功能检查常用）', null=True),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='extra',
            field=models.JSONField(blank=True, db_comment='扩展字段（OCR 原始片段、置信度等）', null=True),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='flag',
            field=models.CharField(blank=True, db_comment='异常标记，例如 H（偏高）、L（偏低）、↑、↓', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='item_code',
            field=models.CharField(blank=True, db_comment='项目编码（LIS/HIS 标准码或机构内部码）', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='item_name',
            field=models.CharField(db_comment='检查/检验项目名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='member',
            field=models.ForeignKey(db_comment='所属家庭成员', on_delete=django.db.models.deletion.CASCADE, related_name='med_exam_details', to='medical.member'),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='modality',
            field=models.CharField(blank=True, db_comment='检查方式/模态，例如 CT、MRI、超声、实验室检验', default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='reference_range',
            field=models.CharField(blank=True, db_comment='参考范围，例如 3.9-6.1', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='result_at',
            field=models.DateTimeField(blank=True, db_comment='结果产生时间', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='result_value',
            field=models.CharField(blank=True, db_comment='结果值（数值或文字描述）', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='同报告内明细排序序号', default=0),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='sub_category',
            field=models.CharField(blank=True, db_comment='指标子类，例如白细胞、总胆红素', db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='unit',
            field=models.CharField(blank=True, db_comment='结果单位，例如 mmol/L、U/L', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
    ]
