# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0007_alter_medicationplan_frequency_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicinebox",
            name="dose_unit",
            field=models.CharField(
                blank=True,
                db_comment="剂量数值单位",
                default="",
                max_length=32,
            ),
        ),
    ]
