# Generated by Django 5.2.12 on 2026-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_membermedicalkeyindicatorrecord_key_indicator'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membermedicalkeyindicatorrecord',
            new_name='medical_mem_user_id_403dae_idx',
            old_name='med_mem_usr_mbr_rec_idx',
        ),
        migrations.RenameIndex(
            model_name='membermedicalkeyindicatorrecord',
            new_name='medical_mem_member__231a27_idx',
            old_name='med_mem_mbr_src_rec_idx',
        ),
        migrations.RenameIndex(
            model_name='membermedicalkeyindicatorrecord',
            new_name='medical_mem_member__778193_idx',
            old_name='med_mem_mbr_scn_rec_idx',
        ),
        migrations.RenameIndex(
            model_name='membermedicalkeyindicatorrecord',
            new_name='medical_mem_qa_sess_e8dfdc_idx',
            old_name='med_mem_qa_session_idx',
        ),
        migrations.AlterField(
            model_name='medexamdetail',
            name='business_type',
            field=models.CharField(choices=[('health_exam_report', 'Health Exam Report'), ('examination_report', 'Examination Report'), ('key_indicator', 'Key Indicator')], db_comment='业务类型：health_exam_report（体检报告）或 examination_report（检查/检验报告）', db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='membermedicalkeyindicatorrecord',
            name='scenario',
            field=models.CharField(choices=[('medical_guide', 'medical_guide'), ('follow_up', 'follow_up'), ('risk_assessment', 'risk_assessment'), ('exam_plan', 'exam_plan')], db_comment='业务场景：医疗引导、随访、风险评估、体检计划', db_index=True, default='medical_guide', max_length=32),
        ),
        migrations.AlterField(
            model_name='membermedicalkeyindicatorrecord',
            name='source',
            field=models.CharField(choices=[('guide_qa', 'guide_qa'), ('manual', 'manual'), ('ai_follow_up', 'ai_follow_up'), ('report_extraction', 'report_extraction'), ('device', 'device')], db_comment='记录来源：问答引导、手动录入、AI随访、报告抽取、设备', db_index=True, default='manual', max_length=32),
        ),
    ]
