# Generated by Django 5.2.12 on 2026-05-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_medicationplan_duration_days_and_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='examinationreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='examinationreport',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='examinationreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='healthexamreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='healthexamreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='healthexamreport',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='healthexamreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='healthmetricrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='healthmetricrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='healthmetricrecord',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='healthmetricrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicationplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicationplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='medicationplan',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='medicationplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicinebox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='medicinebox',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='medicinebox',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='medicinebox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='软删除时间', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否删除', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True),
        ),
    ]
