# Generated by Django 5.2.12 on 2026-04-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_healthexamreport_institution_name_blank'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examinationreport',
            new_name='medical_exa_member__0094aa_idx',
            old_name='examination_member__3b1428_idx',
        ),
        migrations.RenameIndex(
            model_name='examinationreport',
            new_name='medical_exa_member__148bf0_idx',
            old_name='examination_member__d11bb9_idx',
        ),
        migrations.RenameIndex(
            model_name='examinationreport',
            new_name='medical_exa_member__a81112_idx',
            old_name='examination_member__2ff8f6_idx',
        ),
        migrations.RenameIndex(
            model_name='healthexamreport',
            new_name='medical_hea_member__45dd34_idx',
            old_name='health_exam_member__9aeda2_idx',
        ),
        migrations.RenameIndex(
            model_name='healthexamreport',
            new_name='medical_hea_member__af375f_idx',
            old_name='health_exam_member__aa6cf6_idx',
        ),
        migrations.RenameIndex(
            model_name='medexamdetail',
            new_name='medical_med_busines_74e609_idx',
            old_name='med_exam_de_busines_f213f3_idx',
        ),
        migrations.RenameIndex(
            model_name='medexamdetail',
            new_name='medical_med_member__a8555b_idx',
            old_name='med_exam_de_member__d9e802_idx',
        ),
        migrations.RenameIndex(
            model_name='medexamdetail',
            new_name='medical_med_categor_e84f1d_idx',
            old_name='med_exam_de_categor_740399_idx',
        ),
        migrations.RenameIndex(
            model_name='medexamdetail',
            new_name='medical_med_busines_381668_idx',
            old_name='med_exam_de_busines_721c40_idx',
        ),
        migrations.RenameIndex(
            model_name='medication',
            new_name='medical_med_batch_i_b2673a_idx',
            old_name='medication_batch_i_f0703b_idx',
        ),
        migrations.RenameIndex(
            model_name='medication',
            new_name='medical_med_user_id_94c86c_idx',
            old_name='medication_user_id_0a66ae_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationtakenrecord',
            new_name='medical_med_medicat_405d3c_idx',
            old_name='medication__medicat_a8b583_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationtakenrecord',
            new_name='medical_med_user_id_ce705b_idx',
            old_name='medication__user_id_6a62db_idx',
        ),
        migrations.RenameIndex(
            model_name='prescriptionbatch',
            new_name='medical_pre_user_id_7914aa_idx',
            old_name='prescriptio_user_id_705747_idx',
        ),
        migrations.RenameIndex(
            model_name='prescriptionbatch',
            new_name='medical_pre_medical_2e32c5_idx',
            old_name='prescriptio_medical_9b6fba_idx',
        ),
        migrations.RenameIndex(
            model_name='prescriptionbatch',
            new_name='medical_pre_batch_n_1d0ac1_idx',
            old_name='prescriptio_batch_n_9c475b_idx',
        ),
    ]
