# Generated by Django 5.2.12 on 2026-05-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_user_member_binding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usermemberbinding',
            new_name='medical_use_member__7a5065_idx',
            old_name='medical_use_member__b8e0d0_idx',
        ),
        migrations.RenameIndex(
            model_name='usermemberbinding',
            new_name='medical_use_user_id_bc5545_idx',
            old_name='medical_use_user_id_6f0a8b_idx',
        ),
    ]
