# Generated by Django 5.2.12 on 2026-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_rename_examination_member__3b1428_idx_medical_exa_member__0094aa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionbatch',
            name='batch_no',
            field=models.CharField(blank=True, db_comment='业务批次号/处方号（非全局唯一）', default=None, help_text='业务批次号/处方号；不同病例可重复，未填时存库为 NULL', max_length=128, null=True),
        ),
    ]
