# Generated by Django 5.2.12 on 2026-05-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_remove_member_relationship'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membershareinvite',
            new_name='medical_mem_target__29781d_idx',
            old_name='medical_mem_target__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='membershareinvite',
            new_name='medical_mem_member__5abc30_idx',
            old_name='medical_mem_member__d4e5f6_idx',
        ),
    ]
