# Generated by Django 5.2.12 on 2026-05-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_remove_membershareinvite_conditional_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membershareinvite',
            new_name='medical_mem_member__d3f107_idx',
            old_name='medical_mem_invite_dedup_idx',
        ),
    ]
