# Generated by Django 5.2.12 on 2026-06-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_membermedicalexamplan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membermedicalexamplan',
            new_name='medical_mem_member__a4e647_idx',
            old_name='medical_mem_status_del_idx',
        ),
        migrations.RenameIndex(
            model_name='membermedicalexamplan',
            new_name='medical_mem_member__d45b49_idx',
            old_name='medical_mem_source_del_idx',
        ),
        migrations.RenameIndex(
            model_name='membermedicalexamplan',
            new_name='medical_mem_ai_trac_661b77_idx',
            old_name='medical_exam_plan_trace_idx',
        ),
    ]
