# Generated by Django 5.2.12 on 2026-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0017_exam_archive_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationplan',
            name='status',
            field=models.CharField(choices=[('active', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消'), ('as_needed', '按需用药')], db_index=True, default='active', max_length=20),
        ),
    ]
