# Generated by Django 5.2.12 on 2026-07-02 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0018_alter_medicationplan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalShareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('medical_case', 'medical_case')], db_index=True, max_length=64)),
                ('business_id', models.PositiveBigIntegerField(db_index=True)),
                ('share_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_share_records', to='medical.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_share_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_share_record',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'business_type', 'business_id', 'status', 'expires_at'], name='medical_sha_user_id_fd52da_idx'), models.Index(fields=['member', 'business_type', 'business_id'], name='medical_sha_member__b48afd_idx'), models.Index(fields=['expires_at', 'status'], name='medical_sha_expires_98f95c_idx')],
            },
        ),
    ]
