# Generated by Django 5.2.12 on 2026-07-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0020_alter_medexamdetail_result_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalsharerecord',
            name='business_type',
            field=models.CharField(choices=[('medical_case', 'medical_case'), ('health_exam_report', 'health_exam_report'), ('examination_report', 'examination_report'), ('prescription', 'prescription'), ('medication_plan', 'medication_plan'), ('medicine_box', 'medicine_box')], db_index=True, max_length=64),
        ),
    ]
