# Generated by Django 5.2.12 on 2026-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0021_alter_medicalsharerecord_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationreport',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='examinationreport',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='healthexamreport',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='healthexamreport',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='healthmetricrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='healthmetricrecord',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='medicinebox',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='medicinebox',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='membermedicalexamplan',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='membermedicalexamplan',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='membermedicalkeyindicatorrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='membermedicalkeyindicatorrecord',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='membermedicalprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='membermedicalprofile',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='membermodulesetting',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='membermodulesetting',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='surgery',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='symptom',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='归档时间', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_archived',
            field=models.BooleanField(db_comment='是否归档', db_index=True, default=False),
        ),
    ]
