# Generated by Django 6.0.7 on 2026-08-23 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0022_medicalbasemodel_archive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGuideGeneratedQuestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='展示文案', max_length=120)),
                ('prompt', models.TextField(db_comment='完整 prompt')),
                ('category', models.CharField(db_comment='问题分类', db_index=True, default='popular_science', max_length=64)),
                ('locale', models.CharField(db_comment='语言区域', db_index=True, default='zh-Hans', max_length=32)),
                ('click_count', models.PositiveIntegerField(db_comment='点击次数', db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True)),
                ('member', models.ForeignKey(db_comment='关联成员', on_delete=django.db.models.deletion.CASCADE, related_name='guide_generated_questions', to='medical.member')),
                ('user', models.ForeignKey(db_comment='登记用户', on_delete=django.db.models.deletion.CASCADE, related_name='guide_generated_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_chat_guide_generated_question_record',
                'db_table_comment': '客户端 AI 生成引导卡片科普问题登记与点击统计记录。',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='medical_cha_user_id_20f498_idx'), models.Index(fields=['member', 'created_at'], name='medical_cha_member__eaa07e_idx'), models.Index(fields=['category', 'created_at'], name='medical_cha_categor_a19e58_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatGuideQuickQuestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='卡片展示文案，要求短句', max_length=120)),
                ('prompt', models.TextField(db_comment='点击后发送给 AI 的完整 prompt')),
                ('category', models.CharField(db_comment='问题分类', db_index=True, default='popular_science', max_length=64)),
                ('locale', models.CharField(db_comment='语言区域', db_index=True, default='zh-Hans', max_length=32)),
                ('is_active', models.BooleanField(db_comment='是否启用', db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, db_comment='扩展信息，例如适用场景、标签', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_comment='创建操作员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_question_configs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_comment='最近编辑操作员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_question_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_chat_guide_quick_question_config',
                'db_table_comment': '对话引导卡片固定快捷问题配置（后台运营配置）。',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='medical_cha_is_acti_9d1ba4_idx'), models.Index(fields=['locale', 'category', 'is_active'], name='medical_cha_locale_8bffb4_idx')],
            },
        ),
    ]
