from django.urls import path

from hospital_care.api.staff.views import (
    DoctorConsultPatientListView,
    DoctorConsultRecordsView,
    DoctorConversationAttachmentUploadView,
    DoctorConversationDetailView,
    DoctorConversationEndView,
    DoctorConversationJoinView,
    DoctorConversationLeaveView,
    DoctorConversationListView,
    DoctorConversationMessagesView,
    DoctorSymptomCollectionView,
    DoctorSupplementaryReportView,
    DoctorConversationReadCursorView,
    DoctorConversationWebSocketTicketView,
    DoctorPatientConversationsView,
    DoctorPatientListView,
    DoctorPatientWorkspaceView,
    DoctorWorkspaceView,
    StaffAgentSubmitView,
    StaffAgentView,
    StaffMeView,
    StaffWorkLogView,
)

urlpatterns = [
    path("me/", StaffMeView.as_view(), name="hospital-care-staff-me"),
    path("me/agent/", StaffAgentView.as_view(), name="hospital-care-staff-agent"),
    path("me/agent/submit/", StaffAgentSubmitView.as_view(), name="hospital-care-staff-agent-submit"),
    path("me/work-logs/", StaffWorkLogView.as_view(), name="hospital-care-staff-work-logs"),
    path("me/workspace/", DoctorWorkspaceView.as_view(), name="hospital-care-staff-workspace"),
    path("doctor/consults/patients/", DoctorConsultPatientListView.as_view(), name="hospital-care-staff-consult-patients"),
    path("doctor/consults/patients/<int:member_id>/records/", DoctorConsultRecordsView.as_view(), name="hospital-care-staff-consult-records"),
    path("doctor/patients/", DoctorPatientListView.as_view(), name="hospital-care-staff-patients"),
    path("doctor/patients/<int:member_id>/workspace/", DoctorPatientWorkspaceView.as_view(), name="hospital-care-staff-patient-workspace"),
    path("doctor/patients/<int:member_id>/conversations/", DoctorPatientConversationsView.as_view(), name="hospital-care-staff-patient-conversations"),
    path("doctor/conversations/", DoctorConversationListView.as_view(), name="hospital-care-staff-conversations"),
    path("doctor/conversations/ws-tickets/", DoctorConversationWebSocketTicketView.as_view(), name="hospital-care-staff-conversation-ws-tickets"),
    path("doctor/conversations/<uuid:thread_id>/", DoctorConversationDetailView.as_view(), name="hospital-care-staff-conversation-detail"),
    path("doctor/conversations/<uuid:thread_id>/messages/", DoctorConversationMessagesView.as_view(), name="hospital-care-staff-messages"),
    path("doctor/conversations/<uuid:thread_id>/symptom-collection/", DoctorSymptomCollectionView.as_view(), name="hospital-care-staff-symptom-collection"),
    path("doctor/conversations/<uuid:thread_id>/supplementary-report/", DoctorSupplementaryReportView.as_view(), name="hospital-care-staff-supplementary-report"),
    path("doctor/conversations/<uuid:thread_id>/join/", DoctorConversationJoinView.as_view(), name="hospital-care-staff-join"),
    path("doctor/conversations/<uuid:thread_id>/leave/", DoctorConversationLeaveView.as_view(), name="hospital-care-staff-leave"),
    path("doctor/conversations/<uuid:thread_id>/end/", DoctorConversationEndView.as_view(), name="hospital-care-staff-end"),
    path("doctor/conversations/<uuid:thread_id>/read-cursor/", DoctorConversationReadCursorView.as_view(), name="hospital-care-staff-read-cursor"),
    path("doctor/conversations/<uuid:thread_id>/attachments/", DoctorConversationAttachmentUploadView.as_view(), name="hospital-care-staff-attachments"),
]
