from django.urls import path

from hospital_care.api.staff.views import (
    DoctorConsultPatientListView,
    DoctorConsultRecordsView,
    DoctorConversationAttachmentUploadView,
    DoctorConversationAttentionView,
    DoctorConversationDetailView,
    DoctorConversationEndView,
    DoctorConversationJoinView,
    DoctorConversationLeaveView,
    DoctorConversationListView,
    DoctorConversationMessagesView,
    DoctorConversationReadCursorView,
    DoctorConversationRiskHistoryView,
    DoctorConversationRiskView,
    DoctorConversationWebSocketTicketView,
    DoctorPatientConversationsView,
    DoctorPatientListView,
    DoctorPatientRiskView,
    DoctorPatientSummaryAckView,
    DoctorPatientSummaryGenerateView,
    DoctorPatientSummaryView,
    DoctorPatientWorkspaceView,
    DoctorWorkspaceView,
    StaffAgentSubmitView,
    StaffAgentView,
    StaffMeView,
    StaffWorkLogView,
)

urlpatterns = [
    path("me/", StaffMeView.as_view(), name="hospital-care-staff-me"),
    path("me/agent/", StaffAgentView.as_view(), name="hospital-care-staff-agent"),
    path("me/agent/submit/", StaffAgentSubmitView.as_view(), name="hospital-care-staff-agent-submit"),
    path("me/work-logs/", StaffWorkLogView.as_view(), name="hospital-care-staff-work-logs"),
    path("me/workspace/", DoctorWorkspaceView.as_view(), name="hospital-care-staff-workspace"),
    path("doctor/consults/patients/", DoctorConsultPatientListView.as_view(), name="hospital-care-staff-consult-patients"),
    path("doctor/consults/patients/<int:member_id>/records/", DoctorConsultRecordsView.as_view(), name="hospital-care-staff-consult-records"),
    path("doctor/patients/", DoctorPatientListView.as_view(), name="hospital-care-staff-patients"),
    path("doctor/patients/<int:member_id>/workspace/", DoctorPatientWorkspaceView.as_view(), name="hospital-care-staff-patient-workspace"),
    path("doctor/patients/<int:member_id>/conversations/", DoctorPatientConversationsView.as_view(), name="hospital-care-staff-patient-conversations"),
    path("doctor/patients/<int:member_id>/summary/", DoctorPatientSummaryView.as_view(), name="hospital-care-staff-patient-summary"),
    path("doctor/patients/<int:member_id>/summary/generate/", DoctorPatientSummaryGenerateView.as_view(), name="hospital-care-staff-patient-summary-generate"),
    path("doctor/patients/<int:member_id>/summary/ack/", DoctorPatientSummaryAckView.as_view(), name="hospital-care-staff-patient-summary-ack"),
    path("doctor/patients/<int:member_id>/risk/", DoctorPatientRiskView.as_view(), name="hospital-care-staff-patient-risk"),
    path("doctor/conversations/", DoctorConversationListView.as_view(), name="hospital-care-staff-conversations"),
    path("doctor/conversations/ws-tickets/", DoctorConversationWebSocketTicketView.as_view(), name="hospital-care-staff-conversation-ws-tickets"),
    path("doctor/conversations/<uuid:thread_id>/", DoctorConversationDetailView.as_view(), name="hospital-care-staff-conversation-detail"),
    path("doctor/conversations/<uuid:thread_id>/messages/", DoctorConversationMessagesView.as_view(), name="hospital-care-staff-messages"),
    path("doctor/conversations/<uuid:thread_id>/join/", DoctorConversationJoinView.as_view(), name="hospital-care-staff-join"),
    path("doctor/conversations/<uuid:thread_id>/leave/", DoctorConversationLeaveView.as_view(), name="hospital-care-staff-leave"),
    path("doctor/conversations/<uuid:thread_id>/attention/", DoctorConversationAttentionView.as_view(), name="hospital-care-staff-attention"),
    path("doctor/conversations/<uuid:thread_id>/end/", DoctorConversationEndView.as_view(), name="hospital-care-staff-end"),
    path("doctor/conversations/<uuid:thread_id>/risk/", DoctorConversationRiskView.as_view(), name="hospital-care-staff-risk"),
    path("doctor/conversations/<uuid:thread_id>/risk-history/", DoctorConversationRiskHistoryView.as_view(), name="hospital-care-staff-risk-history"),
    path("doctor/conversations/<uuid:thread_id>/read-cursor/", DoctorConversationReadCursorView.as_view(), name="hospital-care-staff-read-cursor"),
    path("doctor/conversations/<uuid:thread_id>/attachments/", DoctorConversationAttachmentUploadView.as_view(), name="hospital-care-staff-attachments"),
]
