from django.urls import path

from notification_center.views import (
    AdminNotificationAnalyticsView,
    AdminNotificationCampaignListView,
    AdminNotificationChannelSettingsView,
    AdminNotificationIntentDetailView,
    AdminNotificationIntentListView,
    AdminNotificationOverviewView,
    AdminNotificationLogDetailView,
    AdminNotificationLogListView,
    AdminNotificationPreviewView,
    AdminNotificationRecordListView,
    AdminNotificationSceneDetailView,
    AdminNotificationSceneListView,
    AdminNotificationSendView,
    AdminNotificationSuppressionListCreateView,
    AdminNotificationSuppressionReleaseView,
    AdminNotificationTemplateDetailView,
    AdminNotificationTemplateListCreateView,
    AdminNotificationUserListView,
    AdminSmsSendDetailsQueryView,
)

urlpatterns = [
    path("overview/", AdminNotificationOverviewView.as_view(), name="notification-center-overview"),
    path("notification-scenes/", AdminNotificationSceneListView.as_view(), name="notification-center-scene-list"),
    path("notification-scenes/<str:scene_key>/", AdminNotificationSceneDetailView.as_view(), name="notification-center-scene-detail"),
    path("notification-intents/", AdminNotificationIntentListView.as_view(), name="notification-center-intent-list"),
    path("notification-intents/<int:intent_id>/", AdminNotificationIntentDetailView.as_view(), name="notification-center-intent-detail"),
    path("notifications/users/", AdminNotificationUserListView.as_view(), name="notification-center-users"),
    path("notifications/send/", AdminNotificationSendView.as_view(), name="notification-center-send"),
    path("notifications/templates/", AdminNotificationTemplateListCreateView.as_view(), name="notification-center-template-list-create"),
    path("notifications/templates/<int:template_id>/", AdminNotificationTemplateDetailView.as_view(), name="notification-center-template-detail"),
    path("notifications/preview/", AdminNotificationPreviewView.as_view(), name="notification-center-preview"),
    path("notifications/campaigns/", AdminNotificationCampaignListView.as_view(), name="notification-center-campaign-list"),
    path("notifications/records/<str:channel>/", AdminNotificationRecordListView.as_view(), name="notification-center-record-list"),
    path("notifications/sms-records/<int:message_id>/query-send-details/", AdminSmsSendDetailsQueryView.as_view(), name="notification-center-sms-query-send-details"),
    path("notifications/logs/<str:channel>/", AdminNotificationLogListView.as_view(), name="notification-center-log-list"),
    path("notifications/logs/detail/<int:log_id>/", AdminNotificationLogDetailView.as_view(), name="notification-center-log-detail"),
    path("notifications/suppressions/", AdminNotificationSuppressionListCreateView.as_view(), name="notification-center-suppression-list-create"),
    path(
        "notifications/suppressions/<int:suppression_id>/release/",
        AdminNotificationSuppressionReleaseView.as_view(),
        name="notification-center-suppression-release",
    ),
    path("analytics/", AdminNotificationAnalyticsView.as_view(), name="notification-center-analytics"),
    path("channel-settings/", AdminNotificationChannelSettingsView.as_view(), name="notification-center-channel-settings"),
]
