# Generated by Django 6.0.7 on 2026-09-01 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def align_knowledge_join_columns(apps, schema_editor):
    """Match chat_sync UUID collation so JOINs on knowledge_base/document work."""
    if schema_editor.connection.vendor != "mysql":
        return
    statements = [
        """
        ALTER TABLE hospital_care_hospitalknowledgebaseprofile
        MODIFY knowledge_base_id char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
        """,
        """
        ALTER TABLE hospital_care_hospitalknowledgechunk
        MODIFY document_id char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
        """,
    ]
    with schema_editor.connection.cursor() as cursor:
        for sql in statements:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0006_alter_aiscenariomodelbinding_scenario_and_more'),
        ('chat_sync', '0017_drop_knowledge_index_tables'),
        ('hospital_care', '0004_backfill_and_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='knowledge_service_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_knowledge_service_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HospitalKnowledgeBaseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('vector_status', models.CharField(choices=[('not_built', 'Not Built'), ('current', 'Current'), ('stale', 'Stale')], db_index=True, default='not_built', max_length=16)),
                ('indexed_revision', models.BigIntegerField(blank=True, null=True)),
                ('version', models.BigIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hospital_knowledge_bases', to=settings.AUTH_USER_MODEL)),
                ('embedding_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_knowledge_profiles', to='ai_config.aiscenariomodelbinding')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_base_profiles', to='hospital_care.hospital')),
                ('knowledge_base', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_profile', to='chat_sync.knowledgebase')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_hospital_knowledge_bases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalKnowledgeBaseDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_base_links', to='hospital_care.hospitaldepartment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='hospital_care.hospitalknowledgebaseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalKnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_revision', models.BigIntegerField()),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('vector_payload', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_chunks', to='chat_sync.knowledgedocument')),
                ('embedding_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_knowledge_chunks', to='ai_config.aiscenariomodelbinding')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='hospital_care.hospitalknowledgebaseprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='hospitalknowledgebaseprofile',
            index=models.Index(fields=['hospital', 'is_deleted', 'name'], name='idx_hkb_hospital_name'),
        ),
        migrations.AddConstraint(
            model_name='hospitalknowledgebasedepartment',
            constraint=models.UniqueConstraint(fields=('profile', 'department'), name='uniq_hkb_profile_department'),
        ),
        migrations.AddIndex(
            model_name='hospitalknowledgechunk',
            index=models.Index(fields=['profile', 'document'], name='idx_hkb_chunk_profile_doc'),
        ),
        migrations.AddConstraint(
            model_name='hospitalknowledgechunk',
            constraint=models.UniqueConstraint(fields=('profile', 'document', 'chunk_index'), name='uniq_hkb_chunk_doc_index'),
        ),
        migrations.RunPython(align_knowledge_join_columns, migrations.RunPython.noop),
    ]
