# Generated by Django 6.0.7 on 2026-09-03 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_care', '0005_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.IntegerField(db_index=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('current_issues', models.TextField(blank=True, db_comment='当前问题/服务概况', default='')),
                ('key_health_info', models.TextField(blank=True, db_comment='关键健康信息', default='')),
                ('conversation_highlights', models.TextField(blank=True, db_comment='会话要点', default='')),
                ('follow_up_items', models.JSONField(blank=True, db_comment='待跟进事项', default=list)),
                ('input_snapshot', models.JSONField(blank=True, db_comment='生成输入快照：会话集合、资料时间、工具版本', default=dict)),
                ('tool_name', models.CharField(default='patient-workspace-summary-v1', max_length=64)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_summaries', to='hospital_care.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_summaries', to='hospital_care.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatientSummaryAck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged', models.BooleanField(default=True)),
                ('acted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_summary_acks', to='hospital_care.doctorprofile')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='hospital_care.doctorpatientsummary')),
            ],
        ),
        migrations.AddIndex(
            model_name='doctorpatientsummary',
            index=models.Index(fields=['doctor', 'member_id', '-generated_at'], name='idx_patient_summary_latest'),
        ),
        migrations.AddConstraint(
            model_name='doctorpatientsummary',
            constraint=models.UniqueConstraint(fields=('doctor', 'member_id', 'version'), name='uniq_patient_summary_version'),
        ),
        migrations.AddConstraint(
            model_name='doctorpatientsummaryack',
            constraint=models.UniqueConstraint(fields=('summary', 'doctor'), name='uniq_patient_summary_ack'),
        ),
    ]
