# Generated by Django 6.0.7 on 2026-09-04 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0006_alter_aiscenariomodelbinding_scenario_and_more'),
        ('file_manager', '0001_initial'),
        ('hospital_care', '0006_doctorpatientsummary_doctorpatientsummaryack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalagentprofile',
            name='avatar_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_agent_avatars', to='file_manager.managedfile'),
        ),
        migrations.AddField(
            model_name='clinicalagentprofile',
            name='avatar_source',
            field=models.CharField(choices=[('doctor', '复用医生头像'), ('custom', '专属头像')], default='doctor', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='clinicalagentprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('avatar_file__isnull', True), ('avatar_source', 'doctor')), models.Q(('avatar_file__isnull', False), ('avatar_source', 'custom')), _connector='OR'), name='chk_agent_avatar_source_file'),
        ),
    ]
