# Generated by Django 6.0.7 on 2026-09-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0006_alter_aiscenariomodelbinding_scenario_and_more'),
        ('hospital_care', '0007_clinical_agent_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalconversationbinding',
            name='scenario_binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_bindings', to='ai_config.aiscenariomodelbinding'),
        ),
    ]
