# Generated by Django 6.0.7 on 2026-09-05 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sync', '0017_drop_knowledge_index_tables'),
        ('hospital_care', '0008_clinicalconversationbinding_scenario_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalconversationbinding',
            name='end_reason_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='clinicalconversationbinding',
            name='end_reason_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DoctorConversationReadCursor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_read_message_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_read_cursors', to='hospital_care.doctorprofile')),
                ('thread', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_read_cursors', to='chat_sync.chatthread')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'updated_at'], name='idx_read_cursor_doctor_time')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'thread'), name='uniq_doctor_thread_read_cursor')],
            },
        ),
        migrations.CreateModel(
            name='DoctorConversationRiskRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('next_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('doctor_manual', 'Doctor Manual')], default='doctor_manual', max_length=32)),
                ('version', models.BigIntegerField(default=1)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_revisions', to='hospital_care.clinicalconversationbinding')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_revisions', to='hospital_care.doctorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['binding', 'created_at', 'id'], name='idx_risk_revision_binding_time')],
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientAttention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('level', models.CharField(choices=[('normal', 'Normal'), ('follow_up', 'Follow Up'), ('priority', 'Priority')], default='normal', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_attentions', to='hospital_care.doctorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'level'], name='idx_patient_attention_level')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'member_id'), name='uniq_doctor_patient_attention')],
            },
        ),
    ]
