# Generated by Django 6.0.7 on 2026-09-05 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_care', '0009_clinicalconversationbinding_end_reason_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consult_no', models.CharField(max_length=24, unique=True)),
                ('consult_date', models.DateField()),
                ('daily_seq', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binding', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='hospital_care.clinicalconversationbinding')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['member_id', 'submitted_at'], name='idx_consultation_member_time'), models.Index(fields=['submitted_at'], name='idx_consultation_submitted')],
                'constraints': [models.UniqueConstraint(fields=('consult_date', 'daily_seq'), name='uniq_consultation_date_seq')],
            },
        ),
    ]
