# Generated by Django 6.0.7 on 2026-09-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_care', '0010_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='allergy_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='family_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='order_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultation',
            name='past_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
