# Generated by Django 6.0.3 on 2026-04-02 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeactivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('frozen', 'Frozen'), ('anonymized', 'Anonymized'), ('cleaned_up', 'Cleaned Up'), ('deactivated', 'Deactivated'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='requested', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('freeze_email', models.EmailField(blank=True, default='', max_length=254)),
                ('freeze_phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDeactivationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('freeze_identifiers', 'Freeze Identifiers'), ('anonymize', 'Anonymize'), ('cleanup_otps', 'Cleanup Otps'), ('deactivate_user', 'Deactivate User'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='accounts.accountdeactivation')),
            ],
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('provider_uid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('bundle_id', models.CharField(blank=True, default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'expires_at'], name='accounts_em_email_86cc9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('password', 'Password'), ('email_otp', 'Email Otp'), ('phone_otp', 'Phone Otp'), ('google', 'Google'), ('apple', 'Apple')], max_length=32)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('bundle_id', models.CharField(blank=True, default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('raw_claims', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('provider_uid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('bundle_id', models.CharField(blank=True, default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', 'expires_at'], name='accounts_ph_phone_n_86e8a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('bundle_id', models.CharField(blank=True, default='', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_trusted_device_per_user')],
            },
        ),
    ]
