# Generated by Django 5.2.12 on 2026-06-04 15:11

from django.conf import settings
from django.db import migrations, models


def merge_duplicate_trusted_devices(apps, schema_editor):
    AccountDeviceSession = apps.get_model("accounts", "AccountDeviceSession")
    TrustedDevice = apps.get_model("accounts", "TrustedDevice")
    database = schema_editor.connection.alias

    keys = (
        TrustedDevice.objects.using(database)
        .values("bundle_id", "device_id", "user_id")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
    )
    for key in keys.iterator():
        rows = list(
            TrustedDevice.objects.using(database)
            .filter(
                bundle_id=key["bundle_id"],
                device_id=key["device_id"],
                user_id=key["user_id"],
            )
            .order_by("-last_seen", "-id")
        )
        keeper, duplicates = rows[0], rows[1:]
        duplicate_ids = [row.id for row in duplicates]
        AccountDeviceSession.objects.using(database).filter(
            trusted_device_id__in=duplicate_ids
        ).update(trusted_device_id=keeper.id)
        TrustedDevice.objects.using(database).filter(id__in=duplicate_ids).delete()


def drop_legacy_bundle_device_index(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    TrustedDevice = apps.get_model("accounts", "TrustedDevice")
    table = TrustedDevice._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table)
    if "uniq_bundle_device" not in constraints:
        return

    quote = schema_editor.quote_name
    schema_editor.execute(
        f"ALTER TABLE {quote(table)} DROP INDEX {quote('uniq_bundle_device')}"
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountdevicesession',
            name='uniq_active_device_session_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='trusteddevice',
            name='uniq_bundle_device_anonymous',
        ),
        migrations.RemoveConstraint(
            model_name='trusteddevice',
            name='uniq_bundle_device_user_bound',
        ),
        migrations.RunPython(
            merge_duplicate_trusted_devices,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            drop_legacy_bundle_device_index,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='bundle_id',
            field=models.CharField(db_comment='应用维度分组键；用户设备行与 device_id、user 共同唯一', db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.CharField(db_comment='客户端安装级稳定设备标识（如 Keychain UUID）；允许同一安装保留多个用户历史行', db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='trusteddevice',
            constraint=models.UniqueConstraint(fields=('bundle_id', 'device_id', 'user'), name='uniq_bundle_device_user_bound'),
        ),
    ]
