# Generated by Django 5.2.12 on 2026-06-02 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.CharField(db_comment='登录时 bundle_id 快照', db_index=True, default='', max_length=255)),
                ('device_id', models.CharField(db_comment='登录时 device_id 快照', db_index=True, default='', max_length=255)),
                ('session_version', models.PositiveIntegerField(db_comment='会话版本号，写入 JWT claim', db_index=True, default=1)),
                ('refresh_jti', models.CharField(blank=True, db_comment='当前 refresh token jti', db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已失效'), ('logged_out', '已退出')], db_comment='会话状态', db_index=True, default='active', max_length=32)),
                ('revoked_reason', models.CharField(blank=True, db_comment='失效原因（如 replaced_by_new_device）', default='', max_length=64)),
                ('last_refreshed_at', models.DateTimeField(blank=True, db_comment='最近一次 refresh 成功时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replaced_by', models.ForeignKey(blank=True, db_comment='被哪条新会话替换', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_sessions', to='accounts.accountdevicesession')),
                ('trusted_device', models.ForeignKey(db_comment='绑定的可信设备安装实例', on_delete=django.db.models.deletion.CASCADE, related_name='account_sessions', to='accounts.trusteddevice')),
                ('user', models.ForeignKey(db_comment='所属用户', on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '设备登录会话',
                'verbose_name_plural': '设备登录会话',
                'db_table_comment': '账号设备登录会话：单用户单 ACTIVE，供 token 校验与 APNs 投递。',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_device_session_per_user')],
            },
        ),
    ]
