# Generated by Django 5.2.12 on 2026-07-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_trusted_device_uniqueness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='template',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='NotificationCampaign',
        ),
        migrations.DeleteModel(
            name='NotificationMessage',
        ),
    ]
