# Generated by Django 5.2.12 on 2026-07-12 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_notificationcampaign_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='requested_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_phone_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='resolved_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_otps', to='accounts.socialidentity'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='scene',
            field=models.CharField(blank=True, db_index=True, default='login', max_length=64),
        ),
    ]
