# Generated by Django 5.2.12 on 2026-06-03 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trusted_device_user_scoped_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='trusteddevice',
            table_comment='客户端上报的可信安装实例：匿名 bundle+device 唯一；已登录用户 bundle+device+user 唯一。',
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='关联 Django User；NULL=匿名冷启动画像，非 NULL=该用户设备行（与匿名行并存，不改绑匿名行）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
