# Generated by Django 5.2.12 on 2026-04-11 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_restore_user_fk_from_legacy_int'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trusteddevice',
            options={'verbose_name': '可信设备', 'verbose_name_plural': '可信设备'},
        ),
        migrations.AlterModelTableComment(
            name='trusteddevice',
            table_comment='客户端上报的可信安装实例：bundle_id+device_id 唯一，支持匿名后关联用户。',
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='app_version',
            field=models.CharField(blank=True, db_comment='面向用户的应用版本号（如 Marketing 版本）', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='build_version',
            field=models.CharField(blank=True, db_comment='构建号（CFBundleVersion 等）', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='bundle_id',
            field=models.CharField(db_comment='应用维度分组键，与 device_id 组成唯一约束（可与 bundle_identifier 相同或业务自定义）', db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='bundle_identifier',
            field=models.CharField(blank=True, db_comment='包标识符（如 com.example.app），与 bundle_id 区分时可并存', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.CharField(db_comment='客户端安装级稳定设备标识（如 Keychain UUID），与 bundle_id 唯一', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_model',
            field=models.CharField(blank=True, db_comment='设备硬件型号代码（如 iPhone15,2）', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_model_name',
            field=models.CharField(blank=True, db_comment='设备市场友好名称（若客户端可解析）', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_name',
            field=models.CharField(blank=True, db_comment='用户在系统中设置的设备名称（可能含隐私，注意展示策略）', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, db_comment='首次登记时间'),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='is_revoked',
            field=models.BooleanField(db_comment='是否已吊销（禁止推送或拒绝敏感操作等策略可读取）', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='is_simulator',
            field=models.BooleanField(db_comment='是否在模拟器环境运行', default=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='language_code',
            field=models.CharField(blank=True, db_comment='首选语言代码（BCP 47 或短码）', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_comment='最近一次上报或刷新时间'),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='notifications_enabled',
            field=models.BooleanField(db_comment='用户是否在系统设置中允许本应用通知（客户端上报）', default=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='platform',
            field=models.CharField(blank=True, db_comment='平台标识（如 ios、android）', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='push_token',
            field=models.CharField(blank=True, db_comment='APNs/FCM 等设备推送令牌（十六进制或供应商格式），可空', default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='region_code',
            field=models.CharField(blank=True, db_comment='区域代码（如 CN、US）', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='request_id',
            field=models.CharField(blank=True, db_comment='关联网关或链路 request id，便于日志串联', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='screen_scale',
            field=models.FloatField(blank=True, db_comment='屏幕 scale（@2x/@3x 等）', null=True),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='screen_size',
            field=models.CharField(blank=True, db_comment='逻辑分辨率描述（如 393x852）', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='system_version',
            field=models.CharField(blank=True, db_comment='操作系统版本字符串', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='time_zone',
            field=models.CharField(blank=True, db_comment='当前系统时区标识符', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='关联 Django User；匿名登记为空，登录成功后回填', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='verified',
            field=models.BooleanField(db_comment='是否通过额外设备证明（预留，默认未验证）', default=False),
        ),
    ]
