# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phone_otp_request_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneotp",
            name="send_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("accepted", "Accepted"),
                    ("submit_failed", "Submit Failed"),
                    ("submit_unknown", "Submit Unknown"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="notification_message_id",
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="provider_request_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="provider_biz_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="send_error_code",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="send_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
