# Generated by Django 5.2.12 on 2026-07-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phone_otp_send_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialidentity',
            name='bundle_id',
            field=models.CharField(blank=True, db_comment='账号身份作用域 identity_scope；可能与真实客户端 bundle_id 不同', db_index=True, default='', max_length=128),
        ),
    ]
