# Generated by Django 5.2.12 on 2026-04-14 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_trusted_device_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('apns', 'APNs'), ('email', 'Email'), ('sms', 'SMS')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('sent', '已发送'), ('failed', '发送失败'), ('partial', '部分成功'), ('skipped', '已跳过')], db_index=True, default='sent', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivery_details', models.JSONField(blank=True, default=list)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('receiver_email', models.EmailField(blank=True, default='', max_length=254)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=32)),
                ('apns_topic', models.CharField(blank=True, default='', max_length=255)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notification_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-created_at'], name='accounts_no_channel_cdc705_idx'), models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_7714f0_idx')],
            },
        ),
    ]
