# Generated by Django 5.2.12 on 2026-07-15 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_socialidentity_bundle_id_identity_scope_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialidentity',
            name='provider',
            field=models.CharField(choices=[('apple', 'Apple'), ('google', 'Google'), ('phone', 'Phone'), ('email', 'Email')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='AccountIdentityVerificationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('bind_identity', 'Bind Identity'), ('change_identity', 'Change Identity')], db_index=True, max_length=32)),
                ('verified_provider', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('apple', 'Apple')], db_index=True, max_length=32)),
                ('identity_scope', models.CharField(db_comment='账号身份作用域', db_index=True, default='', max_length=128)),
                ('bundle_id', models.CharField(blank=True, db_comment='真实客户端 bundle_id', default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('ticket_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_comment='签发对象用户', on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': '账号登录方式绑定/修改再认证一次性 ticket',
                'indexes': [models.Index(fields=['user', 'purpose', 'expires_at'], name='accounts_ac_user_id_cb1dd7_idx')],
            },
        ),
    ]
