# Generated by Django 5.2.12 on 2026-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_socialidentity_email_and_identity_verification_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginaudit',
            name='provider',
            field=models.CharField(choices=[('password', 'Password'), ('email_otp', 'Email Otp'), ('phone_otp', 'Phone Otp'), ('google', 'Google'), ('apple', 'Apple'), ('device', 'Device')], max_length=32),
        ),
        migrations.AlterField(
            model_name='socialidentity',
            name='provider',
            field=models.CharField(choices=[('apple', 'Apple'), ('google', 'Google'), ('phone', 'Phone'), ('email', 'Email'), ('device', 'Device')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='DeviceLoginCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_scope', models.CharField(db_comment='账号身份作用域 identity_scope', db_index=True, max_length=128)),
                ('device_id', models.CharField(db_comment='客户端安装级稳定设备标识', db_index=True, max_length=255)),
                ('secret_hash', models.CharField(db_comment='device_secret 的不可逆哈希（Django make_password）', max_length=128)),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已吊销')], db_index=True, default='active', max_length=32)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.CharField(blank=True, default='', max_length=64)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '设备登录凭证',
                'verbose_name_plural': '设备登录凭证',
                'db_table_comment': '设备游客登录安装凭证：UNIQUE(identity_scope, device_id)',
                'constraints': [models.UniqueConstraint(fields=('identity_scope', 'device_id'), name='uniq_device_login_credential_scope_device')],
            },
        ),
    ]
