# Generated by Django 5.2.12 on 2026-05-06 07:56

from django.db import migrations, models


def map_legacy_deactivation_states(apps, schema_editor):
    AccountDeactivation = apps.get_model("accounts", "AccountDeactivation")
    AccountDeactivationAudit = apps.get_model("accounts", "AccountDeactivationAudit")

    AccountDeactivation.objects.filter(state="frozen").update(state="data_backed_up")
    AccountDeactivation.objects.filter(state="cleaned_up").update(state="related_data_deleted")
    AccountDeactivation.objects.filter(state="deactivated").update(state="completed")

    AccountDeactivationAudit.objects.filter(action="freeze_identifiers").update(action="data_backup")
    AccountDeactivationAudit.objects.filter(action="anonymize").update(action="data_anonymize")
    AccountDeactivationAudit.objects.filter(action="cleanup_otps").update(action="related_data_delete")
    AccountDeactivationAudit.objects.filter(action="deactivate_user").update(action="account_deactivate")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationcampaign_notificationmessage_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeactivation',
            name='anonymize_personal_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountdeactivation',
            name='backup_checksum',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='accountdeactivation',
            name='backup_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdeactivation',
            name='backup_uri',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='accountdeactivation',
            name='data_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='accountdeactivation',
            name='delete_related_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountdeactivation',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.RunPython(map_legacy_deactivation_states, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accountdeactivation',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('data_backed_up', 'Data Backed Up'), ('anonymized', 'Anonymized'), ('related_data_deleted', 'Related Data Deleted'), ('account_disabled', 'Account Disabled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='requested', max_length=32),
        ),
        migrations.AlterField(
            model_name='accountdeactivationaudit',
            name='action',
            field=models.CharField(choices=[('requested', 'Requested'), ('data_backup', 'Data Backup'), ('data_anonymize', 'Data Anonymize'), ('related_data_delete', 'Related Data Delete'), ('account_deactivate', 'Account Deactivate'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, max_length=64),
        ),
    ]
