# Generated by Django 6.0.7 on 2026-08-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_access_deny_entry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessdenyentry',
            new_name='accounts_ac_dimensi_58367d_idx',
            old_name='accounts_ac_dimensi_6a8f2d_idx',
        ),
    ]
