# Generated by Django 6.0.7 on 2026-08-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_access_deny_conditional_unique'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='accessdenyentry',
            table_comment='登录注册黑名单：有效条目在应用层保证 dimension+dimension_value 唯一',
        ),
    ]
