# Generated by Django 6.0.7 on 2026-08-19 03:59

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def _normalize_device_id(value: str) -> str:
    return (value or "").strip()


def _collect_user_device_ids(*, user, TrustedDevice, AccountDeviceSession, SocialIdentity, LoginAudit):
    device_ids: set[str] = set()
    for device_id in TrustedDevice.objects.filter(user=user).values_list("device_id", flat=True):
        normalized = _normalize_device_id(device_id)
        if normalized:
            device_ids.add(normalized)
    for device_id in AccountDeviceSession.objects.filter(user=user).values_list("device_id", flat=True):
        normalized = _normalize_device_id(device_id)
        if normalized:
            device_ids.add(normalized)
    for provider_uid in SocialIdentity.objects.filter(user=user, provider="device").values_list("provider_uid", flat=True):
        normalized = _normalize_device_id(provider_uid)
        if normalized:
            device_ids.add(normalized)
    for device_id in (
        LoginAudit.objects.filter(user=user, outcome="success")
        .exclude(device_id="")
        .values_list("device_id", flat=True)
        .distinct()
    ):
        normalized = _normalize_device_id(device_id)
        if normalized:
            device_ids.add(normalized)
    return device_ids


def backfill_device_deny_entries(apps, schema_editor):
    AccessDenyEntry = apps.get_model("accounts", "AccessDenyEntry")
    User = apps.get_model("auth", "User")
    TrustedDevice = apps.get_model("accounts", "TrustedDevice")
    AccountDeviceSession = apps.get_model("accounts", "AccountDeviceSession")
    SocialIdentity = apps.get_model("accounts", "SocialIdentity")
    LoginAudit = apps.get_model("accounts", "LoginAudit")

    now = timezone.now()
    active_user_entries = (
        AccessDenyEntry.objects.filter(dimension="user_id", revoked_at__isnull=True)
        .filter(Q(expires_at__isnull=True) | Q(expires_at__gt=now))
        .order_by("id")
    )
    for entry in active_user_entries:
        try:
            user_id = int(entry.dimension_value)
        except (TypeError, ValueError):
            continue
        user = User.objects.filter(id=user_id).first()
        if user is None:
            continue
        for device_id in _collect_user_device_ids(
            user=user,
            TrustedDevice=TrustedDevice,
            AccountDeviceSession=AccountDeviceSession,
            SocialIdentity=SocialIdentity,
            LoginAudit=LoginAudit,
        ):
            exists = AccessDenyEntry.objects.filter(
                dimension="device",
                dimension_value=device_id,
                revoked_at__isnull=True,
            ).filter(Q(expires_at__isnull=True) | Q(expires_at__gt=now)).exists()
            if exists:
                continue
            AccessDenyEntry.objects.create(
                dimension="device",
                dimension_value=device_id,
                reason_code=entry.reason_code or "account_banned",
                reason_note=entry.reason_note or "",
                source="auto_expand",
                related_user_id=user_id,
                created_by_id=entry.created_by_id,
                metadata={"backfilled_from_user_entry_id": entry.id},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_accessdenyentry_table_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdenyentry',
            name='dimension',
            field=models.CharField(choices=[('user_id', '用户 ID'), ('phone', '手机号'), ('email', '邮箱'), ('device', '设备')], db_index=True, max_length=32),
        ),
        migrations.RunPython(backfill_device_deny_entries, migrations.RunPython.noop),
    ]
