# Generated by Django 6.0.7 on 2026-08-19 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_access_deny_device_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDenyHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('register', '注册'), ('otp_request', 'OTP 请求'), ('identity_bind', '身份绑定')], db_index=True, max_length=32)),
                ('hit_dimension', models.CharField(db_index=True, max_length=32)),
                ('hit_value', models.CharField(db_index=True, max_length=255)),
                ('reason_code', models.CharField(db_index=True, default='account_banned', max_length=64)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('attempted_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('attempted_email', models.CharField(blank=True, default='', max_length=255)),
                ('attempted_phone', models.CharField(blank=True, default='', max_length=32)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('bundle_id', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deny_entry', models.ForeignKey(blank=True, db_comment='命中的黑名单条目，解封后保留记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hits', to='accounts.accessdenyentry')),
            ],
            options={
                'verbose_name': '访问拒绝拦截记录',
                'verbose_name_plural': '访问拒绝拦截记录',
                'db_table_comment': '黑名单拦截记录：append-only，供后台查询',
                'indexes': [models.Index(fields=['created_at', 'id'], name='accounts_ac_created_1750b4_idx'), models.Index(fields=['hit_dimension', 'hit_value'], name='accounts_ac_hit_dim_f1223f_idx'), models.Index(fields=['deny_entry', 'created_at'], name='accounts_ac_deny_en_b215e6_idx')],
            },
        ),
    ]
