# Generated by Django 6.0.7 on 2026-08-25 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_health_web_identity_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWebSession',
            fields=[
                ('id', models.UUIDField(db_comment='Web 会话 ID，写入 JWT web_session_id claim', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已失效'), ('logged_out', '已退出'), ('expired', '已过期')], db_comment='会话状态', db_index=True, default='active', max_length=32)),
                ('session_version', models.PositiveIntegerField(db_comment='会话版本号，写入 JWT web_session_version claim；rotation 时递增', db_index=True, default=1)),
                ('refresh_jti_hash', models.CharField(blank=True, db_comment='当前 refresh token jti 的哈希（不存原始 token）', db_index=True, default='', max_length=128)),
                ('user_agent_hash', models.CharField(blank=True, db_comment='登录时 User-Agent 哈希，用于异常环境审计', default='', max_length=128)),
                ('ip_prefix_hash', models.CharField(blank=True, db_comment='登录时 IP 前缀哈希（可选，脱敏存储）', default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, db_comment='最近一次 refresh 成功时间', null=True)),
                ('expires_at', models.DateTimeField(db_comment='会话过期时间（对齐 refresh token 生命周期）', db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_comment='失效时间', null=True)),
                ('revoked_reason', models.CharField(blank=True, db_comment='失效原因（user_logout/replaced_by_replay/account_deactivated 等）', default='', max_length=64)),
                ('request_id', models.CharField(blank=True, db_comment='创建或最近失效请求的 request id，便于日志串联', default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_comment='所属用户；与移动设备会话共享同一 User 的对话数据', on_delete=django.db.models.deletion.CASCADE, related_name='web_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web 登录会话',
                'verbose_name_plural': 'Web 登录会话',
                'db_table_comment': 'Chat Web 独立登录会话：与设备会话隔离，支持多浏览器并存，不参与单设备替换。',
            },
        ),
    ]
