# Generated by Django 5.2.12 on 2026-05-28 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('client_message_id', models.UUIDField(db_index=True)),
                ('server_message_id', models.CharField(db_index=True, max_length=64)),
                ('delivery_state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='sent', max_length=16)),
                ('tombstone', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('member_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('scenario', models.CharField(choices=[('chat', 'Chat')], default='chat', max_length=32)),
                ('current_model_name', models.CharField(blank=True, default='', max_length=128)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('top_p', models.FloatField(default=1.0)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('max_messages', models.IntegerField(default=20)),
                ('role_prompt', models.TextField(blank=True, default='')),
                ('image_delivery_mode', models.CharField(blank=True, choices=[('directMultimodal', 'Direct Multimodal'), ('localOCR', 'Local Ocr')], db_index=True, max_length=32, null=True)),
                ('icon_name', models.CharField(blank=True, default='', max_length=128)),
                ('icon_color_name', models.CharField(blank=True, default='', max_length=64)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('pinned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, default='text', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('revision', models.BigIntegerField(default=0)),
                ('order_key', models.FloatField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('parent_tool_call_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('parent_block_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('node_role', models.CharField(default='timeline', max_length=32)),
                ('anchor', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='chat_sync.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_blocks', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_blocks', to='chat_sync.chatthread')),
            ],
            options={
                'ordering': ['order_key', 'created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_sync.chatthread'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(fields=('user', 'id'), name='uniq_chat_thread_user_thread'),
        ),
        migrations.AddIndex(
            model_name='chatmessageblock',
            index=models.Index(fields=['message', 'order_key', 'created_at'], name='idx_chat_block_msg_order'),
        ),
        migrations.AddIndex(
            model_name='chatmessageblock',
            index=models.Index(fields=['user', 'server_updated_at', 'id'], name='idx_chat_block_user_sync'),
        ),
        migrations.AddConstraint(
            model_name='chatmessageblock',
            constraint=models.UniqueConstraint(fields=('user', 'id'), name='uniq_chat_block_user_block_id'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'server_updated_at', 'id'], name='idx_chat_msg_user_sync'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at', 'id'], name='idx_chat_msg_thread_created'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('user', 'client_message_id'), name='uniq_chat_message_user_client_id'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('user', 'server_message_id'), name='uniq_chat_message_user_server_id'),
        ),
    ]
