# Generated by Django 5.2.12 on 2026-07-05 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'role', '-created_at', '-id'], name='idx_chat_msg_user_role_time'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-created_at', '-id'], name='idx_chat_msg_user_time'),
        ),
    ]
