# Generated by Django 6.0.7 on 2026-08-24 20:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sync', '0002_chatmessage_idx_chat_msg_user_role_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_for_user_input', 'Waiting for user input'), ('waiting_for_client_tool', 'Waiting for client tool'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], db_index=True, default='queued', max_length=32)),
                ('capability', models.CharField(default='chat', max_length=64)),
                ('capability_version', models.CharField(default='v1', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('model_config_version', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('request_snapshot', models.JSONField(default=dict)),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=128)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('first_token_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retryable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_message', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ai_assistant_runs', to='chat_sync.chatmessage')),
                ('regenerated_from_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerated_ai_runs', to='chat_sync.chatmessage')),
                ('regenerated_from_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerated_runs', to='chat_sync.chatrun')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='chat_sync.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ai_runs', to=settings.AUTH_USER_MODEL)),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ai_user_runs', to='chat_sync.chatmessage')),
            ],
            options={
                'db_table': 'chat_sync_ai_run',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatRunEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveBigIntegerField()),
                ('type', models.CharField(max_length=64)),
                ('payload_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('terminal_marker', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat_sync.chatrun')),
            ],
            options={
                'db_table': 'chat_sync_ai_run_event',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatEventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_group', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='chat_sync.chatrunevent')),
            ],
            options={
                'db_table': 'chat_sync_ai_event_outbox',
            },
        ),
        migrations.CreateModel(
            name='ChatThreadPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('capability', models.CharField(default='chat', max_length=64)),
                ('enabled_tools', models.JSONField(blank=True, default=list)),
                ('knowledge_bases', models.JSONField(blank=True, default=list)),
                ('subagent', models.JSONField(blank=True, default=dict)),
                ('persona', models.JSONField(blank=True, default=dict)),
                ('llm_selection', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('voice_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to='chat_sync.chatthread')),
            ],
            options={
                'db_table': 'chat_sync_ai_thread_preferences',
            },
        ),
        migrations.CreateModel(
            name='ChatThreadRunLock',
            fields=[
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_run_lock', serialize=False, to='chat_sync.chatthread')),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_thread_lock', to='chat_sync.chatrun')),
            ],
            options={
                'db_table': 'chat_sync_ai_thread_run_lock',
            },
        ),
        migrations.CreateModel(
            name='ChatToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_call_id', models.CharField(max_length=128)),
                ('tool_name', models.CharField(max_length=128)),
                ('tool_version', models.CharField(blank=True, default='', max_length=64)),
                ('target', models.CharField(blank=True, default='server', max_length=32)),
                ('arguments', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('running', 'Running'), ('waiting_for_user', 'Waiting for user'), ('waiting_for_client', 'Waiting for client'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=32)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('result_ref', models.CharField(blank=True, default='', max_length=512)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='chat_sync.chatrun')),
            ],
            options={
                'db_table': 'chat_sync_ai_tool_call',
            },
        ),
        migrations.CreateModel(
            name='ChatPendingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ask_user', 'Ask user'), ('client_tool', 'Client tool'), ('consent', 'Consent')], max_length=32)),
                ('request_schema', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('refused', 'Refused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('response_idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('responded_by_device', models.CharField(blank=True, default='', max_length=128)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_interactions', to='chat_sync.chatrun')),
                ('tool_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='chat_sync.chattoolcall')),
            ],
            options={
                'db_table': 'chat_sync_ai_pending_interaction',
            },
        ),
        migrations.CreateModel(
            name='ChatTurnContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('tool_manifest', models.JSONField(blank=True, default=list)),
                ('token_budget', models.JSONField(blank=True, default=dict)),
                ('trim_trace', models.JSONField(blank=True, default=list)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_snapshot', to='chat_sync.chatrun')),
            ],
            options={
                'db_table': 'chat_sync_ai_turn_context_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ChatUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('tool_calls', models.PositiveIntegerField(default=0)),
                ('price_version', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='chat_sync.chatrun')),
            ],
            options={
                'db_table': 'chat_sync_ai_usage_record',
            },
        ),
        migrations.CreateModel(
            name='ChatDeferredToolState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(blank=True, default='', max_length=128)),
                ('tool_name', models.CharField(max_length=128)),
                ('schema_version', models.CharField(default='v1', max_length=64)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_deferred_tools', to='chat_sync.chatthread')),
            ],
            options={
                'db_table': 'chat_sync_ai_deferred_tool_state',
                'constraints': [models.UniqueConstraint(fields=('thread', 'provider_key', 'tool_name'), name='uniq_ai_deferred_thread_provider_tool')],
            },
        ),
        # ChatThread and the legacy chat tables were created with
        # utf8mb4_unicode_ci, while some MySQL installations default to
        # utf8mb4_0900_ai_ci.  MySQL requires identical character set and
        # collation for string foreign-key columns, so normalize every new
        # AI table before Django adds the foreign-key constraints below.
        # The legacy chat tables are normalized as well so fresh databases
        # (where they inherit the server default collation) stay compatible
        # with the AI tables; on existing deployments this is a no-op.
        migrations.RunSQL(
            sql="""
                SET FOREIGN_KEY_CHECKS = 0;
                ALTER TABLE `chat_sync_chatmessageblock`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_chatmessage`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_chatthread`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                SET FOREIGN_KEY_CHECKS = 1;
                ALTER TABLE `chat_sync_ai_run`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_run_event`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_event_outbox`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_thread_preferences`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_thread_run_lock`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_tool_call`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_pending_interaction`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_turn_context_snapshot`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_usage_record`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                ALTER TABLE `chat_sync_ai_deferred_tool_state`
                    CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name='chatrun',
            index=models.Index(fields=['thread', 'status', 'created_at'], name='idx_ai_run_thread_status_time'),
        ),
        migrations.AddIndex(
            model_name='chatrun',
            index=models.Index(fields=['user', 'created_at'], name='idx_ai_run_user_time'),
        ),
        migrations.AddIndex(
            model_name='chatrun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='idx_ai_run_status_lease'),
        ),
        migrations.AddConstraint(
            model_name='chatrun',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_ai_run_user_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='chatrun',
            constraint=models.UniqueConstraint(fields=('assistant_message',), name='uniq_ai_run_assistant_message'),
        ),
        migrations.AddConstraint(
            model_name='chatrun',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='ai_run_max_attempts_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='chatrun',
            constraint=models.CheckConstraint(condition=models.Q(('last_sequence__gte', 0)), name='ai_run_sequence_gte_0'),
        ),
        migrations.AddIndex(
            model_name='chatrunevent',
            index=models.Index(fields=['run', 'sequence'], name='idx_ai_event_run_sequence'),
        ),
        migrations.AddConstraint(
            model_name='chatrunevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_ai_event_run_sequence'),
        ),
        migrations.AddConstraint(
            model_name='chatrunevent',
            constraint=models.UniqueConstraint(fields=('run', 'terminal_marker'), name='uniq_ai_event_terminal_marker'),
        ),
        migrations.AddIndex(
            model_name='chateventoutbox',
            index=models.Index(fields=['status', 'available_at'], name='idx_ai_outbox_status_time'),
        ),
        migrations.AddIndex(
            model_name='chattoolcall',
            index=models.Index(fields=['run', 'status'], name='idx_ai_tool_run_status'),
        ),
        migrations.AddConstraint(
            model_name='chattoolcall',
            constraint=models.UniqueConstraint(fields=('run', 'tool_call_id'), name='uniq_ai_tool_call_run_id'),
        ),
        migrations.AddIndex(
            model_name='chatpendinginteraction',
            index=models.Index(fields=['run', 'status'], name='idx_ai_interaction_run_status'),
        ),
        migrations.AddConstraint(
            model_name='chatpendinginteraction',
            constraint=models.UniqueConstraint(fields=('run', 'response_idempotency_key'), name='uniq_ai_interaction_response_key'),
        ),
        migrations.AddIndex(
            model_name='chatusagerecord',
            index=models.Index(fields=['provider', 'created_at'], name='idx_ai_usage_provider_time'),
        ),
    ]
