# Generated by Django 5.2.12 on 2026-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sync', '0003_chatthread_image_delivery_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='image_delivery_mode',
            field=models.CharField(blank=True, choices=[('directMultimodal', 'Direct Multimodal'), ('localOCR', 'Local Ocr')], db_index=True, max_length=32, null=True),
        ),
    ]
