# Generated by Django 6.0.7 on 2026-08-26 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sync', '0011_chatusagerecord_model_calls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='个人知识库', max_length=128)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared'), ('system', 'System'), ('imported', 'Imported')], default='personal', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('default_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('revision', models.BigIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sync_ai_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('excerpt', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('agent_bound', 'Agent Bound')], default='personal', max_length=32)),
                ('bound_model_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('tool', 'Tool'), ('import', 'Import'), ('web', 'Web')], default='user', max_length=16)),
                ('revision', models.BigIntegerField(default=1)),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('origin_device_id_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('last_device_id_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat_sync.knowledgebase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sync_ai_knowledge_document',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_revision', models.BigIntegerField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('token_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vector_ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat_sync.knowledgedocument')),
            ],
            options={
                'db_table': 'chat_sync_ai_knowledge_chunk',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIndexState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_revision', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('stale', 'Stale')], db_index=True, default='pending', max_length=16)),
                ('chunk_count', models.IntegerField(default=0)),
                ('embedding_provider', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_dimension', models.IntegerField(blank=True, null=True)),
                ('embedding_signature', models.CharField(blank=True, default='', max_length=255)),
                ('index_version', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_state', to='chat_sync.knowledgedocument')),
            ],
            options={
                'db_table': 'chat_sync_ai_knowledge_index_state',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMutationReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mutation_id', models.UUIDField()),
                ('document_id', models.UUIDField(db_index=True)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore')], max_length=16)),
                ('request_hash', models.CharField(max_length=64)),
                ('result_revision', models.BigIntegerField(default=0)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_mutation_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sync_ai_knowledge_mutation_receipt',
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['user', 'server_updated_at', 'id'], name='idx_kbase_user_sync'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('user', 'id'), name='uniq_kbase_user_id'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('user', 'default_slot'), name='uniq_kbase_user_default_slot'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['user', 'server_updated_at', 'id'], name='idx_kdoc_user_sync'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['user', 'knowledge_base', 'is_deleted', 'server_updated_at'], name='idx_kdoc_base_sync'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('user', 'id'), name='uniq_kdoc_user_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'document_revision'], name='idx_kchunk_doc_rev'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'document_revision', 'sequence'), name='uniq_kchunk_doc_rev_seq'),
        ),
        migrations.AddIndex(
            model_name='knowledgemutationreceipt',
            index=models.Index(fields=['user', 'document_id'], name='idx_kreceipt_user_doc'),
        ),
        migrations.AddConstraint(
            model_name='knowledgemutationreceipt',
            constraint=models.UniqueConstraint(fields=('user', 'mutation_id'), name='uniq_kreceipt_user_mutation'),
        ),
    ]
