# Generated by Django 6.0.7 on 2026-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_sync", "0012_knowledgebase_knowledgedocument_knowledgechunk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattoolcall",
            name="execution_mode",
            field=models.CharField(blank=True, default="immediate", max_length=32),
        ),
    ]
