# Generated by Django 6.0.7

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

import chat_sync.ai_models.knowledge


class Migration(migrations.Migration):

    dependencies = [
        ("chat_sync", "0013_chattoolcall_execution_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="retrieval_config",
            field=models.JSONField(blank=True, default=chat_sync.ai_models.knowledge.default_retrieval_config),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="source_file_uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgechunk",
            name="embedding",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="knowledgechunk",
            name="embedding_norm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeindexstate",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="knowledgeindexstate",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="KnowledgeIndexVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("ready", "Ready"), ("failed", "Failed"), ("stale", "Stale")], db_index=True, default="pending", max_length=16)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("signature", models.CharField(blank=True, default="", max_length=128)),
                ("document_count", models.IntegerField(default=0)),
                ("chunk_count", models.IntegerField(default=0)),
                ("embedding_provider", models.CharField(blank=True, default="", max_length=128)),
                ("embedding_model", models.CharField(blank=True, default="", max_length=128)),
                ("embedding_dimension", models.IntegerField(blank=True, null=True)),
                ("chunker_version", models.CharField(blank=True, default="char.v1", max_length=32)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=128)),
                ("error_message", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("knowledge_base", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="index_versions", to="chat_sync.knowledgebase")),
            ],
            options={"db_table": "chat_sync_ai_knowledge_index_version"},
        ),
        migrations.CreateModel(
            name="KnowledgeCommandReceipt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("operation", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("response_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_command_receipts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "chat_sync_ai_knowledge_command_receipt"},
        ),
        migrations.CreateModel(
            name="KnowledgeRetrievalAudit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("run_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("knowledge_base_ids", models.JSONField(blank=True, default=list)),
                ("query_hash", models.CharField(blank=True, default="", max_length=64)),
                ("top_k", models.PositiveSmallIntegerField(default=8)),
                ("score_threshold", models.FloatField(default=0.72)),
                ("hit_count", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("outcome", models.CharField(default="succeeded", max_length=32)),
                ("error_code", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_retrieval_audits", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "chat_sync_ai_knowledge_retrieval_audit"},
        ),
        migrations.AddConstraint(
            model_name="knowledgecommandreceipt",
            constraint=models.UniqueConstraint(fields=("user", "idempotency_key"), name="uniq_kcmd_user_idempotency"),
        ),
        migrations.AddIndex(
            model_name="knowledgeindexversion",
            index=models.Index(fields=["knowledge_base", "-created_at"], name="idx_kidxver_base_created"),
        ),
        migrations.AddIndex(
            model_name="knowledgeretrievalaudit",
            index=models.Index(fields=["user", "-created_at"], name="idx_kretrieval_user_created"),
        ),
    ]
