# Generated by Django 6.0.7 on 2026-08-29 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sync', '0015_chatturncontextsnapshot_tool_manifest_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMemory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('account', 'Account'), ('member', 'Member'), ('agent', 'Agent'), ('thread', 'Thread')], default='account', max_length=16)),
                ('scope_key', models.CharField(max_length=160)),
                ('member_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('agent_key', models.CharField(blank=True, max_length=128, null=True)),
                ('thread_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('layer', models.CharField(choices=[('L2', 'L2'), ('L3', 'L3')], default='L3', max_length=8)),
                ('document_key', models.CharField(max_length=32)),
                ('section_key', models.CharField(default='general', max_length=64)),
                ('memory_type', models.CharField(choices=[('preference', 'Preference'), ('personal_fact', 'Personal Fact'), ('member_fact', 'Member Fact'), ('health_preference', 'Health Preference'), ('instruction', 'Instruction'), ('conversation_summary', 'Conversation Summary')], default='preference', max_length=32)),
                ('normalized_key', models.CharField(max_length=128)),
                ('dedup_key', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('content', models.TextField()),
                ('structured_value', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System'), ('import', 'Import')], default='user', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('confirmation_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='not_required', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('health', 'Health'), ('identity', 'Identity')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('candidate', 'Candidate'), ('superseded', 'Superseded'), ('expired', 'Expired')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('origin_device_id_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('last_device_id_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('revision', models.BigIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by_run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memories', to='chat_sync.chatrun')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='chat_sync.aimemory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sync_ai_memory',
                'indexes': [models.Index(fields=['user', 'server_updated_at', 'id'], name='idx_aimem_user_sync'), models.Index(fields=['user', 'scope_key', 'is_deleted', 'status'], name='idx_aimem_user_scope'), models.Index(fields=['user', 'memory_type', 'normalized_key'], name='idx_aimem_user_type'), models.Index(fields=['expires_at', 'is_deleted', 'status'], name='idx_aimem_expires'), models.Index(fields=['superseded_by'], name='idx_aimem_superseded'), models.Index(fields=['user', 'layer', 'document_key', 'is_deleted'], name='idx_aimem_user_doc')],
                'constraints': [models.UniqueConstraint(fields=('user', 'id'), name='uniq_aimem_user_id'), models.UniqueConstraint(fields=('user', 'dedup_key'), name='uniq_aimem_user_dedup')],
            },
        ),
        migrations.CreateModel(
            name='AIMemoryMutationReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mutation_id', models.UUIDField()),
                ('memory_id', models.UUIDField(db_index=True)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('confirm', 'Confirm'), ('reject', 'Reject'), ('delete', 'Delete')], max_length=16)),
                ('request_hash', models.CharField(max_length=64)),
                ('base_revision', models.BigIntegerField(blank=True, null=True)),
                ('result_revision', models.BigIntegerField(default=0)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory_mutation_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sync_ai_memory_mutation_receipt',
                'indexes': [models.Index(fields=['user', 'memory_id'], name='idx_aimrcpt_user_mem')],
                'constraints': [models.UniqueConstraint(fields=('user', 'mutation_id'), name='uniq_aimrcpt_user_mut')],
            },
        ),
    ]
