# Generated by Django 6.0.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_sync", "0016_aimemory_aimemorymutationreceipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="retrieval_config",
        ),
        migrations.DeleteModel(
            name="KnowledgeChunk",
        ),
        migrations.DeleteModel(
            name="KnowledgeIndexState",
        ),
        migrations.DeleteModel(
            name="KnowledgeIndexVersion",
        ),
        migrations.DeleteModel(
            name="KnowledgeRetrievalAudit",
        ),
    ]
