from django.urls import path

from chat_sync.ai_api.views import (
    ActiveRunView,
    CreateRunView,
    RunCancelView,
    RunDetailView,
    RunContextSummaryView,
    RunEventsView,
    RunRegenerateView,
    RunReadinessView,
    ThreadPreferencesView,
    ThreadToolCatalogView,
    PendingInteractionsView,
    InteractionDetailView,
    InteractionClaimView,
    InteractionHeartbeatView,
    InteractionResponseView,
    InteractionRefuseView,
    WebSocketTicketView,
    CapabilitiesView,
    DeferredToolCatalogView,
    DeferredToolLoadView,
    DeferredToolRevokeView,
)

urlpatterns = [
    path("capabilities/", CapabilitiesView.as_view(), name="chat_ai_capabilities"),
    path("ws-tickets/", WebSocketTicketView.as_view(), name="chat_ai_ws_ticket"),
    path("readiness/", RunReadinessView.as_view(), name="chat_ai_run_readiness"),
    path("threads/<uuid:thread_id>/preferences/", ThreadPreferencesView.as_view(), name="chat_ai_preferences"),
    path("threads/<uuid:thread_id>/tools/", ThreadToolCatalogView.as_view(), name="chat_ai_thread_tool_catalog"),
    path("threads/<uuid:thread_id>/tools/catalog/", DeferredToolCatalogView.as_view(), name="chat_ai_deferred_tool_catalog"),
    path("threads/<uuid:thread_id>/tools/load/", DeferredToolLoadView.as_view(), name="chat_ai_deferred_tool_load"),
    path("threads/<uuid:thread_id>/tools/revoke/", DeferredToolRevokeView.as_view(), name="chat_ai_deferred_tool_revoke"),
    path("threads/<uuid:thread_id>/runs/", CreateRunView.as_view(), name="chat_ai_run_create"),
    path("threads/<uuid:thread_id>/active-run/", ActiveRunView.as_view(), name="chat_ai_active_run"),
    path("runs/<uuid:run_id>/", RunDetailView.as_view(), name="chat_ai_run_detail"),
    path("runs/<uuid:run_id>/context-summary/", RunContextSummaryView.as_view(), name="chat_ai_run_context_summary"),
    path("runs/<uuid:run_id>/events/", RunEventsView.as_view(), name="chat_ai_run_events"),
    path("runs/<uuid:run_id>/cancel/", RunCancelView.as_view(), name="chat_ai_run_cancel"),
    path("runs/<uuid:run_id>/regenerate/", RunRegenerateView.as_view(), name="chat_ai_run_regenerate"),
    path("runs/<uuid:run_id>/interactions/pending/", PendingInteractionsView.as_view(), name="chat_ai_pending_interactions"),
    path("interactions/<uuid:interaction_id>/", InteractionDetailView.as_view(), name="chat_ai_interaction_detail"),
    path("interactions/<uuid:interaction_id>/claim/", InteractionClaimView.as_view(), name="chat_ai_interaction_claim"),
    path("interactions/<uuid:interaction_id>/claim/heartbeat/", InteractionHeartbeatView.as_view(), name="chat_ai_interaction_heartbeat"),
    path("interactions/<uuid:interaction_id>/responses/", InteractionResponseView.as_view(), name="chat_ai_interaction_response"),
    path("interactions/<uuid:interaction_id>/refuse/", InteractionRefuseView.as_view(), name="chat_ai_interaction_refuse"),
]
