# Generated by Django 5.2.12 on 2026-06-09 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='食物标准名称，例如 Coffee', max_length=128)),
                ('localized_name', models.CharField(blank=True, db_comment='食物本地化名称，例如咖啡', default='', max_length=128)),
                ('brand_name', models.CharField(blank=True, db_comment='品牌名称', default='', max_length=128)),
                ('barcode', models.CharField(blank=True, db_comment='包装食品条形码；普通食物为空', db_index=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, db_comment='食物分类，例如主食、水果、饮品', db_index=True, default='', max_length=64)),
                ('serving_quantity', models.DecimalField(blank=True, db_comment='标准份量数值，例如 1', decimal_places=2, max_digits=10, null=True)),
                ('serving_unit', models.CharField(blank=True, db_comment='份量单位，例如 cup、egg、serving', default='', max_length=32)),
                ('serving_description', models.CharField(blank=True, db_comment='份量展示文案，例如 1杯 (237毫升)', default='', max_length=128)),
                ('weight_grams', models.DecimalField(blank=True, db_comment='标准份量折算克重，单位 g', decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, db_comment='食物来源，例如 system、user_custom', default='', max_length=32)),
                ('food_database_id', models.CharField(blank=True, db_comment='关联食物库 ID；第一期可为空', default='', max_length=64)),
                ('confidence', models.DecimalField(blank=True, db_comment='AI 识别置信度', decimal_places=4, max_digits=5, null=True)),
                ('is_verified', models.BooleanField(db_comment='是否经过系统或运营校验', db_index=True, default=False)),
                ('is_active', models.BooleanField(db_comment='是否可用', db_index=True, default=True)),
                ('sort_weight', models.IntegerField(db_comment='列表排序权重；用于常用、推荐、系统预置排序', db_index=True, default=0)),
                ('extra', models.JSONField(blank=True, db_comment='食物项扩展字段', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='食物项创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='食物项最后更新时间', db_index=True)),
                ('user', models.ForeignKey(blank=True, db_comment='创建该食物的账号 ID；系统预置食物为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sort_weight', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('maintain', 'maintain'), ('lose_weight', 'lose_weight'), ('gain_muscle', 'gain_muscle'), ('custom', 'custom')], db_comment='目标类型，例如 maintain、lose_weight', db_index=True, default='maintain', max_length=32)),
                ('daily_energy_target_kcal', models.DecimalField(blank=True, db_comment='每日热量目标，单位 kcal', decimal_places=2, max_digits=10, null=True)),
                ('carbohydrate_target_g', models.DecimalField(blank=True, db_comment='每日碳水化合物目标，单位 g', decimal_places=2, max_digits=10, null=True)),
                ('protein_target_g', models.DecimalField(blank=True, db_comment='每日蛋白质目标，单位 g', decimal_places=2, max_digits=10, null=True)),
                ('fat_target_g', models.DecimalField(blank=True, db_comment='每日脂肪目标，单位 g', decimal_places=2, max_digits=10, null=True)),
                ('meal_distribution', models.JSONField(blank=True, db_comment='餐次目标分配比例，例如 breakfast/lunch/dinner/snack', default=dict)),
                ('effective_from', models.DateField(blank=True, db_comment='目标生效日期', null=True)),
                ('is_active', models.BooleanField(db_comment='是否为当前生效目标', db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='目标创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='目标最后更新时间', db_index=True)),
                ('member', models.ForeignKey(db_comment='目标归属成员 ID', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to='medical.member')),
                ('user', models.ForeignKey(db_comment='目标所属账号 ID', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(db_comment='营养归属业务类型，例如 nutrition_meal_record、nutrition_food_item', db_index=True, max_length=64)),
                ('business_id', models.BigIntegerField(db_comment='营养归属业务 ID，与 business_type 一起定位所属对象', db_index=True)),
                ('nutrient_type', models.CharField(choices=[('energy_kcal', 'energy_kcal'), ('protein_g', 'protein_g'), ('carbohydrate_g', 'carbohydrate_g'), ('fat_g', 'fat_g')], db_comment='营养类型，例如热量、蛋白质、碳水化合物、脂肪', db_index=True, max_length=32)),
                ('value', models.DecimalField(db_comment='营养摄入数值', decimal_places=2, max_digits=10)),
                ('unit', models.CharField(db_comment='营养单位，例如 kcal、g、mg', max_length=16)),
                ('source', models.CharField(blank=True, db_comment='摄入值来源，例如 food_item、manual、photo_ai、system', default='', max_length=32)),
                ('confidence', models.DecimalField(blank=True, db_comment='AI 估算该营养值的置信度，范围 0 到 1', decimal_places=4, max_digits=5, null=True)),
                ('apple_health_id', models.CharField(blank=True, db_comment='Apple 健康写入标识；成功写入 Apple 健康后登记 HealthKit sample UUID', db_index=True, default='', max_length=128)),
                ('extra', models.JSONField(blank=True, db_comment='营养摄入扩展字段', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='营养摄入记录创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='营养摄入记录最后更新时间', db_index=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['business_type', 'business_id', 'nutrient_type'], name='nutrition_n_busines_d3ea15_idx'), models.Index(fields=['apple_health_id'], name='nutrition_n_apple_h_88cdd9_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_type', 'business_id', 'nutrient_type'), name='uniq_nutrition_intake_business_nutrient')],
            },
        ),
        migrations.CreateModel(
            name='NutritionMealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='软删除标记；true 表示业务已删除但数据库保留记录', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='软删除时间；未删除时为空', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间，用于增量同步、列表排序和缓存失效判断', db_index=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack')], db_comment='餐次类型：早餐、午餐、晚餐、小吃', db_index=True, max_length=16)),
                ('consumed_at', models.DateTimeField(db_comment='实际食用时间；由用户选择或创建记录时生成，用于时间线排序', db_index=True)),
                ('local_day', models.DateField(db_comment='用户本地日期；用于日看板、餐次列表和按天聚合', db_index=True)),
                ('title', models.CharField(blank=True, db_comment='饮食记录标题；可为空', default='', max_length=128)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('photo_ai', 'photo_ai'), ('text_ai', 'text_ai'), ('chat_ai', 'chat_ai'), ('apple_health_import', 'apple_health_import')], db_comment='记录来源：手动、拍照 AI、文本 AI、对话 AI、Apple 健康导入等', db_index=True, default='manual', max_length=32)),
                ('source_text', models.TextField(blank=True, db_comment='AI 整理时的用户原始输入文本或识别来源摘要', default='')),
                ('is_ai_estimated', models.BooleanField(db_comment='是否包含 AI 估算结果', db_index=True, default=False)),
                ('ai_confidence', models.DecimalField(blank=True, db_comment='AI 对本餐识别或整理结果的整体置信度，范围 0 到 1', decimal_places=4, max_digits=5, null=True)),
                ('user_edited', models.BooleanField(db_comment='用户是否编辑过 AI 草稿或系统推荐值', db_index=True, default=False)),
                ('extra', models.JSONField(blank=True, db_comment='扩展字段；仅承载一期未结构化但需要保留的信息', default=dict)),
                ('member', models.ForeignKey(db_comment='饮食营养数据归属成员 ID，与账号用户不同，用于家庭成员饮食记录归属', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='medical.member')),
                ('user', models.ForeignKey(db_comment='当前登录账号 ID，用于权限边界、数据归属和跨成员查询隔离', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consumed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionMealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_ratio', models.DecimalField(db_comment='食用比例；全部为 1，1/5 为 0.2', decimal_places=4, default=1, max_digits=8)),
                ('serving_quantity', models.DecimalField(blank=True, db_comment='本次食用份量数值', decimal_places=2, max_digits=10, null=True)),
                ('serving_unit', models.CharField(blank=True, db_comment='本次食用份量单位', default='', max_length=32)),
                ('serving_description', models.CharField(blank=True, db_comment='本次食用份量展示文案', default='', max_length=128)),
                ('display_order', models.IntegerField(db_comment='餐内食物展示顺序', db_index=True, default=0)),
                ('extra', models.JSONField(blank=True, db_comment='餐次食物关联扩展字段', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='餐次食物关联创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='餐次食物关联最后更新时间', db_index=True)),
                ('food_item', models.ForeignKey(db_comment='本次选择的食物 ID', on_delete=django.db.models.deletion.PROTECT, related_name='meal_foods', to='nutrition.nutritionfooditem')),
                ('meal_record', models.ForeignKey(db_comment='所属饮食记录 ID', on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='nutrition.nutritionmealrecord')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='菜谱名称', db_index=True, max_length=128)),
                ('localized_name', models.CharField(blank=True, db_comment='菜谱本地化名称', db_index=True, default='', max_length=128)),
                ('category', models.CharField(blank=True, db_comment='菜谱分类', db_index=True, default='', max_length=64)),
                ('serving_quantity', models.DecimalField(blank=True, db_comment='菜谱标准份量数值', decimal_places=2, max_digits=10, null=True)),
                ('serving_unit', models.CharField(blank=True, db_comment='菜谱标准份量单位', default='', max_length=32)),
                ('serving_description', models.CharField(blank=True, db_comment='菜谱标准份量展示文案', default='', max_length=128)),
                ('source', models.CharField(blank=True, db_comment='菜谱来源', default='', max_length=32)),
                ('is_active', models.BooleanField(db_comment='是否可用', db_index=True, default=True)),
                ('sort_weight', models.IntegerField(db_comment='列表排序权重', db_index=True, default=0)),
                ('extra', models.JSONField(blank=True, db_comment='菜谱扩展字段', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='菜谱创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='菜谱最后更新时间', db_index=True)),
                ('user', models.ForeignKey(blank=True, db_comment='创建该菜谱的账号 ID；系统预置菜谱为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sort_weight', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionRecipeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_ratio', models.DecimalField(db_comment='菜谱内该食物相对标准份量的比例', decimal_places=4, default=1, max_digits=8)),
                ('serving_quantity', models.DecimalField(blank=True, db_comment='菜谱内该食物的份量数值', decimal_places=2, max_digits=10, null=True)),
                ('serving_unit', models.CharField(blank=True, db_comment='菜谱内该食物的份量单位', default='', max_length=32)),
                ('serving_description', models.CharField(blank=True, db_comment='菜谱内该食物的份量展示文案', default='', max_length=128)),
                ('display_order', models.IntegerField(db_comment='菜谱内食物展示顺序', db_index=True, default=0)),
                ('extra', models.JSONField(blank=True, db_comment='菜谱食物关联扩展字段', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='菜谱食物关联创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='菜谱食物关联最后更新时间', db_index=True)),
                ('food_item', models.ForeignKey(db_comment='菜谱内使用的食物 ID', on_delete=django.db.models.deletion.PROTECT, related_name='recipe_foods', to='nutrition.nutritionfooditem')),
                ('recipe', models.ForeignKey(db_comment='所属菜谱 ID', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_foods', to='nutrition.nutritionrecipe')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionAppleHealthIntakeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='软删除标记；true 表示业务已删除但数据库保留记录', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='软删除时间；未删除时为空', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间，用于增量同步、列表排序和缓存失效判断', db_index=True)),
                ('occurred_at', models.DateTimeField(db_comment='Apple 健康营养摄入样本发生时间', db_index=True)),
                ('local_day', models.DateField(db_comment='用户本地日期', db_index=True)),
                ('source_bundle_id', models.CharField(blank=True, db_comment='Apple 健康样本来源 App bundle id', default='', max_length=128)),
                ('source_name', models.CharField(blank=True, db_comment='Apple 健康样本来源名称', default='', max_length=128)),
                ('apple_health_id', models.CharField(db_comment='HealthKit sample UUID，用于幂等去重', db_index=True, max_length=128)),
                ('extra', models.JSONField(blank=True, db_comment='Apple 健康外部营养摄入扩展字段', default=dict)),
                ('member', models.ForeignKey(db_comment='饮食营养数据归属成员 ID，与账号用户不同，用于家庭成员饮食记录归属', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='medical.member')),
                ('user', models.ForeignKey(db_comment='当前登录账号 ID，用于权限边界、数据归属和跨成员查询隔离', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'member', 'local_day'], name='nutrition_n_user_id_918860_idx'), models.Index(fields=['apple_health_id'], name='nutrition_n_apple_h_4b9f17_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'apple_health_id'), name='uniq_nutrition_apple_health_intake_import')],
            },
        ),
        migrations.CreateModel(
            name='NutritionEnergyBurnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='软删除标记；true 表示业务已删除但数据库保留记录', db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='软删除时间；未删除时为空', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间，用于增量同步、列表排序和缓存失效判断', db_index=True)),
                ('burned_at', models.DateTimeField(db_comment='能量消耗发生时间', db_index=True)),
                ('local_day', models.DateField(db_comment='用户本地日期；用于日看板和按天聚合', db_index=True)),
                ('energy_kcal', models.DecimalField(db_comment='消耗能量，单位 kcal', decimal_places=2, max_digits=10)),
                ('activity_type', models.CharField(blank=True, db_comment='活动类型，例如 walking、running', db_index=True, default='', max_length=64)),
                ('duration_seconds', models.IntegerField(blank=True, db_comment='活动持续时长，单位秒', null=True)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('apple_health_import', 'apple_health_import'), ('workout', 'workout'), ('ai_estimated', 'ai_estimated')], db_comment='记录来源', db_index=True, default='manual', max_length=32)),
                ('note', models.CharField(blank=True, db_comment='备注', default='', max_length=255)),
                ('apple_health_id', models.CharField(blank=True, db_comment='Apple 健康样本 UUID', db_index=True, default='', max_length=128)),
                ('extra', models.JSONField(blank=True, db_comment='能量消耗扩展字段', default=dict)),
                ('member', models.ForeignKey(db_comment='饮食营养数据归属成员 ID，与账号用户不同，用于家庭成员饮食记录归属', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='medical.member')),
                ('user', models.ForeignKey(db_comment='当前登录账号 ID，用于权限边界、数据归属和跨成员查询隔离', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-burned_at', '-id'],
                'indexes': [models.Index(fields=['user', 'member', 'local_day'], name='nutrition_n_user_id_cd8785_idx'), models.Index(fields=['apple_health_id'], name='nutrition_n_apple_h_b3bcf0_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutritionFoodFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('nutrition_food_item', 'nutrition_food_item'), ('nutrition_recipe', 'nutrition_recipe')], db_comment='收藏对象类型：食物或菜谱', db_index=True, max_length=64)),
                ('target_id', models.PositiveIntegerField(db_comment='收藏对象 ID', db_index=True)),
                ('is_deleted', models.BooleanField(db_comment='软删除标记；取消收藏时置为 true', db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='收藏创建时间', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='收藏最后更新时间', db_index=True)),
                ('user', models.ForeignKey(db_comment='收藏所属账号 ID；收藏是账号维度偏好', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_food_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'target_type', 'target_id'], name='nutrition_n_user_id_e646c5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='nutritionfooditem',
            index=models.Index(fields=['is_active', 'sort_weight'], name='nutrition_n_is_acti_aa63b7_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionfooditem',
            index=models.Index(fields=['name'], name='nutrition_n_name_598ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionfooditem',
            index=models.Index(fields=['localized_name'], name='nutrition_n_localiz_e50c43_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritiongoal',
            index=models.Index(fields=['user', 'member', 'is_active'], name='nutrition_n_user_id_4f3784_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionmealrecord',
            index=models.Index(fields=['user', 'member', 'local_day', 'meal_type'], name='nutrition_n_user_id_cd1832_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionmealrecord',
            index=models.Index(fields=['user', 'member', 'consumed_at'], name='nutrition_n_user_id_335288_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionmealrecord',
            index=models.Index(fields=['member', 'local_day'], name='nutrition_n_member__2b7909_idx'),
        ),
    ]
