# Generated by Django 5.2.12 on 2026-06-09 02:14

from django.db import migrations

from nutrition.services.seed_data import seed_system_foods, unseed_system_foods


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_system_foods, unseed_system_foods),
    ]
