# Generated by Django 5.2.12 on 2026-06-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_seed_system_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiongoal',
            name='activity_level',
            field=models.CharField(blank=True, db_comment='活跃水平，例如 low、medium、high、very_high', db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='age_years',
            field=models.IntegerField(blank=True, db_comment='年龄快照，由出生日期推导或用户补充', null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='biological_sex',
            field=models.CharField(blank=True, db_comment='生理性别快照，例如 male/female/unknown', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='bmr_kcal',
            field=models.DecimalField(blank=True, db_comment='最近一次计算得到的基础代谢，单位 kcal', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='calculation_formula',
            field=models.CharField(blank=True, db_comment='最近一次计算公式名称，例如 mifflin_st_jeor', default='', max_length=32),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='calculation_inputs',
            field=models.JSONField(blank=True, db_comment='最近一次计算输入和风险快照', default=dict),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='calculation_version',
            field=models.CharField(blank=True, db_comment='最近一次计算公式版本，例如 v1', default='', max_length=32),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, db_comment='当前体重快照，单位 kg；用于目标计算', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='energy_delta_kcal',
            field=models.DecimalField(blank=True, db_comment='根据每周目标换算得到的每日热量差，单位 kcal', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='height_cm',
            field=models.DecimalField(blank=True, db_comment='身高快照，单位 cm；来自成员档案或目标补充页', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='is_energy_target_custom',
            field=models.BooleanField(db_comment='每日热量目标是否由用户手动覆盖', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='is_weekend_energy_enabled',
            field=models.BooleanField(db_comment='是否启用周末热量目标', db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='step_target',
            field=models.IntegerField(blank=True, db_comment='每日步数目标，第一期用于目标页展示和后续运动联动', null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, db_comment='目标体重，单位 kg', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='tdee_kcal',
            field=models.DecimalField(blank=True, db_comment='最近一次计算得到的维持热量，单位 kcal', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='weekend_energy_target_kcal',
            field=models.DecimalField(blank=True, db_comment='周末热量目标，单位 kcal；第一期预留', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='weekly_weight_delta_kg',
            field=models.DecimalField(blank=True, db_comment='每周体重目标变化，单位 kg；减重为负，增重为正', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutritiongoal',
            name='goal_type',
            field=models.CharField(choices=[('maintain', 'maintain'), ('lose_weight', 'lose_weight'), ('gain_weight', 'gain_weight'), ('gain_muscle', 'gain_muscle'), ('build_muscle', 'build_muscle'), ('control_sugar', 'control_sugar'), ('control_salt', 'control_salt'), ('control_fat', 'control_fat'), ('custom', 'custom')], db_comment='目标类型，例如 maintain、lose_weight', db_index=True, default='maintain', max_length=32),
        ),
    ]
