"""智能体头像与公共图片上传的共享常量。"""

# 智能体头像业务关系类型：用于永久保留识别与归属绑定。
BUSINESS_TYPE_CLINICAL_AGENT_AVATAR = "clinical_agent_avatar_upload"

# 医生头像业务关系类型：同样永久保留。
BUSINESS_TYPE_DOCTOR_AVATAR = "doctor_avatar_upload"

# 公开上传接口当前支持的用途。
UPLOAD_PURPOSE_CLINICAL_AGENT_AVATAR = "clinical_agent_avatar"
UPLOAD_PURPOSE_DOCTOR_AVATAR = "doctor_avatar"
ALLOWED_UPLOAD_PURPOSES = {
    UPLOAD_PURPOSE_CLINICAL_AGENT_AVATAR,
    UPLOAD_PURPOSE_DOCTOR_AVATAR,
}

# 用途 → (业务关系类型, Object Key 模板)。
OSS_ROOT_PREFIX = "zhaodkdream/spark_service/hospital"
AGENT_AVATAR_KEY_TEMPLATE = OSS_ROOT_PREFIX + "/avatar/{hospital_id}/{file_uuid}.webp"
DOCTOR_AVATAR_KEY_TEMPLATE = OSS_ROOT_PREFIX + "/doctor/avatar/{hospital_id}/{file_uuid}.webp"
UPLOAD_PURPOSE_CONFIG = {
    UPLOAD_PURPOSE_CLINICAL_AGENT_AVATAR: (BUSINESS_TYPE_CLINICAL_AGENT_AVATAR, AGENT_AVATAR_KEY_TEMPLATE),
    UPLOAD_PURPOSE_DOCTOR_AVATAR: (BUSINESS_TYPE_DOCTOR_AVATAR, DOCTOR_AVATAR_KEY_TEMPLATE),
}

# 永久保留、禁止删除的业务关系类型。
RETENTION_PROTECTED_BUSINESS_TYPES = {
    BUSINESS_TYPE_CLINICAL_AGENT_AVATAR,
    BUSINESS_TYPE_DOCTOR_AVATAR,
}

# 图片约束（BACKOFFICE-HOSPITAL-AGENT-000002）。
AVATAR_MAX_BYTES = 5 * 1024 * 1024
AVATAR_MAX_DIMENSION = 2048
AVATAR_OUTPUT_SIZE = 1024
AVATAR_OUTPUT_CONTENT_TYPE = "image/webp"
