from django.urls import include, path

from backoffice.blacklist_views import (
    AdminAccessDenyHitListView,
    AdminAccessDenyListCreateView,
    AdminAccessDenyRevokeView,
)
from backoffice.views import (
    AdminAITrialActionView,
    AdminAITrialDetailView,
    AdminAITrialListView,
    AdminAIModelCatalogDetailView,
    AdminAIModelCatalogListView,
    AdminAIProviderKeyDetailView,
    AdminAIProviderKeyListView,
    AdminAIToolOptionsView,
    AdminAIServerToolOptionsView,
    AdminAIScenarioBindingDetailView,
    AdminAIScenarioBindingListCreateView,
    AdminAIScenarioSummaryListView,
    AdminSmallTaskDetailView,
    AdminSmallTaskListCreateView,
    AdminAsyncTaskManagerControlView,
    AdminAsyncTaskManagerStatusView,
    AdminAsyncTaskDashboardView,
    AdminAuditLogListView,
    AdminAuthLoginView,
    AdminAuthProfileView,
    AdminAppVersionConfigDetailView,
    AdminAppVersionConfigListCreateView,
    AdminVersionCheckLogListView,
    AdminDashboardOverviewView,
    AdminDeactivationAuditListView,
    AdminDeactivationCancelView,
    AdminDeactivationListView,
    AdminDeactivationRetryView,
    AdminDeviceListView,
    AdminDeviceRevokeView,
    AdminPermissionListCreateView,
    AdminNotificationLogDetailView,
    AdminNotificationLogListView,
    AdminNotificationCampaignListView,
    AdminNotificationPreviewView,
    AdminNotificationSendView,
    AdminNotificationTemplateDetailView,
    AdminNotificationTemplateListCreateView,
    AdminNotificationUserListView,
    AdminRoleDetailView,
    AdminRoleListCreateView,
    AdminRolePermissionAssignView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserProGrantView,
    AdminUserProRecycleView,
    AdminUserRoleAssignView,
    AdminUserStatusView,
)
from backoffice.conversation_views import (
    AdminConversationBlockDetailView,
    AdminConversationMessageDebugView,
    AdminConversationMessageListView,
    AdminConversationThreadListView,
    AdminConversationUserListView,
    AdminConversationUserSummaryView,
)
from backoffice.quick_question_views import (
    AdminGeneratedQuestionRecordDetailView,
    AdminGeneratedQuestionRecordListView,
    AdminQuickQuestionConfigDetailView,
    AdminQuickQuestionConfigDisableView,
    AdminQuickQuestionConfigEnableView,
    AdminQuickQuestionConfigListCreateView,
)
from backoffice.system_log_views import (
    AdminLoginAuditListView,
    AdminSystemLogDetailView,
    AdminSystemLogListView,
    AdminSystemLogModuleListView,
)
from backoffice.medical_data_views import (
    AdminMedicalDataAttachmentDownloadView,
    AdminMedicalDataGlobalStatsView,
    AdminMedicalDataMemberCompleteDataView,
    AdminMedicalDataMemberQualityFlagsView,
    AdminMedicalDataMemberTimelineView,
    AdminMedicalDataResourceDetailView,
    AdminMedicalDataResourceListView,
    AdminMedicalDataSharedRelationsView,
    AdminMedicalDataUserListView,
    AdminMedicalDataUserMembersView,
)

urlpatterns = [
    path("auth/login/", AdminAuthLoginView.as_view(), name="admin-auth-login"),
    path("auth/profile/", AdminAuthProfileView.as_view(), name="admin-auth-profile"),
    path("dashboard/overview/", AdminDashboardOverviewView.as_view(), name="admin-dashboard-overview"),
    path("content/", include("content.admin_urls")),
    path("tasks/dashboard/", AdminAsyncTaskDashboardView.as_view(), name="admin-tasks-dashboard"),
    path("tasks/manager/status/", AdminAsyncTaskManagerStatusView.as_view(), name="admin-tasks-manager-status"),
    path("tasks/manager/<str:action>/", AdminAsyncTaskManagerControlView.as_view(), name="admin-tasks-manager-control"),
    path("users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("users/blacklist/", AdminAccessDenyListCreateView.as_view(), name="admin-user-blacklist"),
    path("users/blacklist/hits/", AdminAccessDenyHitListView.as_view(), name="admin-user-blacklist-hits"),
    path("users/blacklist/<int:entry_id>/revoke/", AdminAccessDenyRevokeView.as_view(), name="admin-user-blacklist-revoke"),
    path("users/<int:user_id>/status/", AdminUserStatusView.as_view(), name="admin-user-status"),
    path("users/<int:user_id>/detail/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("users/<int:user_id>/pro/grant/", AdminUserProGrantView.as_view(), name="admin-user-pro-grant"),
    path("users/<int:user_id>/pro/recycle/", AdminUserProRecycleView.as_view(), name="admin-user-pro-recycle"),
    path("users/<int:user_id>/roles/", AdminUserRoleAssignView.as_view(), name="admin-user-role-assign"),
    path("users/devices/", AdminDeviceListView.as_view(), name="admin-user-device-list"),
    path("users/devices/<int:device_id>/revoke/", AdminDeviceRevokeView.as_view(), name="admin-user-device-revoke"),
    path("users/deactivations/", AdminDeactivationListView.as_view(), name="admin-user-deactivation-list"),
    path("users/deactivations/<int:deactivation_id>/audits/", AdminDeactivationAuditListView.as_view(), name="admin-user-deactivation-audits"),
    path("users/deactivations/<int:deactivation_id>/cancel/", AdminDeactivationCancelView.as_view(), name="admin-user-deactivation-cancel"),
    path("users/deactivations/<int:deactivation_id>/retry/", AdminDeactivationRetryView.as_view(), name="admin-user-deactivation-retry"),
    path("notifications/users/", AdminNotificationUserListView.as_view(), name="admin-notification-users"),
    path("notifications/send/", AdminNotificationSendView.as_view(), name="admin-notification-send"),
    path("notifications/preview/", AdminNotificationPreviewView.as_view(), name="admin-notification-preview"),
    path("notifications/templates/", AdminNotificationTemplateListCreateView.as_view(), name="admin-notification-template-list-create"),
    path("notifications/templates/<int:template_id>/", AdminNotificationTemplateDetailView.as_view(), name="admin-notification-template-detail"),
    path("notifications/campaigns/", AdminNotificationCampaignListView.as_view(), name="admin-notification-campaign-list"),
    path("notifications/logs/<str:channel>/", AdminNotificationLogListView.as_view(), name="admin-notification-log-list"),
    path("notifications/logs/detail/<int:log_id>/", AdminNotificationLogDetailView.as_view(), name="admin-notification-log-detail"),
    path("notification-center/", include("notification_center.urls")),
    path("version/configs/", AdminAppVersionConfigListCreateView.as_view(), name="admin-version-config-list-create"),
    path("version/configs/<int:config_id>/", AdminAppVersionConfigDetailView.as_view(), name="admin-version-config-detail"),
    path("version/logs/", AdminVersionCheckLogListView.as_view(), name="admin-version-check-log-list"),
    path("ai/scenarios/", AdminAIScenarioSummaryListView.as_view(), name="admin-ai-scenario-summary"),
    path("ai/tool-options/", AdminAIToolOptionsView.as_view(), name="admin-ai-tool-options"),
    path("ai/server-tool-options/", AdminAIServerToolOptionsView.as_view(), name="admin-ai-server-tool-options"),
    path("ai/scenarios/<str:scenario_key>/models/", AdminAIScenarioBindingListCreateView.as_view(), name="admin-ai-scenario-models"),
    path("ai/scenario-models/<int:binding_id>/", AdminAIScenarioBindingDetailView.as_view(), name="admin-ai-scenario-binding-detail"),
    path("ai/models/", AdminAIModelCatalogListView.as_view(), name="admin-ai-model-catalog-list"),
    path("ai/models/<int:catalog_id>/", AdminAIModelCatalogDetailView.as_view(), name="admin-ai-model-catalog-detail"),
    path("ai/small-tasks/", AdminSmallTaskListCreateView.as_view(), name="admin-ai-small-task-list"),
    path("ai/small-tasks/<int:task_id>/", AdminSmallTaskDetailView.as_view(), name="admin-ai-small-task-detail"),
    path("ai/providers/", AdminAIProviderKeyListView.as_view(), name="admin-ai-provider-list"),
    path("ai/providers/<int:provider_id>/", AdminAIProviderKeyDetailView.as_view(), name="admin-ai-provider-detail"),
    path("ai/trials/", AdminAITrialListView.as_view(), name="admin-ai-trial-list"),
    path("ai/trials/<int:trial_id>/", AdminAITrialDetailView.as_view(), name="admin-ai-trial-detail"),
    path("ai/trials/<int:trial_id>/<str:action>/", AdminAITrialActionView.as_view(), name="admin-ai-trial-action"),
    path("rbac/roles/", AdminRoleListCreateView.as_view(), name="admin-rbac-role-list-create"),
    path("rbac/roles/<int:role_id>/", AdminRoleDetailView.as_view(), name="admin-rbac-role-detail"),
    path("rbac/roles/<int:role_id>/permissions/", AdminRolePermissionAssignView.as_view(), name="admin-rbac-role-permission-assign"),
    path("rbac/permissions/", AdminPermissionListCreateView.as_view(), name="admin-rbac-permission-list-create"),
    path("audit/logs/", AdminAuditLogListView.as_view(), name="admin-audit-log-list"),
    path("audit/login-logs/", AdminLoginAuditListView.as_view(), name="admin-login-audit-list"),
    path("audit/system-log-modules/", AdminSystemLogModuleListView.as_view(), name="admin-system-log-module-list"),
    path("audit/system-logs/", AdminSystemLogListView.as_view(), name="admin-system-log-list"),
    path("audit/system-logs/detail/", AdminSystemLogDetailView.as_view(), name="admin-system-log-detail"),
    path("conversations/users/", AdminConversationUserListView.as_view(), name="admin-conversation-user-list"),
    path("conversations/users/<int:user_id>/summary/", AdminConversationUserSummaryView.as_view(), name="admin-conversation-user-summary"),
    path("conversations/users/<int:user_id>/threads/", AdminConversationThreadListView.as_view(), name="admin-conversation-thread-list"),
    path("conversations/users/<int:user_id>/threads/<uuid:thread_id>/messages/", AdminConversationMessageListView.as_view(), name="admin-conversation-message-list"),
    path(
        "conversations/users/<int:user_id>/threads/<uuid:thread_id>/messages/<int:message_db_id>/debug/",
        AdminConversationMessageDebugView.as_view(),
        name="admin-conversation-message-debug",
    ),
    path(
        "conversations/users/<int:user_id>/threads/<uuid:thread_id>/blocks/<uuid:block_id>/detail/",
        AdminConversationBlockDetailView.as_view(),
        name="admin-conversation-block-detail",
    ),
    path(
        "conversations/quick-questions/configs/",
        AdminQuickQuestionConfigListCreateView.as_view(),
        name="admin-quick-question-config-list-create",
    ),
    path(
        "conversations/quick-questions/configs/<int:config_id>/",
        AdminQuickQuestionConfigDetailView.as_view(),
        name="admin-quick-question-config-detail",
    ),
    path(
        "conversations/quick-questions/configs/<int:config_id>/enable/",
        AdminQuickQuestionConfigEnableView.as_view(),
        name="admin-quick-question-config-enable",
    ),
    path(
        "conversations/quick-questions/configs/<int:config_id>/disable/",
        AdminQuickQuestionConfigDisableView.as_view(),
        name="admin-quick-question-config-disable",
    ),
    path(
        "conversations/quick-questions/generated-records/",
        AdminGeneratedQuestionRecordListView.as_view(),
        name="admin-quick-question-generated-record-list",
    ),
    path(
        "conversations/quick-questions/generated-records/<int:record_id>/",
        AdminGeneratedQuestionRecordDetailView.as_view(),
        name="admin-quick-question-generated-record-detail",
    ),
    path("medical-data/stats/global/", AdminMedicalDataGlobalStatsView.as_view(), name="admin-medical-data-global-stats"),
    path("medical-data/users/", AdminMedicalDataUserListView.as_view(), name="admin-medical-data-user-list"),
    path("medical-data/users/<int:user_id>/members/", AdminMedicalDataUserMembersView.as_view(), name="admin-medical-data-user-members"),
    path(
        "medical-data/users/<int:user_id>/members/<int:member_id>/timeline/",
        AdminMedicalDataMemberTimelineView.as_view(),
        name="admin-medical-data-member-timeline",
    ),
    path(
        "medical-data/users/<int:user_id>/members/<int:member_id>/quality-flags/",
        AdminMedicalDataMemberQualityFlagsView.as_view(),
        name="admin-medical-data-member-quality-flags",
    ),
    path(
        "medical-data/users/<int:user_id>/members/<int:member_id>/complete-data/",
        AdminMedicalDataMemberCompleteDataView.as_view(),
        name="admin-medical-data-member-complete",
    ),
    path(
        "medical-data/users/<int:user_id>/members/<int:member_id>/shared-relations/",
        AdminMedicalDataSharedRelationsView.as_view(),
        name="admin-medical-data-shared-relations",
    ),
    path(
        "medical-data/users/<int:user_id>/members/<int:member_id>/<str:resource_type>/",
        AdminMedicalDataResourceListView.as_view(),
        name="admin-medical-data-resource-list",
    ),
    path(
        "medical-data/resources/<str:resource_type>/<int:resource_id>/",
        AdminMedicalDataResourceDetailView.as_view(),
        name="admin-medical-data-resource-detail",
    ),
    path(
        "medical-data/attachments/<int:file_id>/download/",
        AdminMedicalDataAttachmentDownloadView.as_view(),
        name="admin-medical-data-attachment-download",
    ),
]
