from django.urls import path

from backoffice.views import (
    AdminAITrialActionView,
    AdminAITrialListView,
    AdminAIModelCatalogDetailView,
    AdminAIModelCatalogListView,
    AdminAIProviderKeyDetailView,
    AdminAIProviderKeyListView,
    AdminAIScenarioBindingDetailView,
    AdminAIScenarioBindingListCreateView,
    AdminAIScenarioSummaryListView,
    AdminAsyncTaskDashboardView,
    AdminAuditLogListView,
    AdminAuthLoginView,
    AdminAuthProfileView,
    AdminDashboardOverviewView,
    AdminPermissionListCreateView,
    AdminRoleDetailView,
    AdminRoleListCreateView,
    AdminRolePermissionAssignView,
    AdminUserListView,
    AdminUserRoleAssignView,
    AdminUserStatusView,
)

urlpatterns = [
    path("auth/login/", AdminAuthLoginView.as_view(), name="admin-auth-login"),
    path("auth/profile/", AdminAuthProfileView.as_view(), name="admin-auth-profile"),
    path("dashboard/overview/", AdminDashboardOverviewView.as_view(), name="admin-dashboard-overview"),
    path("tasks/dashboard/", AdminAsyncTaskDashboardView.as_view(), name="admin-tasks-dashboard"),
    path("users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("users/<int:user_id>/status/", AdminUserStatusView.as_view(), name="admin-user-status"),
    path("users/<int:user_id>/roles/", AdminUserRoleAssignView.as_view(), name="admin-user-role-assign"),
    path("ai/scenarios/", AdminAIScenarioSummaryListView.as_view(), name="admin-ai-scenario-summary"),
    path("ai/scenarios/<str:scenario_key>/models/", AdminAIScenarioBindingListCreateView.as_view(), name="admin-ai-scenario-models"),
    path("ai/scenario-models/<int:binding_id>/", AdminAIScenarioBindingDetailView.as_view(), name="admin-ai-scenario-binding-detail"),
    path("ai/models/", AdminAIModelCatalogListView.as_view(), name="admin-ai-model-catalog-list"),
    path("ai/models/<int:catalog_id>/", AdminAIModelCatalogDetailView.as_view(), name="admin-ai-model-catalog-detail"),
    path("ai/providers/", AdminAIProviderKeyListView.as_view(), name="admin-ai-provider-list"),
    path("ai/providers/<int:provider_id>/", AdminAIProviderKeyDetailView.as_view(), name="admin-ai-provider-detail"),
    path("ai/trials/", AdminAITrialListView.as_view(), name="admin-ai-trial-list"),
    path("ai/trials/<int:trial_id>/<str:action>/", AdminAITrialActionView.as_view(), name="admin-ai-trial-action"),
    path("rbac/roles/", AdminRoleListCreateView.as_view(), name="admin-rbac-role-list-create"),
    path("rbac/roles/<int:role_id>/", AdminRoleDetailView.as_view(), name="admin-rbac-role-detail"),
    path("rbac/roles/<int:role_id>/permissions/", AdminRolePermissionAssignView.as_view(), name="admin-rbac-role-permission-assign"),
    path("rbac/permissions/", AdminPermissionListCreateView.as_view(), name="admin-rbac-permission-list-create"),
    path("audit/logs/", AdminAuditLogListView.as_view(), name="admin-audit-log-list"),
]
