from django.urls import path

from backoffice.views import (
    AdminAITrialActionView,
    AdminAITrialListView,
    AdminAIModelCatalogDetailView,
    AdminAIModelCatalogListView,
    AdminAIProviderKeyDetailView,
    AdminAIProviderKeyListView,
    AdminAIScenarioBindingDetailView,
    AdminAIScenarioBindingListCreateView,
    AdminAIScenarioSummaryListView,
    AdminSmallTaskDetailView,
    AdminSmallTaskListCreateView,
    AdminAsyncTaskManagerControlView,
    AdminAsyncTaskManagerStatusView,
    AdminAsyncTaskDashboardView,
    AdminAuditLogListView,
    AdminAuthLoginView,
    AdminAuthProfileView,
    AdminDashboardOverviewView,
    AdminDeactivationAuditListView,
    AdminDeactivationCancelView,
    AdminDeactivationListView,
    AdminDeactivationRetryView,
    AdminDeviceListView,
    AdminDeviceRevokeView,
    AdminPermissionListCreateView,
    AdminNotificationLogDetailView,
    AdminNotificationLogListView,
    AdminNotificationCampaignListView,
    AdminNotificationPreviewView,
    AdminNotificationSendView,
    AdminNotificationTemplateDetailView,
    AdminNotificationTemplateListCreateView,
    AdminNotificationUserListView,
    AdminRoleDetailView,
    AdminRoleListCreateView,
    AdminRolePermissionAssignView,
    AdminUserListView,
    AdminUserRoleAssignView,
    AdminUserStatusView,
)

urlpatterns = [
    path("auth/login/", AdminAuthLoginView.as_view(), name="admin-auth-login"),
    path("auth/profile/", AdminAuthProfileView.as_view(), name="admin-auth-profile"),
    path("dashboard/overview/", AdminDashboardOverviewView.as_view(), name="admin-dashboard-overview"),
    path("tasks/dashboard/", AdminAsyncTaskDashboardView.as_view(), name="admin-tasks-dashboard"),
    path("tasks/manager/status/", AdminAsyncTaskManagerStatusView.as_view(), name="admin-tasks-manager-status"),
    path("tasks/manager/<str:action>/", AdminAsyncTaskManagerControlView.as_view(), name="admin-tasks-manager-control"),
    path("users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("users/<int:user_id>/status/", AdminUserStatusView.as_view(), name="admin-user-status"),
    path("users/<int:user_id>/roles/", AdminUserRoleAssignView.as_view(), name="admin-user-role-assign"),
    path("users/devices/", AdminDeviceListView.as_view(), name="admin-user-device-list"),
    path("users/devices/<int:device_id>/revoke/", AdminDeviceRevokeView.as_view(), name="admin-user-device-revoke"),
    path("users/deactivations/", AdminDeactivationListView.as_view(), name="admin-user-deactivation-list"),
    path("users/deactivations/<int:deactivation_id>/audits/", AdminDeactivationAuditListView.as_view(), name="admin-user-deactivation-audits"),
    path("users/deactivations/<int:deactivation_id>/cancel/", AdminDeactivationCancelView.as_view(), name="admin-user-deactivation-cancel"),
    path("users/deactivations/<int:deactivation_id>/retry/", AdminDeactivationRetryView.as_view(), name="admin-user-deactivation-retry"),
    path("notifications/users/", AdminNotificationUserListView.as_view(), name="admin-notification-users"),
    path("notifications/send/", AdminNotificationSendView.as_view(), name="admin-notification-send"),
    path("notifications/preview/", AdminNotificationPreviewView.as_view(), name="admin-notification-preview"),
    path("notifications/templates/", AdminNotificationTemplateListCreateView.as_view(), name="admin-notification-template-list-create"),
    path("notifications/templates/<int:template_id>/", AdminNotificationTemplateDetailView.as_view(), name="admin-notification-template-detail"),
    path("notifications/campaigns/", AdminNotificationCampaignListView.as_view(), name="admin-notification-campaign-list"),
    path("notifications/logs/<str:channel>/", AdminNotificationLogListView.as_view(), name="admin-notification-log-list"),
    path("notifications/logs/detail/<int:log_id>/", AdminNotificationLogDetailView.as_view(), name="admin-notification-log-detail"),
    path("ai/scenarios/", AdminAIScenarioSummaryListView.as_view(), name="admin-ai-scenario-summary"),
    path("ai/scenarios/<str:scenario_key>/models/", AdminAIScenarioBindingListCreateView.as_view(), name="admin-ai-scenario-models"),
    path("ai/scenario-models/<int:binding_id>/", AdminAIScenarioBindingDetailView.as_view(), name="admin-ai-scenario-binding-detail"),
    path("ai/models/", AdminAIModelCatalogListView.as_view(), name="admin-ai-model-catalog-list"),
    path("ai/models/<int:catalog_id>/", AdminAIModelCatalogDetailView.as_view(), name="admin-ai-model-catalog-detail"),
    path("ai/small-tasks/", AdminSmallTaskListCreateView.as_view(), name="admin-ai-small-task-list"),
    path("ai/small-tasks/<int:task_id>/", AdminSmallTaskDetailView.as_view(), name="admin-ai-small-task-detail"),
    path("ai/providers/", AdminAIProviderKeyListView.as_view(), name="admin-ai-provider-list"),
    path("ai/providers/<int:provider_id>/", AdminAIProviderKeyDetailView.as_view(), name="admin-ai-provider-detail"),
    path("ai/trials/", AdminAITrialListView.as_view(), name="admin-ai-trial-list"),
    path("ai/trials/<int:trial_id>/<str:action>/", AdminAITrialActionView.as_view(), name="admin-ai-trial-action"),
    path("rbac/roles/", AdminRoleListCreateView.as_view(), name="admin-rbac-role-list-create"),
    path("rbac/roles/<int:role_id>/", AdminRoleDetailView.as_view(), name="admin-rbac-role-detail"),
    path("rbac/roles/<int:role_id>/permissions/", AdminRolePermissionAssignView.as_view(), name="admin-rbac-role-permission-assign"),
    path("rbac/permissions/", AdminPermissionListCreateView.as_view(), name="admin-rbac-permission-list-create"),
    path("audit/logs/", AdminAuditLogListView.as_view(), name="admin-audit-log-list"),
]
