# Generated by Django 5.2.12 on 2026-06-01 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], db_index=True, max_length=20, verbose_name='平台')),
                ('bundle_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='包名/BundleID')),
                ('channel', models.CharField(choices=[('production', 'Production'), ('testflight', 'TestFlight'), ('internal', 'Internal')], db_index=True, default='production', max_length=32, verbose_name='渠道')),
                ('latest_version', models.CharField(max_length=50, verbose_name='最新版本号')),
                ('latest_build', models.CharField(blank=True, default='', max_length=50, verbose_name='最新构建号')),
                ('force_update_min_version', models.CharField(blank=True, default='', max_length=50, verbose_name='强制更新最低版本')),
                ('force_update_min_build', models.CharField(blank=True, default='', max_length=50, verbose_name='强制更新最低构建号')),
                ('update_title', models.CharField(max_length=200, verbose_name='更新标题')),
                ('update_message', models.TextField(verbose_name='更新提示内容')),
                ('release_notes', models.TextField(blank=True, default='', verbose_name='发布说明')),
                ('download_url', models.URLField(max_length=512, verbose_name='下载地址')),
                ('enable_gradual_release', models.BooleanField(default=False, verbose_name='是否开启灰度发布')),
                ('gradual_release_percentage', models.PositiveSmallIntegerField(default=100, verbose_name='灰度发布比例(%)')),
                ('gradual_release_min_version', models.CharField(blank=True, default='', max_length=50, verbose_name='灰度生效最低版本')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_version_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '应用版本配置',
                'verbose_name_plural': '应用版本配置',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VersionCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, max_length=20, verbose_name='平台')),
                ('bundle_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='包名/BundleID')),
                ('channel', models.CharField(blank=True, db_index=True, default='production', max_length=32, verbose_name='渠道')),
                ('current_version', models.CharField(max_length=50, verbose_name='当前版本')),
                ('current_build', models.CharField(blank=True, default='', max_length=50, verbose_name='当前构建号')),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='设备ID')),
                ('system_version', models.CharField(blank=True, default='', max_length=50, verbose_name='系统版本')),
                ('has_update', models.BooleanField(db_index=True, default=False, verbose_name='是否有更新')),
                ('force_update', models.BooleanField(db_index=True, default=False, verbose_name='是否强制更新')),
                ('latest_version', models.CharField(blank=True, default='', max_length=50, verbose_name='返回的最新版本')),
                ('latest_build', models.CharField(blank=True, default='', max_length=50, verbose_name='返回的最新构建号')),
                ('decision_reason', models.CharField(blank=True, default='', max_length=64, verbose_name='版本决策原因')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64, verbose_name='IP地址')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='请求ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='检查时间')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_logs', to='app_version.appversionconfig', verbose_name='关联版本配置')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_check_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '版本检查日志',
                'verbose_name_plural': '版本检查日志',
                'ordering': ['-checked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UpdateActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('force_update_shown', 'Force update shown'), ('optional_update_shown', 'Optional update shown'), ('update_clicked', 'Update clicked'), ('later_clicked', 'Later clicked'), ('dismissed', 'Dismissed')], db_index=True, max_length=50, verbose_name='用户行为')),
                ('device_id', models.CharField(blank=True, default='', max_length=255, verbose_name='设备ID')),
                ('platform', models.CharField(blank=True, default='', max_length=20, verbose_name='平台')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='请求ID')),
                ('action_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='行为时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_update_actions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('check_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app_version.versionchecklog', verbose_name='关联检查日志')),
            ],
            options={
                'verbose_name': '更新行为日志',
                'verbose_name_plural': '更新行为日志',
                'ordering': ['-action_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='appversionconfig',
            index=models.Index(fields=['platform', 'bundle_id', 'channel', 'is_active'], name='app_version_platfor_be18ff_idx'),
        ),
        migrations.AddIndex(
            model_name='appversionconfig',
            index=models.Index(fields=['is_active', 'created_at'], name='app_version_is_acti_bc2d08_idx'),
        ),
        migrations.AddIndex(
            model_name='versionchecklog',
            index=models.Index(fields=['platform', 'checked_at'], name='app_version_platfor_6a708c_idx'),
        ),
        migrations.AddIndex(
            model_name='versionchecklog',
            index=models.Index(fields=['bundle_id', 'device_id', 'checked_at'], name='app_version_bundle__5301e3_idx'),
        ),
        migrations.AddIndex(
            model_name='versionchecklog',
            index=models.Index(fields=['has_update', 'force_update'], name='app_version_has_upd_880e56_idx'),
        ),
        migrations.AddIndex(
            model_name='updateactionlog',
            index=models.Index(fields=['action', 'action_at'], name='app_version_action_44f7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='updateactionlog',
            index=models.Index(fields=['user', 'action_at'], name='app_version_user_id_be838f_idx'),
        ),
    ]
