# Generated by Django 5.2.12 on 2026-05-02 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_version', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversionconfig',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '应用版本配置', 'verbose_name_plural': '应用版本配置'},
        ),
        migrations.AlterModelOptions(
            name='updateactionlog',
            options={'ordering': ['-action_at', '-id'], 'verbose_name': '更新行为日志', 'verbose_name_plural': '更新行为日志'},
        ),
        migrations.AlterModelOptions(
            name='versionchecklog',
            options={'ordering': ['-checked_at', '-id'], 'verbose_name': '版本检查日志', 'verbose_name_plural': '版本检查日志'},
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='bundle_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='包名/BundleID'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='channel',
            field=models.CharField(choices=[('production', 'Production'), ('testflight', 'TestFlight'), ('internal', 'Internal')], db_index=True, default='production', max_length=32, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_version_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='download_url',
            field=models.URLField(max_length=512, verbose_name='下载地址'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='enable_gradual_release',
            field=models.BooleanField(default=False, verbose_name='是否开启灰度发布'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='force_update_min_build',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='强制更新最低构建号'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='force_update_min_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='强制更新最低版本'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='gradual_release_min_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='灰度生效最低版本'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='gradual_release_percentage',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='灰度发布比例(%)'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='latest_build',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='最新构建号'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='latest_version',
            field=models.CharField(max_length=50, verbose_name='最新版本号'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], db_index=True, max_length=20, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='release_notes',
            field=models.TextField(blank=True, default='', verbose_name='发布说明'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='update_message',
            field=models.TextField(verbose_name='更新提示内容'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='update_title',
            field=models.CharField(max_length=200, verbose_name='更新标题'),
        ),
        migrations.AlterField(
            model_name='appversionconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='action',
            field=models.CharField(choices=[('force_update_shown', 'Force update shown'), ('optional_update_shown', 'Optional update shown'), ('update_clicked', 'Update clicked'), ('later_clicked', 'Later clicked'), ('dismissed', 'Dismissed')], db_index=True, max_length=50, verbose_name='用户行为'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='action_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='行为时间'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='check_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app_version.versionchecklog', verbose_name='关联检查日志'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='请求ID'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_update_actions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='bundle_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='包名/BundleID'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='channel',
            field=models.CharField(blank=True, db_index=True, default='production', max_length=32, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='检查时间'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_logs', to='app_version.appversionconfig', verbose_name='关联版本配置'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='current_build',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='当前构建号'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='current_version',
            field=models.CharField(max_length=50, verbose_name='当前版本'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='decision_reason',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='版本决策原因'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='force_update',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否强制更新'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='has_update',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否有更新'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='latest_build',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='返回的最新构建号'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='latest_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='返回的最新版本'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='platform',
            field=models.CharField(db_index=True, max_length=20, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='请求ID'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='system_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='versionchecklog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_check_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
