# Generated by Django 6.0.3 on 2026-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIBootstrapProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", max_length=32, unique=True)),
                ("choose_embedding_model", models.CharField(blank=True, default="", max_length=128)),
                ("optimization_text_model", models.CharField(blank=True, default="", max_length=128)),
                ("optimization_visual_model", models.CharField(blank=True, default="", max_length=128)),
                ("text_to_speech_model", models.CharField(blank=True, default="", max_length=128)),
                ("use_knowledge", models.BooleanField(default=True)),
                ("knowledge_count", models.IntegerField(default=5)),
                ("knowledge_similarity", models.FloatField(default=0.75)),
                ("use_search", models.BooleanField(default=True)),
                ("bilingual_search", models.BooleanField(default=False)),
                ("search_count", models.IntegerField(default=3)),
                ("use_map", models.BooleanField(default=False)),
                ("use_calendar", models.BooleanField(default=False)),
                ("use_weather", models.BooleanField(default=False)),
                ("use_canvas", models.BooleanField(default=False)),
                ("use_code", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="AIModelCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                ("identity", models.CharField(choices=[("model", "Model"), ("agent", "Agent")], default="model", max_length=16)),
                ("position", models.IntegerField(db_index=True, default=0)),
                ("company", models.CharField(max_length=64)),
                ("is_hidden", models.BooleanField(default=False)),
                ("supports_search", models.BooleanField(default=False)),
                ("supports_multimodal", models.BooleanField(default=False)),
                ("supports_reasoning", models.BooleanField(default=False)),
                ("supports_tool_use", models.BooleanField(default=False)),
                ("supports_voice_gen", models.BooleanField(default=False)),
                ("supports_image_gen", models.BooleanField(default=False)),
                ("source", models.CharField(choices=[("system", "System"), ("custom", "Custom")], default="system", max_length=16)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["position", "name"]},
        ),
        migrations.CreateModel(
            name="AIProviderKeyConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("api", "Api"), ("search", "Search"), ("tool", "Tool")], db_index=True, max_length=16)),
                ("name", models.CharField(max_length=128)),
                ("company", models.CharField(max_length=64)),
                ("key", models.CharField(blank=True, default="", max_length=512)),
                ("request_url", models.CharField(max_length=512)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_using", models.BooleanField(default=False)),
                ("capability_class", models.CharField(blank=True, default="", max_length=64)),
                ("help", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(choices=[("system", "System"), ("custom", "Custom")], default="system", max_length=16)),
                ("position", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["kind", "position", "company", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "company", "name"),
                        name="uniq_ai_provider_key_kind_company_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIScenarioConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scenario",
                    models.CharField(
                        choices=[("chat", "Chat"), ("medical_extraction", "Medical Extraction"), ("embedding", "Embedding")],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("endpoint", models.CharField(max_length=512)),
                ("model", models.CharField(max_length=128)),
                ("api_key", models.CharField(blank=True, default="", max_length=512)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.IntegerField(default=2048)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["scenario"]},
        ),
    ]
