# Generated by Django 5.2.12 on 2026-06-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiscenariomodelbinding',
            name='uniq_scenario_model_identity_binding',
        ),
    ]
