# Generated by Django 6.0.3 on 2026-04-04 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialModelPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", max_length=32, unique=True)),
                ("name", models.CharField(default="Default Trial Policy", max_length=64)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="TrialApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "grant_source",
                    models.CharField(
                        choices=[("auto", "Auto"), ("manual", "Manual"), ("application", "Application")],
                        default="auto",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="trial_application", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="TrialModelPolicyItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scenario",
                    models.CharField(
                        choices=[("chat", "Chat"), ("medical_extraction", "Medical Extraction"), ("embedding", "Embedding")],
                        max_length=64,
                    ),
                ),
                ("endpoint", models.CharField(max_length=512)),
                ("model", models.CharField(max_length=128)),
                ("api_key", models.CharField(blank=True, default="", max_length=512)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.IntegerField(default=2048)),
                ("position", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="ai_config.trialmodelpolicy"),
                ),
            ],
            options={
                "ordering": ["position", "scenario", "model"],
                "constraints": [
                    models.UniqueConstraint(fields=("policy", "scenario"), name="uniq_trial_model_policy_scenario"),
                ],
            },
        ),
    ]
