# Generated by Django 6.0.3 on 2026-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_config", "0002_trial_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiproviderkeyconfig",
            name="privacy_policy_url",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
