# Generated by Django 6.0.7 on 2026-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0005_aiscenariomodelbinding_server_tool_scenarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='scenario',
            field=models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('voice', 'Voice'), ('medical_structured_extraction', 'Medical Structured Extraction'), ('medical_document_type_recognition', 'Medical Document Type Recognition'), ('medical_case_extraction', 'Medical Case Extraction'), ('health_exam_extraction', 'Health Exam Extraction'), ('medical_report_extraction', 'Medical Report Extraction'), ('prescription_extraction', 'Prescription Extraction'), ('medication_extraction', 'Medication Extraction'), ('medicine_box_extraction', 'Medicine Box Extraction'), ('optimization_text', 'Optimization Text'), ('optimization_visual', 'Optimization Visual'), ('context_folding', 'Context Folding'), ('router', 'Router'), ('model_config', 'Model Config'), ('report_interpretation', 'Report Interpretation'), ('nutrition_intake_extraction', 'Nutrition Intake Extraction'), ('medical_exam_plan_generation', 'Medical Exam Plan Generation'), ('memory_consolidation', 'Memory Consolidation')], db_comment='场景key', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='scenario',
            field=models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('voice', 'Voice'), ('medical_structured_extraction', 'Medical Structured Extraction'), ('medical_document_type_recognition', 'Medical Document Type Recognition'), ('medical_case_extraction', 'Medical Case Extraction'), ('health_exam_extraction', 'Health Exam Extraction'), ('medical_report_extraction', 'Medical Report Extraction'), ('prescription_extraction', 'Prescription Extraction'), ('medication_extraction', 'Medication Extraction'), ('medicine_box_extraction', 'Medicine Box Extraction'), ('optimization_text', 'Optimization Text'), ('optimization_visual', 'Optimization Visual'), ('context_folding', 'Context Folding'), ('router', 'Router'), ('model_config', 'Model Config'), ('report_interpretation', 'Report Interpretation'), ('nutrition_intake_extraction', 'Nutrition Intake Extraction'), ('medical_exam_plan_generation', 'Medical Exam Plan Generation'), ('memory_consolidation', 'Memory Consolidation')], db_comment='场景key', max_length=64),
        ),
    ]
