# Generated by Django 6.0.3 on 2026-04-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0006_scenario_v2_catalog_slim'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScenarioModelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('chat', 'Chat'), ('optimization_text', 'Optimization Text'), ('optimization_visual', 'Optimization Visual'), ('context_folding', 'Context Folding'), ('router', 'Router'), ('model_config', 'Model Config'), ('report_interpretation', 'Report Interpretation')], db_index=True, max_length=64)),
                ('identity', models.CharField(choices=[('model', 'Model'), ('agent', 'Agent')], default='model', max_length=16)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scenario', 'position', 'model__name'],
            },
        ),
        migrations.RemoveField(
            model_name='aiscenarioconfig',
            name='model',
        ),
        migrations.RemoveConstraint(
            model_name='trialmodelpolicyitem',
            name='uniq_trial_model_policy_scenario',
        ),
        migrations.AddField(
            model_name='trialmodelpolicyitem',
            name='identity',
            field=models.CharField(choices=[('model', 'Model'), ('agent', 'Agent')], default='model', max_length=16),
        ),
        migrations.AddField(
            model_name='trialmodelpolicyitem',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='trialmodelpolicyitem',
            constraint=models.UniqueConstraint(fields=('policy', 'scenario', 'model'), name='uniq_trial_policy_scenario_model'),
        ),
        migrations.AddConstraint(
            model_name='trialmodelpolicyitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('policy', 'scenario'), name='uniq_trial_one_default_per_scenario'),
        ),
        migrations.AddField(
            model_name='aiscenariomodelbinding',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_bindings', to='ai_config.aimodelcatalog'),
        ),
        migrations.DeleteModel(
            name='AIScenarioConfig',
        ),
        migrations.AddConstraint(
            model_name='aiscenariomodelbinding',
            constraint=models.UniqueConstraint(fields=('scenario', 'model'), name='uniq_scenario_model_binding'),
        ),
        migrations.AddConstraint(
            model_name='aiscenariomodelbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('scenario',), name='uniq_scenario_one_default'),
        ),
    ]
