# Generated by Django 6.0.3 on 2026-04-04 23:44

from django.db import migrations, models
from django.db.models import Min


def _backfill_default_markers(apps, schema_editor):
    """Populate nullable unique markers; dedupe if MySQL never enforced partial UNIQUE."""
    Binding = apps.get_model("ai_config", "AIScenarioModelBinding")
    Item = apps.get_model("ai_config", "TrialModelPolicyItem")

    first_binding_ids = set(
        Binding.objects.filter(is_default=True)
        .values("scenario")
        .annotate(min_id=Min("id"))
        .values_list("min_id", flat=True)
    )
    for row in Binding.objects.filter(is_default=True).iterator():
        if row.id in first_binding_ids:
            Binding.objects.filter(pk=row.pk).update(default_marker=f"{row.scenario}:default")
        else:
            Binding.objects.filter(pk=row.pk).update(is_default=False, default_marker=None)

    first_item_ids = set(
        Item.objects.filter(is_default=True)
        .values("policy_id", "scenario")
        .annotate(min_id=Min("id"))
        .values_list("min_id", flat=True)
    )
    for row in Item.objects.filter(is_default=True).iterator():
        if row.id in first_item_ids:
            Item.objects.filter(pk=row.pk).update(
                trial_default_marker=f"p{row.policy_id}_s{row.scenario}:default"
            )
        else:
            Item.objects.filter(pk=row.pk).update(is_default=False, trial_default_marker=None)


def _clear_markers(apps, schema_editor):
    Binding = apps.get_model("ai_config", "AIScenarioModelBinding")
    Item = apps.get_model("ai_config", "TrialModelPolicyItem")
    Binding.objects.all().update(default_marker=None)
    Item.objects.all().update(trial_default_marker=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0007_scenario_multi_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiscenariomodelbinding',
            name='uniq_scenario_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='trialmodelpolicyitem',
            name='uniq_trial_one_default_per_scenario',
        ),
        migrations.AddField(
            model_name='aiscenariomodelbinding',
            name='default_marker',
            field=models.CharField(blank=True, db_index=True, help_text="Set to '<scenario>:default' when is_default; NULL otherwise. Enforces one default per scenario on MySQL.", max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trialmodelpolicyitem',
            name='trial_default_marker',
            field=models.CharField(blank=True, db_index=True, help_text="Set to 'p<policy_id>_s<scenario>:default' when is_default; NULL otherwise (MySQL-safe unique).", max_length=96, null=True, unique=True),
        ),
        migrations.RunPython(_backfill_default_markers, _clear_markers),
    ]
