# Generated by Django 5.2.12 on 2026-04-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0009_expand_scenario_keys'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='aimodelcatalog',
            table_comment='AI模型目录：能力与展示字段；绑定场景见 AIScenarioModelBinding。',
        ),
        migrations.AddField(
            model_name='aimodelcatalog',
            name='ai_tool_scenarios',
            field=models.JSONField(blank=True, db_comment='工具场景key列表JSON对应aiToolScenarios', default=list),
        ),
        migrations.AddField(
            model_name='aimodelcatalog',
            name='brief_description',
            field=models.TextField(blank=True, db_comment='简介briefDescription', default=''),
        ),
        migrations.AddField(
            model_name='aimodelcatalog',
            name='icon',
            field=models.CharField(blank=True, db_comment='图标SF符号或标识', default='', max_length=128),
        ),
        migrations.AddField(
            model_name='aimodelcatalog',
            name='system_provision',
            field=models.TextField(blank=True, db_comment='系统级说明文本systemProvision', default=''),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='company',
            field=models.CharField(db_comment='厂商', max_length=64),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='display_name',
            field=models.CharField(db_comment='展示名称', max_length=128),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='is_hidden',
            field=models.BooleanField(db_comment='是否隐藏', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='name',
            field=models.CharField(db_comment='模型唯一标识', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='position',
            field=models.IntegerField(db_comment='排序权重', db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='price_tier',
            field=models.PositiveSmallIntegerField(db_comment='价格档位0-3', default=0),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='reasoning_controllable',
            field=models.BooleanField(db_comment='推理可控', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], db_comment='来源system或custom', default='system', max_length=16),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='supports_image_gen',
            field=models.BooleanField(db_comment='支持图像生成', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='supports_multimodal',
            field=models.BooleanField(db_comment='支持多模态', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='supports_reasoning',
            field=models.BooleanField(db_comment='支持推理', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='supports_search',
            field=models.BooleanField(db_comment='支持搜索', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='supports_text',
            field=models.BooleanField(db_comment='支持文本', default=True),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='supports_tool_use',
            field=models.BooleanField(db_comment='支持工具调用', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='supports_voice_gen',
            field=models.BooleanField(db_comment='支持语音生成', default=False),
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
    ]
