# Generated by Django 5.2.12 on 2026-04-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0011_scenario_binding_and_trial_item_provision_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='aibootstrapprofile',
            table_comment='AI bootstrap 用户偏好配置档',
        ),
        migrations.AlterModelTableComment(
            name='aiproviderkeyconfig',
            table_comment='AI厂商与工具接入配置',
        ),
        migrations.AlterModelTableComment(
            name='aiscenariomodelbinding',
            table_comment='场景模型绑定：Pro bootstrap 场景列表来源',
        ),
        migrations.AlterModelTableComment(
            name='trialapplication',
            table_comment='用户试用申请与周期',
        ),
        migrations.AlterModelTableComment(
            name='trialmodelpolicy',
            table_comment='试用模型策略主表',
        ),
        migrations.AlterModelTableComment(
            name='trialmodelpolicyitem',
            table_comment='试用策略场景模型明细',
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='bilingual_search',
            field=models.BooleanField(db_comment='是否双语搜索', default=False),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='choose_embedding_model',
            field=models.CharField(blank=True, db_comment='向量嵌入模型名', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='key',
            field=models.CharField(db_comment='配置档主键', default='default', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='knowledge_count',
            field=models.IntegerField(db_comment='知识检索条数', default=5),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='knowledge_similarity',
            field=models.FloatField(db_comment='知识相似度阈值', default=0.75),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='optimization_text_model',
            field=models.CharField(blank=True, db_comment='文本优化默认模型', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='optimization_visual_model',
            field=models.CharField(blank=True, db_comment='视觉优化默认模型', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='search_count',
            field=models.IntegerField(db_comment='搜索条数', default=3),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='text_to_speech_model',
            field=models.CharField(blank=True, db_comment='语音合成模型', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='use_calendar',
            field=models.BooleanField(db_comment='是否启用日历工具', default=False),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='use_canvas',
            field=models.BooleanField(db_comment='是否启用画布', default=False),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='use_code',
            field=models.BooleanField(db_comment='是否启用代码能力', default=False),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='use_knowledge',
            field=models.BooleanField(db_comment='是否启用知识库', default=True),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='use_map',
            field=models.BooleanField(db_comment='是否启用地图工具', default=False),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='use_search',
            field=models.BooleanField(db_comment='是否启用联网搜索', default=True),
        ),
        migrations.AlterField(
            model_name='aibootstrapprofile',
            name='use_weather',
            field=models.BooleanField(db_comment='是否启用天气工具', default=False),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='capability_class',
            field=models.CharField(blank=True, db_comment='能力分类标签', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='company',
            field=models.CharField(db_comment='厂商大写键与模型company对齐', max_length=64),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='help',
            field=models.CharField(blank=True, db_comment='运营侧帮助说明', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='is_hidden',
            field=models.BooleanField(db_comment='是否隐藏', default=False),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='is_using',
            field=models.BooleanField(db_comment='是否当前生效行', default=False),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='key',
            field=models.CharField(blank=True, db_comment='API密钥或令牌', default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='kind',
            field=models.CharField(choices=[('api', 'Api'), ('search', 'Search'), ('tool', 'Tool')], db_comment='配置类型api或search或tool', db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='name',
            field=models.CharField(db_comment='配置展示名', max_length=128),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='position',
            field=models.IntegerField(db_comment='同类型下排序', default=0),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='privacy_policy_url',
            field=models.CharField(blank=True, db_comment='隐私政策链接', default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='request_url',
            field=models.CharField(db_comment='请求基址', max_length=512),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], db_comment='来源system或custom', default='system', max_length=16),
        ),
        migrations.AlterField(
            model_name='aiproviderkeyconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='default_marker',
            field=models.CharField(blank=True, db_comment='默认时为scenario:default否则NULL', db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='identity',
            field=models.CharField(choices=[('model', 'Model'), ('agent', 'Agent')], db_comment='model或agent', default='model', max_length=16),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='is_default',
            field=models.BooleanField(db_comment='是否场景默认', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='max_tokens',
            field=models.IntegerField(db_comment='最大输出token', default=2048),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='model',
            field=models.ForeignKey(db_comment='目录模型', on_delete=django.db.models.deletion.PROTECT, related_name='scenario_bindings', to='ai_config.aimodelcatalog'),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='position',
            field=models.IntegerField(db_comment='场景内排序', db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='scenario',
            field=models.CharField(choices=[('chat', 'Chat'), ('medical_structured_extraction', 'Medical Structured Extraction'), ('medical_document_type_recognition', 'Medical Document Type Recognition'), ('medical_case_extraction', 'Medical Case Extraction'), ('health_exam_extraction', 'Health Exam Extraction'), ('medical_report_extraction', 'Medical Report Extraction'), ('prescription_extraction', 'Prescription Extraction'), ('medication_extraction', 'Medication Extraction'), ('optimization_text', 'Optimization Text'), ('optimization_visual', 'Optimization Visual'), ('context_folding', 'Context Folding'), ('router', 'Router'), ('model_config', 'Model Config'), ('report_interpretation', 'Report Interpretation')], db_comment='场景key', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='temperature',
            field=models.FloatField(db_comment='生成温度', default=0.2),
        ),
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='applied_at',
            field=models.DateTimeField(blank=True, db_comment='申请提交时间', null=True),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_comment='审核通过时间', null=True),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='试用到期时间', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='grant_source',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('application', 'Application')], db_comment='授权来源', default='auto', max_length=16),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='note',
            field=models.CharField(blank=True, db_comment='申请或审核备注', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='rejected_at',
            field=models.DateTimeField(blank=True, db_comment='拒绝时间', null=True),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='started_at',
            field=models.DateTimeField(blank=True, db_comment='试用开始时间', null=True),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_comment='试用状态', db_index=True, default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
        migrations.AlterField(
            model_name='trialapplication',
            name='user',
            field=models.OneToOneField(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, related_name='trial_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicy',
            name='description',
            field=models.CharField(blank=True, db_comment='策略说明', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicy',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicy',
            name='key',
            field=models.CharField(db_comment='策略档主键', default='default', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicy',
            name='name',
            field=models.CharField(db_comment='策略展示名', default='Default Trial Policy', max_length=64),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='identity',
            field=models.CharField(choices=[('model', 'Model'), ('agent', 'Agent')], db_comment='model或agent', default='model', max_length=16),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='is_default',
            field=models.BooleanField(db_comment='是否该场景在策略内默认', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='max_tokens',
            field=models.IntegerField(db_comment='最大输出token', default=2048),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='model',
            field=models.ForeignKey(db_comment='目录模型', on_delete=django.db.models.deletion.PROTECT, related_name='trial_policy_items', to='ai_config.aimodelcatalog'),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='policy',
            field=models.ForeignKey(db_comment='所属策略', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_config.trialmodelpolicy'),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='position',
            field=models.IntegerField(db_comment='策略内排序', default=0),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='scenario',
            field=models.CharField(choices=[('chat', 'Chat'), ('medical_structured_extraction', 'Medical Structured Extraction'), ('medical_document_type_recognition', 'Medical Document Type Recognition'), ('medical_case_extraction', 'Medical Case Extraction'), ('health_exam_extraction', 'Health Exam Extraction'), ('medical_report_extraction', 'Medical Report Extraction'), ('prescription_extraction', 'Prescription Extraction'), ('medication_extraction', 'Medication Extraction'), ('optimization_text', 'Optimization Text'), ('optimization_visual', 'Optimization Visual'), ('context_folding', 'Context Folding'), ('router', 'Router'), ('model_config', 'Model Config'), ('report_interpretation', 'Report Interpretation')], db_comment='场景key', max_length=64),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='temperature',
            field=models.FloatField(db_comment='生成温度', default=0.2),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='trial_default_marker',
            field=models.CharField(blank=True, db_comment='默认时为p策略id_s场景:default否则NULL', db_index=True, max_length=96, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
    ]
