# Generated by Django 5.2.12 on 2026-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0012_alter_aibootstrapprofile_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiscenariomodelbinding',
            name='scenario',
            field=models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('voice', 'Voice'), ('medical_structured_extraction', 'Medical Structured Extraction'), ('medical_document_type_recognition', 'Medical Document Type Recognition'), ('medical_case_extraction', 'Medical Case Extraction'), ('health_exam_extraction', 'Health Exam Extraction'), ('medical_report_extraction', 'Medical Report Extraction'), ('prescription_extraction', 'Prescription Extraction'), ('medication_extraction', 'Medication Extraction'), ('optimization_text', 'Optimization Text'), ('optimization_visual', 'Optimization Visual'), ('context_folding', 'Context Folding'), ('router', 'Router'), ('model_config', 'Model Config'), ('report_interpretation', 'Report Interpretation')], db_comment='场景key', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='trialmodelpolicyitem',
            name='scenario',
            field=models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('voice', 'Voice'), ('medical_structured_extraction', 'Medical Structured Extraction'), ('medical_document_type_recognition', 'Medical Document Type Recognition'), ('medical_case_extraction', 'Medical Case Extraction'), ('health_exam_extraction', 'Health Exam Extraction'), ('medical_report_extraction', 'Medical Report Extraction'), ('prescription_extraction', 'Prescription Extraction'), ('medication_extraction', 'Medication Extraction'), ('optimization_text', 'Optimization Text'), ('optimization_visual', 'Optimization Visual'), ('context_folding', 'Context Folding'), ('router', 'Router'), ('model_config', 'Model Config'), ('report_interpretation', 'Report Interpretation')], db_comment='场景key', max_length=64),
        ),
    ]
