# Generated by Django 5.2.12 on 2026-07-12 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channeldelivery',
            name='success_threshold',
            field=models.CharField(default='provider_accepted', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='sensitive_context_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationtemplateversion',
            name='payload_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='status',
            field=models.CharField(choices=[('queued', '已入队'), ('processing', '处理中'), ('accepted', '已受理'), ('delivered', '已送达'), ('sent', '已发送'), ('failed', '发送失败'), ('partial', '部分成功'), ('skipped', '已跳过')], db_index=True, default='sent', max_length=16),
        ),
        migrations.CreateModel(
            name='AudienceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, default='explicit', max_length=32)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('frozen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience_definition', to='notification_center.notificationcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRecipientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(db_index=True, default='user', max_length=16)),
                ('recipient_key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('created', '已创建'), ('processing', '处理中'), ('accepted', '已受理'), ('delivered', '已送达'), ('partial', '部分完成'), ('failed', '失败'), ('skipped', '已跳过')], db_index=True, default='created', max_length=16)),
                ('routing', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_messages', to='notification_center.notificationcampaign')),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_messages', to='notification_center.notificationintent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_recipient_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='recipient_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='notification_center.notificationrecipientmessage'),
        ),
        migrations.CreateModel(
            name='AudienceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(db_index=True, default='user', max_length=16)),
                ('recipient_key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('included', '已纳入'), ('excluded', '已排除')], db_index=True, default='included', max_length=16)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_snapshots', to='notification_center.notificationcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_audience_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'status', 'position'], name='notificatio_campaig_81cfb6_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'recipient_type', 'recipient_key'), name='uniq_campaign_audience_recipient')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationrecipientmessage',
            constraint=models.UniqueConstraint(fields=('campaign', 'recipient_type', 'recipient_key'), name='uniq_campaign_recipient_message'),
        ),
    ]
