# Generated by Django 5.2.12 on 2026-07-12 22:14

import django.db.models.deletion
from django.db import migrations, models


def seed_business_scenes(apps, schema_editor):
    Scene = apps.get_model("notification_center", "NotificationBusinessScene")
    scene_rows = [
        {
            "key": "account.auth.registration_otp_requested",
            "domain": "account",
            "business_type": "account.auth",
            "event_name": "registration_otp_requested",
            "display_name": "注册验证码",
            "description": "注册手机号或邮箱验证挑战创建时使用。",
            "category": "security",
            "severity": "info",
            "default_template_key": "account_auth_registration_otp",
            "default_routing": {"mode": "parallel", "steps": [{"channel": "sms", "required": True, "success_threshold": "provider_accepted"}]},
            "preference_policy": "mandatory",
            "quiet_hour_policy": "bypass_critical",
            "status": "active",
            "contract_version": 1,
        },
        {
            "key": "account.auth.login_otp_requested",
            "domain": "account",
            "business_type": "account.auth",
            "event_name": "login_otp_requested",
            "display_name": "登录验证码",
            "description": "登录挑战创建时使用。",
            "category": "security",
            "severity": "info",
            "default_template_key": "account_auth_login_otp",
            "default_routing": {"mode": "parallel", "steps": [{"channel": "sms", "required": True, "success_threshold": "provider_accepted"}]},
            "preference_policy": "mandatory",
            "quiet_hour_policy": "bypass_critical",
            "status": "active",
            "contract_version": 1,
        },
        {
            "key": "account.lifecycle.deactivation_requested",
            "domain": "account",
            "business_type": "account.lifecycle",
            "event_name": "deactivation_requested",
            "display_name": "注销申请已受理",
            "description": "用户提交账号注销请求后使用。",
            "category": "transactional",
            "severity": "warning",
            "default_template_key": "account_lifecycle_deactivation_requested",
            "default_routing": {"mode": "parallel", "steps": [{"channel": "in_app", "required": False}, {"channel": "email", "required": False}, {"channel": "sms", "required": False}]},
            "preference_policy": "mandatory",
            "quiet_hour_policy": "bypass_critical",
            "status": "active",
            "contract_version": 1,
        },
        {
            "key": "account.lifecycle.deactivation_completed",
            "domain": "account",
            "business_type": "account.lifecycle",
            "event_name": "deactivation_completed",
            "display_name": "注销完成",
            "description": "账号注销终态完成后使用。",
            "category": "transactional",
            "severity": "critical",
            "default_template_key": "account_lifecycle_deactivation_completed",
            "default_routing": {"mode": "parallel", "steps": [{"channel": "email", "required": False}, {"channel": "sms", "required": False}, {"channel": "in_app", "required": False}]},
            "preference_policy": "mandatory",
            "quiet_hour_policy": "bypass_critical",
            "status": "active",
            "contract_version": 1,
        },
        {
            "key": "operation.campaign.published",
            "domain": "operation",
            "business_type": "operation.campaign",
            "event_name": "published",
            "display_name": "运营活动发布",
            "description": "后台活动或公告发布时使用。",
            "category": "operational",
            "severity": "info",
            "default_template_key": "operation_campaign_published",
            "default_routing": {"mode": "parallel", "steps": [{"channel": "apns", "required": False}, {"channel": "email", "required": False}, {"channel": "sms", "required": False}]},
            "preference_policy": "opt_out",
            "quiet_hour_policy": "respect",
            "status": "active",
            "contract_version": 1,
        },
    ]
    for row in scene_rows:
        Scene.objects.update_or_create(key=row["key"], defaults=row)


def unseed_business_scenes(apps, schema_editor):
    Scene = apps.get_model("notification_center", "NotificationBusinessScene")
    Scene.objects.filter(
        key__in=[
            "account.auth.registration_otp_requested",
            "account.auth.login_otp_requested",
            "account.lifecycle.deactivation_requested",
            "account.lifecycle.deactivation_completed",
            "operation.campaign.published",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notification_center', '0002_channeldelivery_success_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBusinessScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=32)),
                ('business_type', models.CharField(db_index=True, max_length=64)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(choices=[('security', '安全'), ('transactional', '事务性'), ('system', '系统'), ('operational', '运营'), ('marketing', '营销')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', '信息'), ('success', '成功'), ('warning', '警告'), ('critical', '严重')], db_index=True, default='info', max_length=16)),
                ('default_template_key', models.CharField(blank=True, default='', max_length=128)),
                ('default_routing', models.JSONField(blank=True, default=dict)),
                ('variable_schema', models.JSONField(blank=True, default=dict)),
                ('reference_schema', models.JSONField(blank=True, default=dict)),
                ('client_action_schema', models.JSONField(blank=True, default=dict)),
                ('idempotency_strategy', models.CharField(db_index=True, default='event', max_length=32)),
                ('dedupe_window_seconds', models.PositiveIntegerField(default=0)),
                ('preference_policy', models.CharField(db_index=True, default='opt_out', max_length=32)),
                ('quiet_hour_policy', models.CharField(db_index=True, default='respect', max_length=32)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('deprecated', '已弃用'), ('retired', '已退役')], db_index=True, default='draft', max_length=16)),
                ('contract_version', models.PositiveIntegerField(default=1)),
                ('owner_team', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'business_type', 'event_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='actor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='actor_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='business_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='business_reference_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='business_scene',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='scene_contract_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='scene_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='subject_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='subject_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['business_scene', '-created_at'], name='notificatio_busines_d30006_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['business_domain', '-created_at'], name='notificatio_busines_257d41_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['business_type', '-created_at'], name='notificatio_busines_795ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['business_reference_type', 'business_id', '-created_at'], name='notificatio_busines_fb3e29_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['actor_type', 'actor_id', '-created_at'], name='notificatio_actor_t_f1f683_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['subject_type', 'subject_id', '-created_at'], name='notificatio_subject_4d644b_idx'),
        ),
        migrations.AddField(
            model_name='notificationbusinessscene',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_scenes', to='notification_center.notificationtopic'),
        ),
        migrations.AddIndex(
            model_name='notificationbusinessscene',
            index=models.Index(fields=['domain', 'status'], name='notificatio_domain_d9c9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbusinessscene',
            index=models.Index(fields=['business_type', 'status'], name='notificatio_busines_6dc831_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbusinessscene',
            index=models.Index(fields=['category', 'status'], name='notificatio_categor_e71080_idx'),
        ),
        migrations.RunPython(seed_business_scenes, unseed_business_scenes),
    ]
