# Generated by Django 5.2.12 on 2026-07-06 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='分类别名')),
                ('parent_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='父级分类 ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='分类说明')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'content_categories',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['parent_id', 'sort_order'], name='content_cat_parent_sort_idx'), models.Index(fields=['is_active', 'sort_order'], name='content_cat_active_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='文章标题')),
                ('slug', models.CharField(max_length=255, verbose_name='URL 别名')),
                ('locale', models.CharField(db_index=True, default='zh-CN', max_length=16, verbose_name='内容语言')),
                ('translation_group_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='多语言翻译组 ID')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='文章摘要')),
                ('cover_image', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图片 URL')),
                ('content', models.TextField(verbose_name='Markdown 正文')),
                ('content_format', models.CharField(db_index=True, default='markdown', max_length=30, verbose_name='正文格式')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '草稿'), (2, '已发布'), (3, '已下架'), (4, '已归档')], db_index=True, default=0, verbose_name='状态')),
                ('visibility', models.PositiveSmallIntegerField(choices=[(0, '私密'), (1, '公开'), (2, '未列出')], db_index=True, default=1, verbose_name='可见性')),
                ('is_top', models.BooleanField(db_index=True, default=False, verbose_name='是否置顶')),
                ('is_recommended', models.BooleanField(db_index=True, default=False, verbose_name='是否推荐')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='排序权重')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='有效阅读次数')),
                ('reading_time_seconds', models.PositiveBigIntegerField(default=0, verbose_name='累计阅读时长秒数')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO 标题')),
                ('seo_description', models.CharField(blank=True, default='', max_length=500, verbose_name='SEO 描述')),
                ('source_url', models.TextField(blank=True, default='', verbose_name='来源链接')),
                ('references_json', models.JSONField(blank=True, null=True, verbose_name='参考文献')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间')),
                ('offline_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下架时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='软删除时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_articles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_content_articles', to=settings.AUTH_USER_MODEL, verbose_name='最近编辑人')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.contentcategory', verbose_name='主分类')),
            ],
            options={
                'db_table': 'content_articles',
                'ordering': ['-published_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='标签别名')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='标签说明')),
                ('article_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='关联文章数量')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'content_tags',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'article_count'], name='content_tag_active_count_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关联创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tag_links', to='content.contentarticle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tag_links', to='content.contenttag')),
            ],
            options={
                'db_table': 'content_article_tags',
            },
        ),
        migrations.AddField(
            model_name='contentarticle',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='content.ContentArticleTag', to='content.contenttag'),
        ),
        migrations.CreateModel(
            name='ContentArticleOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=32, verbose_name='操作动作')),
                ('from_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='操作前状态')),
                ('to_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='操作后状态')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='操作原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='content.contentarticle')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_article_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_article_operation_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['article', 'created_at'], name='content_op_article_time_idx'), models.Index(fields=['operator', 'created_at'], name='content_op_operator_time_idx'), models.Index(fields=['action', 'created_at'], name='content_op_action_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentArticleReadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(db_index=True, max_length=16, verbose_name='阅读语言')),
                ('event_type', models.CharField(choices=[('view', '详情点击'), ('read_duration', '阅读时长')], db_index=True, max_length=32, verbose_name='事件类型')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='阅读时长秒数')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='App 会话 ID')),
                ('client_platform', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='客户端平台')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上报时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_events', to='content.contentarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_read_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_article_read_events',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['article', 'created_at'], name='content_read_article_time_idx'), models.Index(fields=['user', 'created_at'], name='content_read_user_time_idx'), models.Index(fields=['locale', 'created_at'], name='content_read_locale_time_idx'), models.Index(fields=['event_type', 'created_at'], name='content_read_event_time_idx'), models.Index(fields=['session_id'], name='content_read_session_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('title', models.CharField(max_length=255, verbose_name='快照标题')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='快照摘要')),
                ('content', models.TextField(verbose_name='快照正文')),
                ('content_format', models.CharField(max_length=30, verbose_name='快照正文格式')),
                ('metadata_json', models.JSONField(blank=True, null=True, verbose_name='元数据快照')),
                ('change_note', models.CharField(blank=True, default='', max_length=500, verbose_name='变更说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='版本创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.contentarticle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_article_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_article_versions',
                'ordering': ['-version_no', '-id'],
                'indexes': [models.Index(fields=['article', 'created_at'], name='cont_ver_article_time_idx'), models.Index(fields=['created_by', 'created_at'], name='cont_ver_creator_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'version_no'), name='uniq_content_article_version_no')],
            },
        ),
        migrations.AddIndex(
            model_name='contentarticletag',
            index=models.Index(fields=['tag'], name='content_article_tag_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentarticletag',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='uniq_content_article_tag'),
        ),
        migrations.AddIndex(
            model_name='contentarticle',
            index=models.Index(fields=['category', 'locale', 'status', 'published_at'], name='cont_art_cat_loc_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='contentarticle',
            index=models.Index(fields=['locale', 'status', 'published_at'], name='content_art_loc_stat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='contentarticle',
            index=models.Index(fields=['author', 'status', 'updated_at'], name='content_art_author_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contentarticle',
            index=models.Index(fields=['is_top', 'status', 'published_at'], name='content_art_top_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='contentarticle',
            index=models.Index(fields=['is_recommended', 'status', 'published_at'], name='content_art_rec_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='contentarticle',
            index=models.Index(fields=['translation_group_id'], name='content_art_trans_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentarticle',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='uniq_content_article_locale_slug'),
        ),
        migrations.AddConstraint(
            model_name='contentarticle',
            constraint=models.CheckConstraint(condition=models.Q(('content_format', 'markdown')), name='chk_content_article_markdown'),
        ),
    ]
